/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package palamod.init;

import palamod.block.*;

import palamod.PalamodMod;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.Block;

import java.util.function.Function;

public class PalamodModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(PalamodMod.MODID);
	public static final DeferredBlock<Block> PALADIUM_ORE;
	public static final DeferredBlock<Block> PALADIUM_BLOCK;
	public static final DeferredBlock<Block> TITANE_ORE;
	public static final DeferredBlock<Block> TITANE_BLOCK;
	public static final DeferredBlock<Block> AMETHYST_ORE;
	public static final DeferredBlock<Block> AMETHYST_BLOCK;
	public static final DeferredBlock<Block> PALADIUM_CRUSHER;
	public static final DeferredBlock<Block> ENDIUM_BLOCK;
	public static final DeferredBlock<Block> FINDIUM_ORE;
	public static final DeferredBlock<Block> FINDIUM_BLOCK;
	public static final DeferredBlock<Block> OSTRYA_WOOD_WOOD;
	public static final DeferredBlock<Block> OSTRYA_WOOD_LOG;
	public static final DeferredBlock<Block> OSTRYA_WOOD_PLANKS;
	public static final DeferredBlock<Block> OSTRYA_WOOD_LEAVES;
	public static final DeferredBlock<Block> OSTRYA_WOOD_STAIRS;
	public static final DeferredBlock<Block> OSTRYA_WOOD_SLAB;
	public static final DeferredBlock<Block> OSTRYA_WOOD_FENCE;
	public static final DeferredBlock<Block> OSTRYA_WOOD_FENCE_GATE;
	public static final DeferredBlock<Block> JACARANDA_WOOD;
	public static final DeferredBlock<Block> JACARANDA_LOG;
	public static final DeferredBlock<Block> JACARANDA_PLANKS;
	public static final DeferredBlock<Block> JACARANDA_LEAVES;
	public static final DeferredBlock<Block> JACARANDA_STAIRS;
	public static final DeferredBlock<Block> JACARANDA_SLAB;
	public static final DeferredBlock<Block> JACARANDA_FENCE;
	public static final DeferredBlock<Block> JACARANDA_FENCE_GATE;
	public static final DeferredBlock<Block> NBT_BLOCK;
	public static final DeferredBlock<Block> JUDEECERCIS_WOOD;
	public static final DeferredBlock<Block> JUDEECERCIS_LOG;
	public static final DeferredBlock<Block> JUDEECERCIS_PLANKS;
	public static final DeferredBlock<Block> JUDEECERCIS_LEAVES;
	public static final DeferredBlock<Block> JUDEECERCIS_STAIRS;
	public static final DeferredBlock<Block> JUDEECERCIS_SLAB;
	public static final DeferredBlock<Block> JUDEECERCIS_FENCE;
	public static final DeferredBlock<Block> JUDEECERCIS_FENCE_GATE;
	public static final DeferredBlock<Block> ERABLE_WOOD;
	public static final DeferredBlock<Block> ERABLE_LOG;
	public static final DeferredBlock<Block> ERABLE_PLANKS;
	public static final DeferredBlock<Block> ERABLE_LEAVES;
	public static final DeferredBlock<Block> ERABLE_STAIRS;
	public static final DeferredBlock<Block> ERABLE_SLAB;
	public static final DeferredBlock<Block> ERABLE_FENCE;
	public static final DeferredBlock<Block> ERABLE_FENCE_GATE;
	public static final DeferredBlock<Block> ERABLE_SAPPLING;
	public static final DeferredBlock<Block> JUDEECERCIS_SAPPLING;
	public static final DeferredBlock<Block> OSTRYA_SAPPLING;
	public static final DeferredBlock<Block> JACARANDA_SAPPLING;
	public static final DeferredBlock<Block> FINDIUM_STAIRS;
	public static final DeferredBlock<Block> FINDIUM_SLAB;
	public static final DeferredBlock<Block> XPBUSH;
	public static final DeferredBlock<Block> XPBUSHON;
	public static final DeferredBlock<Block> SLIMEPAD;
	public static final DeferredBlock<Block> PALADIUM_GREEN_ORE;
	public static final DeferredBlock<Block> PALADIUM_GREEN_BLOCK;
	public static final DeferredBlock<Block> ALCHIMET_1;
	public static final DeferredBlock<Block> GRINDER_CASING;
	public static final DeferredBlock<Block> GRINDER_FRAME;
	public static final DeferredBlock<Block> GRINDER_BLOCK;
	public static final DeferredBlock<Block> PALADIUM_FURNACE;
	public static final DeferredBlock<Block> PALADIUM_FURNACE_ON;
	public static final DeferredBlock<Block> OBSIDIAN_TRAPDOOR;
	public static final DeferredBlock<Block> RENFORCED_OBSIDIAN;
	public static final DeferredBlock<Block> OBSIDIAN_DOOR;
	public static final DeferredBlock<Block> COMPACTED_OBSIDIAN;
	public static final DeferredBlock<Block> FAKE_WATER_OBSIDIAN;
	public static final DeferredBlock<Block> LAVA_OBSIDIAN;
	public static final DeferredBlock<Block> IRON_SPIKE;
	public static final DeferredBlock<Block> SPIKE_GOLD;
	public static final DeferredBlock<Block> DIAMOND_SPIKE;
	public static final DeferredBlock<Block> AMETHYST_SPIKE;
	public static final DeferredBlock<Block> TITANE_SPIKE;
	public static final DeferredBlock<Block> PALADIUM_SPIKE;
	public static final DeferredBlock<Block> PALADIUM_FORGE;
	public static final DeferredBlock<Block> TITANE_SLAB;
	public static final DeferredBlock<Block> TITANE_STAIRS;
	public static final DeferredBlock<Block> LOADBLOCK_1T;
	public static final DeferredBlock<Block> TCV_2;
	public static final DeferredBlock<Block> EGGPLANT_0;
	public static final DeferredBlock<Block> EGGPLANT_1;
	public static final DeferredBlock<Block> EGGPLANT_2;
	public static final DeferredBlock<Block> EGGPLANT_3;
	public static final DeferredBlock<Block> PALADIUM_MACHINE;
	public static final DeferredBlock<Block> LUCKY_BLOCK;
	public static final DeferredBlock<Block> CHERVIL_1;
	public static final DeferredBlock<Block> CHERVIL_0;
	public static final DeferredBlock<Block> CHERVIL_2;
	public static final DeferredBlock<Block> CHERVIL_3;
	public static final DeferredBlock<Block> KIWANO_4;
	public static final DeferredBlock<Block> KIWANO_3;
	public static final DeferredBlock<Block> KIWANO_2;
	public static final DeferredBlock<Block> KIWANO_1;
	public static final DeferredBlock<Block> KIWANO_0;
	public static final DeferredBlock<Block> TRESAURE_FALSE;
	public static final DeferredBlock<Block> TRESAURE_TRUE;
	public static final DeferredBlock<Block> ALARM;
	public static final DeferredBlock<Block> MEGA_SAFE_CHEST;
	public static final DeferredBlock<Block> COLORED_LAMP;
	public static final DeferredBlock<Block> COLOFUL_LAMP;
	public static final DeferredBlock<Block> FAKE_PALADIUM_ORE;
	public static final DeferredBlock<Block> ORANGEBLUE_1;
	public static final DeferredBlock<Block> ORANGEBLUE_0;
	public static final DeferredBlock<Block> ORANGEBLUE_2;
	public static final DeferredBlock<Block> ORANGEBLUE_3;
	public static final DeferredBlock<Block> ORANGEBLUE_4;
	public static final DeferredBlock<Block> TRIXIUM_NBT_BLOCK;
	public static final DeferredBlock<Block> PALADIUM_STAIRS;
	public static final DeferredBlock<Block> PALADIUM_SLAB;
	public static final DeferredBlock<Block> AMETHYST_STAIRS;
	public static final DeferredBlock<Block> AMETHYST_SLAB;
	public static final DeferredBlock<Block> ELEVATOR_WHITE;
	public static final DeferredBlock<Block> ELEVATO_RRED;
	public static final DeferredBlock<Block> ELEVATOR_BLUE;
	public static final DeferredBlock<Block> ELEVATOR_GREEN;
	public static final DeferredBlock<Block> ELEVATOR_PINK;
	public static final DeferredBlock<Block> ELEVATORL_IGHT_BLUE;
	public static final DeferredBlock<Block> ELEVATOR_LIGHT_GREEN;
	public static final DeferredBlock<Block> ELEVATOR_BROWN;
	public static final DeferredBlock<Block> ELEVATOR_ORANGE;
	public static final DeferredBlock<Block> ELEVATOR_PURPLE;
	public static final DeferredBlock<Block> ELEVATOR_GRAY;
	public static final DeferredBlock<Block> ELEVATOR_LIGHT_GRAY;
	public static final DeferredBlock<Block> ELEVATOR_CYAN;
	public static final DeferredBlock<Block> GUARDIAN_BLOCK;
	public static final DeferredBlock<Block> STONY;
	public static final DeferredBlock<Block> CLOUD_BLOCK;
	public static final DeferredBlock<Block> CROWN;
	public static final DeferredBlock<Block> FACTION_BLOCK;
	public static final DeferredBlock<Block> BLACK_LUCKY_BLOCK;
	public static final DeferredBlock<Block> JUDEECERCIS_DOOR;
	public static final DeferredBlock<Block> ENDIUM_LUCKY_BLOCK;
	public static final DeferredBlock<Block> ENDIUM_NUGGET_ORE;
	public static final DeferredBlock<Block> ENDIUM_SLAB;
	public static final DeferredBlock<Block> ENDIUM_STAIRS;
	public static final DeferredBlock<Block> GREEN_PALADIUM_STAIRS;
	public static final DeferredBlock<Block> GREEN_PALADIUM_SLAB;
	public static final DeferredBlock<Block> UPLOADER;
	public static final DeferredBlock<Block> OSTRYA_DOOR;
	public static final DeferredBlock<Block> ERABLE_DOOR;
	public static final DeferredBlock<Block> JACARANDA_DOOR;
	public static final DeferredBlock<Block> HDV_BLOCK;
	public static final DeferredBlock<Block> ERABLETRAPDOOR;
	public static final DeferredBlock<Block> FLATTEN_TITANE_CHEST;
	public static final DeferredBlock<Block> FLATTEN_PALADIUM_CHEST;
	public static final DeferredBlock<Block> FLATTEN_AMETHYST_CHEST;
	public static final DeferredBlock<Block> FLATTEN_GREEN_PALADIUM_CHEST;
	public static final DeferredBlock<Block> FLATTEN_ENDIUM_CHEST;
	public static final DeferredBlock<Block> DOWNLOADER;
	public static final DeferredBlock<Block> ALARM_ON;
	public static final DeferredBlock<Block> DEEPSLATE_AMETHYST_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_TITANE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_PALADIUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_TRIXIUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_GREEN_PALADIUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_ENDIUM_NUGGET_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_FINDIUM_ORE;
	public static final DeferredBlock<Block> TRIXIUM_ORE;
	public static final DeferredBlock<Block> TRIXIUM_BLOCK;
	public static final DeferredBlock<Block> CAVE_BLOCK;
	public static final DeferredBlock<Block> PALADIUM_CHEST;
	public static final DeferredBlock<Block> GREEN_PALADIUM_CHEST;
	public static final DeferredBlock<Block> AMETHYST_CHEST;
	public static final DeferredBlock<Block> ENDIUM_CHEST;
	public static final DeferredBlock<Block> TITANE_CHEST;
	public static final DeferredBlock<Block> WOODEN_SPIKE;
	public static final DeferredBlock<Block> WOODEN_OBSIDIAN_SPIKE;
	public static final DeferredBlock<Block> IRON_OBSIDIAN_SPIKE;
	public static final DeferredBlock<Block> GOLDEN_OBSIDIAN_SPIKE;
	public static final DeferredBlock<Block> DIAMOND_OBSIDIAN_SPIKE;
	public static final DeferredBlock<Block> AMETHYS_TOBSIDIAN_SPIKE;
	public static final DeferredBlock<Block> TITANE_OBSIDIAN_SPIKE;
	public static final DeferredBlock<Block> PALADIUM_OBSIDIAN_SPIKE;
	public static final DeferredBlock<Block> ONLINE_DETECTOR;
	public static final DeferredBlock<Block> ONLINE_DETECTOR_ON;
	public static final DeferredBlock<Block> COBBLEBREAKER;
	public static final DeferredBlock<Block> FERTILZED_DIRT;
	public static final DeferredBlock<Block> PRINTINGPRESS;
	public static final DeferredBlock<Block> TYPESETTINGTABLE;
	public static final DeferredBlock<Block> DRAWBRIDGE;
	public static final DeferredBlock<Block> UNKNOWNBLOCK;
	public static final DeferredBlock<Block> COMPRESSEDSPONGE;
	public static final DeferredBlock<Block> SPONGETNT;
	public static final DeferredBlock<Block> LAVASPONGE;
	public static final DeferredBlock<Block> WETLAVASPONGE;
	public static final DeferredBlock<Block> WITHERTNT;
	public static final DeferredBlock<Block> MAGIC_TNT;
	public static final DeferredBlock<Block> COMPACTTNT;
	public static final DeferredBlock<Block> ENDIUMTNT;
	public static final DeferredBlock<Block> RENFORCEDOBSIDIANSTAIRS;
	public static final DeferredBlock<Block> OBSIDIANSTAIRS;
	public static final DeferredBlock<Block> OBSIDIANSLAB;
	public static final DeferredBlock<Block> HARDENED_OBSIDIAN_SLAB;
	public static final DeferredBlock<Block> FAKE_WATER;
	public static final DeferredBlock<Block> ANGELIC_WATER;
	public static final DeferredBlock<Block> SLIME_OBSIDIAN;
	public static final DeferredBlock<Block> POISON_OBSIDIAN;
	public static final DeferredBlock<Block> EXTRACTOR;
	public static final DeferredBlock<Block> BOOM_OBSIDIAN;
	public static final DeferredBlock<Block> MEGABOOMOBSIDIAN;
	public static final DeferredBlock<Block> HARPAGOPHYTUM;
	public static final DeferredBlock<Block> GLUEBALL_RED;
	public static final DeferredBlock<Block> GREEN_GLUEBALL;
	public static final DeferredBlock<Block> GLUEBALL_LIGHT_GREEN;
	public static final DeferredBlock<Block> GLUEBALL_DARK_GREEN;
	public static final DeferredBlock<Block> GLUEBALL_BLUE;
	public static final DeferredBlock<Block> GLUEBALL_PURPLE;
	public static final DeferredBlock<Block> GLUEBALL_YELLOW;
	public static final DeferredBlock<Block> GLUEBALL_CYAN;
	public static final DeferredBlock<Block> GLUEBALL_ORANGE;
	public static final DeferredBlock<Block> GLUEBALL_GRAY;
	public static final DeferredBlock<Block> SLIMEPAD_RED;
	public static final DeferredBlock<Block> SLIMEPAD_BLUE;
	public static final DeferredBlock<Block> SLIMEPAD_ORANGE;
	public static final DeferredBlock<Block> SLIMEPAD_PURPLE;
	public static final DeferredBlock<Block> TOTEMFERTILITY;
	public static final DeferredBlock<Block> XPBUSHLOW;
	public static final DeferredBlock<Block> ROTATED_PALADIUM_HOPPER;
	public static final DeferredBlock<Block> PALADIUM_HOPPER;
	public static final DeferredBlock<Block> TRIXIUMSLAB;
	public static final DeferredBlock<Block> TRIXIUMSTAIRS;
	public static final DeferredBlock<Block> COBBLEBREAKERSERVER;
	public static final DeferredBlock<Block> ROTATED_SLIMEPAD;
	public static final DeferredBlock<Block> ROTATED_RED_SLIMEPAD;
	public static final DeferredBlock<Block> ROTATED_PURPLE_SLIMEPAD;
	public static final DeferredBlock<Block> ROTATED_BLUE_SLIMEPAD;
	public static final DeferredBlock<Block> ROTATED_ORANGE_SLIMEPAD;
	public static final DeferredBlock<Block> WITHEREDOBSIDIAN_0;
	public static final DeferredBlock<Block> WITHEREDOBSIDIAN_1;
	public static final DeferredBlock<Block> WITHEREDOBSIDIAN_2;
	public static final DeferredBlock<Block> WITHEREDOBSIDIAN_3;
	public static final DeferredBlock<Block> WITHEREDOBSIDIAN_4;
	public static final DeferredBlock<Block> WITHEREDOBSIDIAN_5;
	public static final DeferredBlock<Block> WITHEREDOBSIDIAN_6;
	public static final DeferredBlock<Block> WITHEREDOBSIDIAN_7;
	public static final DeferredBlock<Block> WITHEREDOBSIDIAN_8;
	public static final DeferredBlock<Block> WITHEREDOBSIDIAN_9;
	public static final DeferredBlock<Block> WITHEREDOBSIDIAN_10;
	public static final DeferredBlock<Block> WITHEREDOBSIDIAN_11;
	public static final DeferredBlock<Block> WITHEREDOBSIDIAN_12;
	public static final DeferredBlock<Block> WITHEREDOBSIDIAN_13;
	public static final DeferredBlock<Block> MINERDIMENSION_PORTAL;
	public static final DeferredBlock<Block> SOFT_STONE;
	public static final DeferredBlock<Block> SOFTENED_AMETHYST_ORE;
	public static final DeferredBlock<Block> SOFTENED_TITANE_ORE;
	public static final DeferredBlock<Block> SOFTENED_PALADIUM_ORE;
	public static final DeferredBlock<Block> SOFTENED_TRIXIUM_ORE;
	public static final DeferredBlock<Block> SOFTENED_GREEN_PALADIUM_ORE;
	public static final DeferredBlock<Block> SOFTENED_FINDIUM_ORE;
	public static final DeferredBlock<Block> SOFTENED_ENDIUM_NUGGET_ORE;
	public static final DeferredBlock<Block> COBBLED_SOFT_STONE;
	public static final DeferredBlock<Block> SOFTSTONESLAB;
	public static final DeferredBlock<Block> SOFTSTONESTAIRS;
	public static final DeferredBlock<Block> COBBLEDSOFTSTONESLAB;
	public static final DeferredBlock<Block> COBBLEDSOFTSTONESTAIRS;
	public static final DeferredBlock<Block> SOFTENED_COAL_ORE;
	public static final DeferredBlock<Block> SOFTENED_IRON_ORE;
	public static final DeferredBlock<Block> SOFTENED_GOLD_ORE;
	public static final DeferredBlock<Block> SOFTENED_DIAMOND_ORE;
	public static final DeferredBlock<Block> SOFTENED_REDSTONE_ORE;
	public static final DeferredBlock<Block> SOFTENED_LAPIS_LAZULIS_ORE;
	public static final DeferredBlock<Block> FLOWERTOTEM;
	public static final DeferredBlock<Block> MINERALFLOWER;
	public static final DeferredBlock<Block> ENDIUMFLOWER;
	public static final DeferredBlock<Block> ENDIUMFLOWERON;
	public static final DeferredBlock<Block> CLATHRUSARCHERI;
	public static final DeferredBlock<Block> PALADIUMFLOWER;
	public static final DeferredBlock<Block> DANKABLOCK;
<<<<<<< Updated upstream
	public static final DeferredBlock<Block> BROKENSPAWNER;
	public static final DeferredBlock<Block> SPAWNCONTROLLER;
	public static final DeferredBlock<Block> EMPTYSPAWNER;
	public static final DeferredBlock<Block> DIAMONDINFUSEDOBSIDIAN;
	public static final DeferredBlock<Block> AMETHYSTINFUSEDOBSIDIAN;
	public static final DeferredBlock<Block> TITANEINFUSEDOBSIDIAN;
	public static final DeferredBlock<Block> PALADIUMINFUSEDOBSIDIAN;
=======
	public static final DeferredBlock<Block> BROKEN_SPAWNER;
	public static final DeferredBlock<Block> SPAWN_CONTROLLER;
	public static final DeferredBlock<Block> EMPTY_SPAWNER;
	public static final DeferredBlock<Block> DIAMOND_INFUSED_OBSIDIAN;
	public static final DeferredBlock<Block> AMETHYST_INFUSED_OBSIDIAN;
	public static final DeferredBlock<Block> TITANE_INFUSED_OBSIDIAN;
	public static final DeferredBlock<Block> PALADIUM_INFUSED_OBSIDIAN;
	public static final DeferredBlock<Block> DEAD_LOG;
	public static final DeferredBlock<Block> DEAD_WOOD;
	public static final DeferredBlock<Block> STRIPPED_DEAD_LOG;
	public static final DeferredBlock<Block> STRIPPED_DEAD_WOOD;
	public static final DeferredBlock<Block> DEAD_PLANKS;
	public static final DeferredBlock<Block> DEAD_STAIRS;
	public static final DeferredBlock<Block> DEAD_SLAB;
	public static final DeferredBlock<Block> DEAD_FENCE;
	public static final DeferredBlock<Block> DEAD_FENCE_GATE;
	public static final DeferredBlock<Block> DEAD_DOOR;
	public static final DeferredBlock<Block> DEAD_TRAPDOOR;
	public static final DeferredBlock<Block> DEAD_PRESSURE_PLATE;
	public static final DeferredBlock<Block> DEAD_BUTTON;
	public static final DeferredBlock<Block> FROZEN_OBSIDIAN;
	public static final DeferredBlock<Block> KNOCKBACK_OBSIDIAN;
	public static final DeferredBlock<Block> AMETHYST_ANVIL;
	public static final DeferredBlock<Block> TITANE_ANVIL;
	public static final DeferredBlock<Block> PALADIUM_ANVIL;
	public static final DeferredBlock<Block> MONEY_ANVIL;
	public static final DeferredBlock<Block> AMETHYSTANVIL_2;
>>>>>>> Stashed changes
	static {
		PALADIUM_ORE = register("paladium_ore", PaladiumOreBlock::new);
		PALADIUM_BLOCK = register("paladium_block", PaladiumBlockBlock::new);
		TITANE_ORE = register("titane_ore", TitaneOreBlock::new);
		TITANE_BLOCK = register("titane_block", TitaneBlockBlock::new);
		AMETHYST_ORE = register("amethyst_ore", AmethysteOreBlock::new);
		AMETHYST_BLOCK = register("amethyst_block", AmethysteBlockBlock::new);
		PALADIUM_CRUSHER = register("paladium_crusher", PaladiumcrusherBlock::new);
		ENDIUM_BLOCK = register("endium_block", EndiumBlockBlock::new);
		FINDIUM_ORE = register("findium_ore", FindiumOreBlock::new);
		FINDIUM_BLOCK = register("findium_block", FindiumBlockBlock::new);
		OSTRYA_WOOD_WOOD = register("ostrya_wood_wood", Ostrya_woodWoodBlock::new);
		OSTRYA_WOOD_LOG = register("ostrya_wood_log", Ostrya_woodLogBlock::new);
		OSTRYA_WOOD_PLANKS = register("ostrya_wood_planks", Ostrya_woodPlanksBlock::new);
		OSTRYA_WOOD_LEAVES = register("ostrya_wood_leaves", Ostrya_woodLeavesBlock::new);
		OSTRYA_WOOD_STAIRS = register("ostrya_wood_stairs", Ostrya_woodStairsBlock::new);
		OSTRYA_WOOD_SLAB = register("ostrya_wood_slab", Ostrya_woodSlabBlock::new);
		OSTRYA_WOOD_FENCE = register("ostrya_wood_fence", Ostrya_woodFenceBlock::new);
		OSTRYA_WOOD_FENCE_GATE = register("ostrya_wood_fence_gate", Ostrya_woodFenceGateBlock::new);
		JACARANDA_WOOD = register("jacaranda_wood", Jacaranda_WoodBlock::new);
		JACARANDA_LOG = register("jacaranda_log", Jacaranda_LogBlock::new);
		JACARANDA_PLANKS = register("jacaranda_planks", Jacaranda_PlanksBlock::new);
		JACARANDA_LEAVES = register("jacaranda_leaves", Jacaranda_LeavesBlock::new);
		JACARANDA_STAIRS = register("jacaranda_stairs", Jacaranda_StairsBlock::new);
		JACARANDA_SLAB = register("jacaranda_slab", Jacaranda_SlabBlock::new);
		JACARANDA_FENCE = register("jacaranda_fence", Jacaranda_FenceBlock::new);
		JACARANDA_FENCE_GATE = register("jacaranda_fence_gate", Jacaranda_FenceGateBlock::new);
		NBT_BLOCK = register("nbt_block", NbtblockBlock::new);
		JUDEECERCIS_WOOD = register("judeecercis_wood", Judeecercis_WoodBlock::new);
		JUDEECERCIS_LOG = register("judeecercis_log", Judeecercis_LogBlock::new);
		JUDEECERCIS_PLANKS = register("judeecercis_planks", Judeecercis_PlanksBlock::new);
		JUDEECERCIS_LEAVES = register("judeecercis_leaves", Judeecercis_LeavesBlock::new);
		JUDEECERCIS_STAIRS = register("judeecercis_stairs", Judeecercis_StairsBlock::new);
		JUDEECERCIS_SLAB = register("judeecercis_slab", Judeecercis_SlabBlock::new);
		JUDEECERCIS_FENCE = register("judeecercis_fence", Judeecercis_FenceBlock::new);
		JUDEECERCIS_FENCE_GATE = register("judeecercis_fence_gate", Judeecercis_FenceGateBlock::new);
		ERABLE_WOOD = register("erable_wood", Erable_WoodBlock::new);
		ERABLE_LOG = register("erable_log", Erable_LogBlock::new);
		ERABLE_PLANKS = register("erable_planks", Erable_PlanksBlock::new);
		ERABLE_LEAVES = register("erable_leaves", Erable_LeavesBlock::new);
		ERABLE_STAIRS = register("erable_stairs", Erable_StairsBlock::new);
		ERABLE_SLAB = register("erable_slab", Erable_SlabBlock::new);
		ERABLE_FENCE = register("erable_fence", Erable_FenceBlock::new);
		ERABLE_FENCE_GATE = register("erable_fence_gate", Erable_FenceGateBlock::new);
		ERABLE_SAPPLING = register("erable_sappling", ErablesapplingBlock::new);
		JUDEECERCIS_SAPPLING = register("judeecercis_sappling", JudeecercissapplingBlock::new);
		OSTRYA_SAPPLING = register("ostrya_sappling", OstryasapplingBlock::new);
		JACARANDA_SAPPLING = register("jacaranda_sappling", JacarandasapplingBlock::new);
		FINDIUM_STAIRS = register("findium_stairs", FindiumstairsBlock::new);
		FINDIUM_SLAB = register("findium_slab", FindiumslabBlock::new);
<<<<<<< Updated upstream
		XPBUSH = register("xpbush", XpbushBlock::new);
		XPBUSHON = register("xpbushon", XpbushonBlock::new);
=======
		XP_BUSH = register("xp_bush", XpbushBlock::new);
		XP_BUSH_ON = register("xp_bush_on", XpbushonBlock::new);
>>>>>>> Stashed changes
		SLIMEPAD = register("slimepad", SlimepadBlock::new);
		PALADIUM_GREEN_ORE = register("paladium_green_ore", PaladiumGreenoreBlock::new);
		PALADIUM_GREEN_BLOCK = register("paladium_green_block", PaladiumGreenblockBlock::new);
		ALCHIMET_1 = register("alchimet_1", Alchimet1Block::new);
		GRINDER_CASING = register("grinder_casing", GrindercasingBlock::new);
		GRINDER_FRAME = register("grinder_frame", GrinderframeBlock::new);
		GRINDER_BLOCK = register("grinder_block", GrinderblockBlock::new);
		PALADIUM_FURNACE = register("paladium_furnace", PaladiumfurnaceBlock::new);
		PALADIUM_FURNACE_ON = register("paladium_furnace_on", PaladiumfurnaceonBlock::new);
		OBSIDIAN_TRAPDOOR = register("obsidian_trapdoor", ObsidiantrapdoorBlock::new);
		RENFORCED_OBSIDIAN = register("renforced_obsidian", RenforcedobsidianBlock::new);
		OBSIDIAN_DOOR = register("obsidian_door", ObsidiandoorBlock::new);
		COMPACTED_OBSIDIAN = register("compacted_obsidian", CompactedobsidianBlock::new);
		FAKE_WATER_OBSIDIAN = register("fake_water_obsidian", FakewaterobsidianBlock::new);
		LAVA_OBSIDIAN = register("lava_obsidian", LavaobsidianBlock::new);
		IRON_SPIKE = register("iron_spike", IronspikeBlock::new);
		SPIKE_GOLD = register("spike_gold", SpikegoldBlock::new);
		DIAMOND_SPIKE = register("diamond_spike", DiamondspikeBlock::new);
		AMETHYST_SPIKE = register("amethyst_spike", AmetystespikeBlock::new);
		TITANE_SPIKE = register("titane_spike", TitanespikeBlock::new);
		PALADIUM_SPIKE = register("paladium_spike", PaladiumspikeBlock::new);
		PALADIUM_FORGE = register("paladium_forge", PaladiumforgeBlock::new);
		TITANE_SLAB = register("titane_slab", TitaneslabBlock::new);
		TITANE_STAIRS = register("titane_stairs", TitanestairsBlock::new);
		LOADBLOCK_1T = register("loadblock_1t", Loadblock1tBlock::new);
		TCV_2 = register("tcv_2", Tcv2Block::new);
		EGGPLANT_0 = register("eggplant_0", Eggplant0Block::new);
		EGGPLANT_1 = register("eggplant_1", Eggplant1Block::new);
		EGGPLANT_2 = register("eggplant_2", Eggplant2Block::new);
		EGGPLANT_3 = register("eggplant_3", Eggplant3Block::new);
		PALADIUM_MACHINE = register("paladium_machine", PaladiummachineBlock::new);
		LUCKY_BLOCK = register("lucky_block", LuckyblockBlock::new);
		CHERVIL_1 = register("chervil_1", Chervil1Block::new);
		CHERVIL_0 = register("chervil_0", Chervil0Block::new);
		CHERVIL_2 = register("chervil_2", Chervil2Block::new);
		CHERVIL_3 = register("chervil_3", Chervil3Block::new);
		KIWANO_4 = register("kiwano_4", Kiwano4Block::new);
		KIWANO_3 = register("kiwano_3", Kiwano3Block::new);
		KIWANO_2 = register("kiwano_2", Kiwano2Block::new);
		KIWANO_1 = register("kiwano_1", Kiwano1Block::new);
		KIWANO_0 = register("kiwano_0", Kiwano0Block::new);
		TRESAURE_FALSE = register("tresaure_false", FalsetresureBlock::new);
		TRESAURE_TRUE = register("tresaure_true", TruetresureBlock::new);
		ALARM = register("alarm", AlarmBlock::new);
		MEGA_SAFE_CHEST = register("mega_safe_chest", MegasafechestBlock::new);
		COLORED_LAMP = register("colored_lamp", ColoredlampBlock::new);
		COLOFUL_LAMP = register("coloful_lamp", ColofullampBlock::new);
		FAKE_PALADIUM_ORE = register("fake_paladium_ore", FakepaladiumoreBlock::new);
		ORANGEBLUE_1 = register("orangeblue_1", Orangeblue1Block::new);
		ORANGEBLUE_0 = register("orangeblue_0", Orangeblue0Block::new);
		ORANGEBLUE_2 = register("orangeblue_2", Orangeblue2Block::new);
		ORANGEBLUE_3 = register("orangeblue_3", Orangeblue3Block::new);
		ORANGEBLUE_4 = register("orangeblue_4", Orangeblue4Block::new);
		TRIXIUM_NBT_BLOCK = register("trixium_nbt_block", TrixiumnbtblockBlock::new);
		PALADIUM_STAIRS = register("paladium_stairs", PaladiumstairsBlock::new);
		PALADIUM_SLAB = register("paladium_slab", PaladiumslabBlock::new);
		AMETHYST_STAIRS = register("amethyst_stairs", AmethyststairsBlock::new);
		AMETHYST_SLAB = register("amethyst_slab", AmethystslabBlock::new);
		ELEVATOR_WHITE = register("elevator_white", ElevatorwhiteBlock::new);
<<<<<<< Updated upstream
		ELEVATO_RRED = register("elevato_rred", ElevatorredBlock::new);
		ELEVATOR_BLUE = register("elevator_blue", ElevatorblueBlock::new);
		ELEVATOR_GREEN = register("elevator_green", ElevatorgreenBlock::new);
		ELEVATOR_PINK = register("elevator_pink", ElevatorpinkBlock::new);
		ELEVATORL_IGHT_BLUE = register("elevatorl_ight_blue", ElevatorlightblueBlock::new);
=======
		ELEVATOR_RED = register("elevator_red", ElevatorredBlock::new);
		ELEVATOR_BLUE = register("elevator_blue", ElevatorblueBlock::new);
		ELEVATOR_GREEN = register("elevator_green", ElevatorgreenBlock::new);
		ELEVATOR_PINK = register("elevator_pink", ElevatorpinkBlock::new);
		ELEVATOR_LIGHT_BLUE = register("elevator_light_blue", ElevatorlightblueBlock::new);
>>>>>>> Stashed changes
		ELEVATOR_LIGHT_GREEN = register("elevator_light_green", ElevatorlightgreenBlock::new);
		ELEVATOR_BROWN = register("elevator_brown", ElevatorbrownBlock::new);
		ELEVATOR_ORANGE = register("elevator_orange", ElevatororangeBlock::new);
		ELEVATOR_PURPLE = register("elevator_purple", ElevatorpurpleBlock::new);
		ELEVATOR_GRAY = register("elevator_gray", ElevatorgrayBlock::new);
		ELEVATOR_LIGHT_GRAY = register("elevator_light_gray", ElevatorlightgrayBlock::new);
		ELEVATOR_CYAN = register("elevator_cyan", ElevatorcyanBlock::new);
		GUARDIAN_BLOCK = register("guardian_block", GuardianblockBlock::new);
		STONY = register("stony", StonyBlock::new);
		CLOUD_BLOCK = register("cloud_block", CloudblockBlock::new);
		CROWN = register("crown", CrownBlock::new);
		FACTION_BLOCK = register("faction_block", FactionblckBlock::new);
		BLACK_LUCKY_BLOCK = register("black_lucky_block", BlackluckyblockBlock::new);
		JUDEECERCIS_DOOR = register("judeecercis_door", JudeecercisdoorBlock::new);
		ENDIUM_LUCKY_BLOCK = register("endium_lucky_block", EndiumluckyblockBlock::new);
		ENDIUM_NUGGET_ORE = register("endium_nugget_ore", EndiumnuggetoreBlock::new);
		ENDIUM_SLAB = register("endium_slab", EndiumslabBlock::new);
		ENDIUM_STAIRS = register("endium_stairs", EndiumstairsBlock::new);
		GREEN_PALADIUM_STAIRS = register("green_paladium_stairs", GreenpaladiumstairsBlock::new);
		GREEN_PALADIUM_SLAB = register("green_paladium_slab", GreenpaladiumslabBlock::new);
		UPLOADER = register("uploader", UploaderBlock::new);
		OSTRYA_DOOR = register("ostrya_door", OstryadoorBlock::new);
		ERABLE_DOOR = register("erable_door", ErabledoorBlock::new);
		JACARANDA_DOOR = register("jacaranda_door", JacarandadoorBlock::new);
		HDV_BLOCK = register("hdv_block", HdvblockBlock::new);
<<<<<<< Updated upstream
		ERABLETRAPDOOR = register("erabletrapdoor", ErabletrapdoorBlock::new);
=======
		ERABLE_TRAPDOOR = register("erable_trapdoor", ErabletrapdoorBlock::new);
>>>>>>> Stashed changes
		FLATTEN_TITANE_CHEST = register("flatten_titane_chest", TitanechestBlock::new);
		FLATTEN_PALADIUM_CHEST = register("flatten_paladium_chest", PaladiumchestBlock::new);
		FLATTEN_AMETHYST_CHEST = register("flatten_amethyst_chest", AmethystchestBlock::new);
		FLATTEN_GREEN_PALADIUM_CHEST = register("flatten_green_paladium_chest", GreenpaladiumchestBlock::new);
		FLATTEN_ENDIUM_CHEST = register("flatten_endium_chest", EndiumchestBlock::new);
		DOWNLOADER = register("downloader", DownloaderBlock::new);
		ALARM_ON = register("alarm_on", AlarmonBlock::new);
		DEEPSLATE_AMETHYST_ORE = register("deepslate_amethyst_ore", AmethystoredeepslateBlock::new);
		DEEPSLATE_TITANE_ORE = register("deepslate_titane_ore", TitaneoredeepslateBlock::new);
		DEEPSLATE_PALADIUM_ORE = register("deepslate_paladium_ore", PaladiumoredeepslateBlock::new);
		DEEPSLATE_TRIXIUM_ORE = register("deepslate_trixium_ore", TrixiumoredeepslateBlock::new);
		DEEPSLATE_GREEN_PALADIUM_ORE = register("deepslate_green_paladium_ore", PaladiumgreenoredeepslateBlock::new);
		DEEPSLATE_ENDIUM_NUGGET_ORE = register("deepslate_endium_nugget_ore", EndiumnuggetoredeepslateBlock::new);
		DEEPSLATE_FINDIUM_ORE = register("deepslate_findium_ore", FindiumoredeepslateBlock::new);
		TRIXIUM_ORE = register("trixium_ore", TrixiumoreBlock::new);
		TRIXIUM_BLOCK = register("trixium_block", TrixiumblockBlock::new);
		CAVE_BLOCK = register("cave_block", CaveblockBlock::new);
		PALADIUM_CHEST = register("paladium_chest", Paladiumchestv2Block::new);
		GREEN_PALADIUM_CHEST = register("green_paladium_chest", Greenpaladiumchestv2Block::new);
		AMETHYST_CHEST = register("amethyst_chest", Amethystchestv2Block::new);
		ENDIUM_CHEST = register("endium_chest", Endiumchestv2Block::new);
		TITANE_CHEST = register("titane_chest", Titanechestv2Block::new);
		WOODEN_SPIKE = register("wooden_spike", WoddenspikeBlock::new);
		WOODEN_OBSIDIAN_SPIKE = register("wooden_obsidian_spike", SpikeobsidianwoodBlock::new);
		IRON_OBSIDIAN_SPIKE = register("iron_obsidian_spike", IronobsidianspikeBlock::new);
		GOLDEN_OBSIDIAN_SPIKE = register("golden_obsidian_spike", GoldenobsidianspikeBlock::new);
		DIAMOND_OBSIDIAN_SPIKE = register("diamond_obsidian_spike", DiamondobsidianspikeBlock::new);
<<<<<<< Updated upstream
		AMETHYS_TOBSIDIAN_SPIKE = register("amethys_tobsidian_spike", AmethystobsidianspikeBlock::new);
=======
		AMETHYST_OBSIDIAN_SPIKE = register("amethyst_obsidian_spike", AmethystobsidianspikeBlock::new);
>>>>>>> Stashed changes
		TITANE_OBSIDIAN_SPIKE = register("titane_obsidian_spike", TitaneobsidianspikeBlock::new);
		PALADIUM_OBSIDIAN_SPIKE = register("paladium_obsidian_spike", PaladiumobsidianspikeBlock::new);
		ONLINE_DETECTOR = register("online_detector", OnlinedetectorBlock::new);
		ONLINE_DETECTOR_ON = register("online_detector_on", OnlinedetectoronBlock::new);
		COBBLEBREAKER = register("cobblebreaker", CobblebreakerBlock::new);
		FERTILZED_DIRT = register("fertilzed_dirt", FertilseddirtBlock::new);
		PRINTINGPRESS = register("printingpress", PrintingpressBlock::new);
		TYPESETTINGTABLE = register("typesettingtable", TypesettingtableBlock::new);
		DRAWBRIDGE = register("drawbridge", DrawbridgeBlock::new);
		UNKNOWNBLOCK = register("unknownblock", UnknownblockBlock::new);
<<<<<<< Updated upstream
		COMPRESSEDSPONGE = register("compressedsponge", CompressedspongeBlock::new);
		SPONGETNT = register("spongetnt", SpongetntBlock::new);
		LAVASPONGE = register("lavasponge", LavaspongeBlock::new);
		WETLAVASPONGE = register("wetlavasponge", WetlavaspongeBlock::new);
		WITHERTNT = register("withertnt", WithertntBlock::new);
		MAGIC_TNT = register("magic_tnt", MagictntBlock::new);
		COMPACTTNT = register("compacttnt", CompacttntBlock::new);
		ENDIUMTNT = register("endiumtnt", EndiumtntBlock::new);
		RENFORCEDOBSIDIANSTAIRS = register("renforcedobsidianstairs", RenforcedobsidianstairsBlock::new);
		OBSIDIANSTAIRS = register("obsidianstairs", ObsidianstairsBlock::new);
		OBSIDIANSLAB = register("obsidianslab", ObsidianslabBlock::new);
=======
		COMPRESSED_SPONGE = register("compressed_sponge", CompressedspongeBlock::new);
		TNT_SPONGE = register("tnt_sponge", SpongetntBlock::new);
		LAVA_SPONGE = register("lava_sponge", LavaspongeBlock::new);
		WET_LAVA_SPONGE = register("wet_lava_sponge", WetlavaspongeBlock::new);
		TNT_WITHER = register("tnt_wither", WithertntBlock::new);
		TNT_MAGIC = register("tnt_magic", MagictntBlock::new);
		TNT_COMPACT = register("tnt_compact", CompacttntBlock::new);
		TNT_ENDIUM = register("tnt_endium", EndiumtntBlock::new);
		RENFORCED_OBSIDIAN_STAIRS = register("renforced_obsidian_stairs", RenforcedobsidianstairsBlock::new);
		OBSIDIAN_STAIRS = register("obsidian_stairs", ObsidianstairsBlock::new);
		OBSIDIAN_SLAB = register("obsidian_slab", ObsidianslabBlock::new);
>>>>>>> Stashed changes
		HARDENED_OBSIDIAN_SLAB = register("hardened_obsidian_slab", HardenedobsidianslabBlock::new);
		FAKE_WATER = register("fake_water", FakewterBlock::new);
		ANGELIC_WATER = register("angelic_water", AngelicwterBlock::new);
		SLIME_OBSIDIAN = register("slime_obsidian", SlimeobsidianBlock::new);
		POISON_OBSIDIAN = register("poison_obsidian", PoisonobsidianBlock::new);
		EXTRACTOR = register("extractor", ExctractorBlock::new);
		BOOM_OBSIDIAN = register("boom_obsidian", BoomobsidianBlock::new);
<<<<<<< Updated upstream
		MEGABOOMOBSIDIAN = register("megaboomobsidian", MegaboomobsidianBlock::new);
=======
		MEGA_BOOM_OBSIDIAN = register("mega_boom_obsidian", MegaboomobsidianBlock::new);
>>>>>>> Stashed changes
		HARPAGOPHYTUM = register("harpagophytum", HarpagophytumBlock::new);
		GLUEBALL_RED = register("glueball_red", RedglueballBlock::new);
		GREEN_GLUEBALL = register("green_glueball", GreenglueballBlock::new);
		GLUEBALL_LIGHT_GREEN = register("glueball_light_green", LightgreenglueballBlock::new);
		GLUEBALL_DARK_GREEN = register("glueball_dark_green", DarkgreenglueballBlock::new);
		GLUEBALL_BLUE = register("glueball_blue", BlueglueballBlock::new);
		GLUEBALL_PURPLE = register("glueball_purple", PurpleglueballBlock::new);
		GLUEBALL_YELLOW = register("glueball_yellow", YellowglueballBlock::new);
		GLUEBALL_CYAN = register("glueball_cyan", CyanglueballBlock::new);
		GLUEBALL_ORANGE = register("glueball_orange", OrangeglueballBlock::new);
		GLUEBALL_GRAY = register("glueball_gray", GrayglueballBlock::new);
		SLIMEPAD_RED = register("slimepad_red", RedslimepadBlock::new);
		SLIMEPAD_BLUE = register("slimepad_blue", BlueslimepadBlock::new);
		SLIMEPAD_ORANGE = register("slimepad_orange", OrangeslimepadBlock::new);
		SLIMEPAD_PURPLE = register("slimepad_purple", PurpleslimepadBlock::new);
<<<<<<< Updated upstream
		TOTEMFERTILITY = register("totemfertility", TotemfertilityBlock::new);
		XPBUSHLOW = register("xpbushlow", XpbushlowBlock::new);
=======
		TOTEM_FERTILITY = register("totem_fertility", TotemfertilityBlock::new);
		XP_BUSH_LOW = register("xp_bush_low", XpbushlowBlock::new);
>>>>>>> Stashed changes
		ROTATED_PALADIUM_HOPPER = register("rotated_paladium_hopper", PaladiumhopperBlock::new);
		PALADIUM_HOPPER = register("paladium_hopper", PaladiumhoppersouthBlock::new);
		TRIXIUMSLAB = register("trixiumslab", TrixiumslabBlock::new);
		TRIXIUMSTAIRS = register("trixiumstairs", TrixiumstairsBlock::new);
<<<<<<< Updated upstream
		COBBLEBREAKERSERVER = register("cobblebreakerserver", CobblebreakerserverBlock::new);
=======
		COBBLEBREAKER_SERVER = register("cobblebreaker_server", CobblebreakerserverBlock::new);
>>>>>>> Stashed changes
		ROTATED_SLIMEPAD = register("rotated_slimepad", RotatedslimepadBlock::new);
		ROTATED_RED_SLIMEPAD = register("rotated_red_slimepad", RotatedredslimepadBlock::new);
		ROTATED_PURPLE_SLIMEPAD = register("rotated_purple_slimepad", RotatedpurpleslimepadBlock::new);
		ROTATED_BLUE_SLIMEPAD = register("rotated_blue_slimepad", RotatedblueslimepadBlock::new);
		ROTATED_ORANGE_SLIMEPAD = register("rotated_orange_slimepad", RotatedorangeslimepadBlock::new);
<<<<<<< Updated upstream
		WITHEREDOBSIDIAN_0 = register("witheredobsidian_0", Witheredobsidian0Block::new);
		WITHEREDOBSIDIAN_1 = register("witheredobsidian_1", Witheredobsidian1Block::new);
		WITHEREDOBSIDIAN_2 = register("witheredobsidian_2", Witheredobsidian2Block::new);
		WITHEREDOBSIDIAN_3 = register("witheredobsidian_3", Witheredobsidian3Block::new);
		WITHEREDOBSIDIAN_4 = register("witheredobsidian_4", Witheredobsidian4Block::new);
		WITHEREDOBSIDIAN_5 = register("witheredobsidian_5", Witheredobsidian5Block::new);
		WITHEREDOBSIDIAN_6 = register("witheredobsidian_6", Witheredobsidian6Block::new);
		WITHEREDOBSIDIAN_7 = register("witheredobsidian_7", Witheredobsidian7Block::new);
		WITHEREDOBSIDIAN_8 = register("witheredobsidian_8", Witheredobsidian8Block::new);
		WITHEREDOBSIDIAN_9 = register("witheredobsidian_9", Witheredobsidian9Block::new);
		WITHEREDOBSIDIAN_10 = register("witheredobsidian_10", Witheredobsidian10Block::new);
		WITHEREDOBSIDIAN_11 = register("witheredobsidian_11", Witheredobsidian11Block::new);
		WITHEREDOBSIDIAN_12 = register("witheredobsidian_12", Witheredobsidian12Block::new);
		WITHEREDOBSIDIAN_13 = register("witheredobsidian_13", Witheredobsidian13Block::new);
=======
		WITHERED_OBSIDIAN_0 = register("withered_obsidian_0", Witheredobsidian0Block::new);
		WITHERED_OBSIDIAN_1 = register("withered_obsidian_1", Witheredobsidian1Block::new);
		WITHERED_OBSIDIAN_2 = register("withered_obsidian_2", Witheredobsidian2Block::new);
		WITHERED_OBSIDIAN_3 = register("withered_obsidian_3", Witheredobsidian3Block::new);
		WITHERED_OBSIDIAN_4 = register("withered_obsidian_4", Witheredobsidian4Block::new);
		WITHERED_OBSIDIAN_5 = register("withered_obsidian_5", Witheredobsidian5Block::new);
		WITHERED_OBSIDIAN_6 = register("withered_obsidian_6", Witheredobsidian6Block::new);
		WITHERED_OBSIDIAN_7 = register("withered_obsidian_7", Witheredobsidian7Block::new);
		WITHERED_OBSIDIAN_8 = register("withered_obsidian_8", Witheredobsidian8Block::new);
		WITHERED_OBSIDIAN_9 = register("withered_obsidian_9", Witheredobsidian9Block::new);
		WITHERED_OBSIDIAN_10 = register("withered_obsidian_10", Witheredobsidian10Block::new);
		WITHERED_OBSIDIAN_11 = register("withered_obsidian_11", Witheredobsidian11Block::new);
		WITHERED_OBSIDIAN_12 = register("withered_obsidian_12", Witheredobsidian12Block::new);
		WITHERED_OBSIDIAN_13 = register("withered_obsidian_13", Witheredobsidian13Block::new);
>>>>>>> Stashed changes
		MINERDIMENSION_PORTAL = register("minerdimension_portal", MinerdimensionPortalBlock::new);
		SOFT_STONE = register("soft_stone", SoftstoneBlock::new);
		SOFTENED_AMETHYST_ORE = register("softened_amethyst_ore", SoftenedamethystoreBlock::new);
		SOFTENED_TITANE_ORE = register("softened_titane_ore", SoftenedtitaneoreBlock::new);
		SOFTENED_PALADIUM_ORE = register("softened_paladium_ore", SoftenedpaladiumoreBlock::new);
		SOFTENED_TRIXIUM_ORE = register("softened_trixium_ore", SoftenedtrixiumoreBlock::new);
		SOFTENED_GREEN_PALADIUM_ORE = register("softened_green_paladium_ore", SoftenedgreenpaladiumoreBlock::new);
		SOFTENED_FINDIUM_ORE = register("softened_findium_ore", SoftenedfindiumoreBlock::new);
		SOFTENED_ENDIUM_NUGGET_ORE = register("softened_endium_nugget_ore", SoftenedendiumnuggetoreBlock::new);
		COBBLED_SOFT_STONE = register("cobbled_soft_stone", CobbleledsoftstoneBlock::new);
<<<<<<< Updated upstream
		SOFTSTONESLAB = register("softstoneslab", SoftstoneslabBlock::new);
		SOFTSTONESTAIRS = register("softstonestairs", SoftstonestairsBlock::new);
		COBBLEDSOFTSTONESLAB = register("cobbledsoftstoneslab", CobbledsoftstoneslabBlock::new);
		COBBLEDSOFTSTONESTAIRS = register("cobbledsoftstonestairs", CobbledsoftstonestairsBlock::new);
=======
		SOFT_STONE_SLAB = register("soft_stone_slab", SoftstoneslabBlock::new);
		SOFT_STONE_STAIRS = register("soft_stone_stairs", SoftstonestairsBlock::new);
		COBBLED_SOFT_STONE_SLAB = register("cobbled_soft_stone_slab", CobbledsoftstoneslabBlock::new);
		COBBLED_SOFT_STONE_STAIRS = register("cobbled_soft_stone_stairs", CobbledsoftstonestairsBlock::new);
>>>>>>> Stashed changes
		SOFTENED_COAL_ORE = register("softened_coal_ore", SoftcoaloreBlock::new);
		SOFTENED_IRON_ORE = register("softened_iron_ore", SoftenedironoreBlock::new);
		SOFTENED_GOLD_ORE = register("softened_gold_ore", SoftenedgoldoreBlock::new);
		SOFTENED_DIAMOND_ORE = register("softened_diamond_ore", SofteneddiamondoreBlock::new);
		SOFTENED_REDSTONE_ORE = register("softened_redstone_ore", SoftenedredstoneoreBlock::new);
		SOFTENED_LAPIS_LAZULIS_ORE = register("softened_lapis_lazulis_ore", SoftenedlapislazulisoreBlock::new);
<<<<<<< Updated upstream
		FLOWERTOTEM = register("flowertotem", FlowertotemBlock::new);
		MINERALFLOWER = register("mineralflower", MineralflowerBlock::new);
		ENDIUMFLOWER = register("endiumflower", EndiumflowerBlock::new);
		ENDIUMFLOWERON = register("endiumfloweron", EndiumfloweronBlock::new);
		CLATHRUSARCHERI = register("clathrusarcheri", ClathrusarcheriBlock::new);
		PALADIUMFLOWER = register("paladiumflower", PaladiumflowerBlock::new);
		DANKABLOCK = register("dankablock", DankablockBlock::new);
		BROKENSPAWNER = register("brokenspawner", BrokenspawnerBlock::new);
		SPAWNCONTROLLER = register("spawncontroller", SpawncontrollerBlock::new);
		EMPTYSPAWNER = register("emptyspawner", EmptyspawnerBlock::new);
		DIAMONDINFUSEDOBSIDIAN = register("diamondinfusedobsidian", DiamondinfusedobsidianBlock::new);
		AMETHYSTINFUSEDOBSIDIAN = register("amethystinfusedobsidian", AmethystinfusedobsidianBlock::new);
		TITANEINFUSEDOBSIDIAN = register("titaneinfusedobsidian", TitaneinfusedobsidianBlock::new);
		PALADIUMINFUSEDOBSIDIAN = register("paladiuminfusedobsidian", PaladiuminfusedobsidianBlock::new);
=======
		FLOWER_TOTEM = register("flower_totem", FlowertotemBlock::new);
		MINERAL_FLOWER = register("mineral_flower", MineralflowerBlock::new);
		ENDIUM_FLOWER = register("endium_flower", EndiumflowerBlock::new);
		ENDIUM_FLOWER_ON = register("endium_flower_on", EndiumfloweronBlock::new);
		CLATHRUSARCHERI = register("clathrusarcheri", ClathrusarcheriBlock::new);
		PALADIUM_FLOWER = register("paladium_flower", PaladiumflowerBlock::new);
		DANKABLOCK = register("dankablock", DankablockBlock::new);
		BROKEN_SPAWNER = register("broken_spawner", BrokenspawnerBlock::new);
		SPAWN_CONTROLLER = register("spawn_controller", SpawncontrollerBlock::new);
		EMPTY_SPAWNER = register("empty_spawner", EmptyspawnerBlock::new);
		DIAMOND_INFUSED_OBSIDIAN = register("diamond_infused_obsidian", DiamondinfusedobsidianBlock::new);
		AMETHYST_INFUSED_OBSIDIAN = register("amethyst_infused_obsidian", AmethystinfusedobsidianBlock::new);
		TITANE_INFUSED_OBSIDIAN = register("titane_infused_obsidian", TitaneinfusedobsidianBlock::new);
		PALADIUM_INFUSED_OBSIDIAN = register("paladium_infused_obsidian", PaladiuminfusedobsidianBlock::new);
		DEAD_LOG = register("dead_log", DeadLogBlock::new);
		DEAD_WOOD = register("dead_wood", DeadWoodBlock::new);
		STRIPPED_DEAD_LOG = register("stripped_dead_log", StrippedDeadLogBlock::new);
		STRIPPED_DEAD_WOOD = register("stripped_dead_wood", StrippedDeadWoodBlock::new);
		DEAD_PLANKS = register("dead_planks", DeadPlanksBlock::new);
		DEAD_STAIRS = register("dead_stairs", DeadStairsBlock::new);
		DEAD_SLAB = register("dead_slab", DeadSlabBlock::new);
		DEAD_FENCE = register("dead_fence", DeadFenceBlock::new);
		DEAD_FENCE_GATE = register("dead_fence_gate", DeadFenceGateBlock::new);
		DEAD_DOOR = register("dead_door", DeadDoorBlock::new);
		DEAD_TRAPDOOR = register("dead_trapdoor", DeadTrapdoorBlock::new);
		DEAD_PRESSURE_PLATE = register("dead_pressure_plate", DeadPressurePlateBlock::new);
		DEAD_BUTTON = register("dead_button", DeadButtonBlock::new);
		FROZEN_OBSIDIAN = register("frozen_obsidian", FrozenobsidianBlock::new);
		KNOCKBACK_OBSIDIAN = register("knockback_obsidian", KnockbackobsidianBlock::new);
		AMETHYST_ANVIL = register("amethyst_anvil", AmethystanvilBlock::new);
		TITANE_ANVIL = register("titane_anvil", TitaneanvilBlock::new);
		PALADIUM_ANVIL = register("paladium_anvil", PaladiumanvilBlock::new);
		MONEY_ANVIL = register("money_anvil", MoneyanvilBlock::new);
		AMETHYSTANVIL_2 = register("amethystanvil_2", Amethystanvil2Block::new);
>>>>>>> Stashed changes
	}

	// Start of user code block custom blocks
	// End of user code block custom blocks
	private static <B extends Block> DeferredBlock<B> register(String name, Function<BlockBehaviour.Properties, ? extends B> supplier) {
		return REGISTRY.registerBlock(name, supplier);
	}
}