/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package palamod.init;

import palamod.item.inventory.VoidstoneInventoryCapability;
import palamod.item.inventory.PaladiumphoneInventoryCapability;
import palamod.item.inventory.MinerjobsitemInventoryCapability;
import palamod.item.inventory.FarmerjobsitemInventoryCapability;
import palamod.item.*;

import palamod.block.*;

import palamod.PalamodMod;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.fluids.capability.wrappers.FluidBucketWrapper;
import net.neoforged.neoforge.client.event.RegisterRangeSelectItemModelPropertyEvent;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;

import java.util.function.Function;

@EventBusSubscriber
public class PalamodModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(PalamodMod.MODID);
	public static final DeferredItem<Item> PALADIUM_INGOT;
	public static final DeferredItem<Item> PALADIUM_ORE;
	public static final DeferredItem<Item> PALADIUM_BLOCK;
	public static final DeferredItem<Item> PALADIUM_PICKAXE;
	public static final DeferredItem<Item> PALADIUM_AXE;
	public static final DeferredItem<Item> PALADIUM_SWORD;
	public static final DeferredItem<Item> PALADIUM_SHOVEL;
	public static final DeferredItem<Item> PALADIUM_ARMOR_HELMET;
	public static final DeferredItem<Item> PALADIUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> PALADIUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> PALADIUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> TITANE_INGOT;
	public static final DeferredItem<Item> TITANE_ORE;
	public static final DeferredItem<Item> TITANE_BLOCK;
	public static final DeferredItem<Item> TITANE_PICKAXE;
	public static final DeferredItem<Item> TITANE_AXE;
	public static final DeferredItem<Item> TITANE_SWORD;
	public static final DeferredItem<Item> TITANE_SHOVEL;
	public static final DeferredItem<Item> TITANE_ARMOR_HELMET;
	public static final DeferredItem<Item> TITANE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> TITANE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> TITANE_ARMOR_BOOTS;
	public static final DeferredItem<Item> AMETHYST;
	public static final DeferredItem<Item> AMETHYST_ORE;
	public static final DeferredItem<Item> AMETHYST_BLOCK;
	public static final DeferredItem<Item> AMETHYST_PICKAXE;
	public static final DeferredItem<Item> AMETHYST_AXE;
	public static final DeferredItem<Item> AMETHYST_SWORD;
	public static final DeferredItem<Item> AMETHYST_SHOVEL;
	public static final DeferredItem<Item> AMETHYST_ARMOR_HELMET;
	public static final DeferredItem<Item> AMETHYST_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> AMETHYST_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> AMETHYST_ARMOR_BOOTS;
	public static final DeferredItem<Item> PALADIUM_CRUSHER;
	public static final DeferredItem<Item> PALADIUM_MIXED_CHARCOAL;
	public static final DeferredItem<Item> EGGPLANT;
	public static final DeferredItem<Item> ORANGEBLUE;
	public static final DeferredItem<Item> KIWANO;
	public static final DeferredItem<Item> CHERVIL;
	public static final DeferredItem<Item> ENDIUM_INGOT;
	public static final DeferredItem<Item> ENDIUM_BLOCK;
	public static final DeferredItem<Item> ENDIUM_PICKAXE;
	public static final DeferredItem<Item> ENDIUM_AXE;
	public static final DeferredItem<Item> ENDIUM_SWORD;
	public static final DeferredItem<Item> ENDIUM_ARMOR_HELMET;
	public static final DeferredItem<Item> ENDIUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ENDIUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ENDIUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> ENDIUM_NUGGET;
	public static final DeferredItem<Item> PALADIUM_STICK;
	public static final DeferredItem<Item> TITANE_STICK;
	public static final DeferredItem<Item> AMETHYST_STICK;
	public static final DeferredItem<Item> COMPRESSED_AMETHYST;
	public static final DeferredItem<Item> COMPRESSED_TITANE;
	public static final DeferredItem<Item> COMPRESSED_PALADIUM;
	public static final DeferredItem<Item> FINDIUM;
	public static final DeferredItem<Item> FINDIUM_ORE;
	public static final DeferredItem<Item> FINDIUM_BLOCK;
	public static final DeferredItem<Item> OSTRYA_WOOD_WOOD;
	public static final DeferredItem<Item> OSTRYA_WOOD_LOG;
	public static final DeferredItem<Item> OSTRYA_WOOD_PLANKS;
	public static final DeferredItem<Item> OSTRYA_WOOD_LEAVES;
	public static final DeferredItem<Item> OSTRYA_WOOD_STAIRS;
	public static final DeferredItem<Item> OSTRYA_WOOD_SLAB;
	public static final DeferredItem<Item> OSTRYA_WOOD_FENCE;
	public static final DeferredItem<Item> OSTRYA_WOOD_FENCE_GATE;
	public static final DeferredItem<Item> JACARANDA_WOOD;
	public static final DeferredItem<Item> JACARANDA_LOG;
	public static final DeferredItem<Item> JACARANDA_PLANKS;
	public static final DeferredItem<Item> JACARANDA_LEAVES;
	public static final DeferredItem<Item> JACARANDA_STAIRS;
	public static final DeferredItem<Item> JACARANDA_SLAB;
	public static final DeferredItem<Item> JACARANDA_FENCE;
	public static final DeferredItem<Item> JACARANDA_FENCE_GATE;
	public static final DeferredItem<Item> NBT_BLOCK;
	public static final DeferredItem<Item> JUDEECERCIS_WOOD;
	public static final DeferredItem<Item> JUDEECERCIS_LOG;
	public static final DeferredItem<Item> JUDEECERCIS_PLANKS;
	public static final DeferredItem<Item> JUDEECERCIS_LEAVES;
	public static final DeferredItem<Item> JUDEECERCIS_STAIRS;
	public static final DeferredItem<Item> JUDEECERCIS_SLAB;
	public static final DeferredItem<Item> JUDEECERCIS_FENCE;
	public static final DeferredItem<Item> JUDEECERCIS_FENCE_GATE;
	public static final DeferredItem<Item> ERABLE_WOOD;
	public static final DeferredItem<Item> ERABLE_LOG;
	public static final DeferredItem<Item> ERABLE_PLANKS;
	public static final DeferredItem<Item> ERABLE_LEAVES;
	public static final DeferredItem<Item> ERABLE_STAIRS;
	public static final DeferredItem<Item> ERABLE_SLAB;
	public static final DeferredItem<Item> ERABLE_FENCE;
	public static final DeferredItem<Item> ERABLE_FENCE_GATE;
	public static final DeferredItem<Item> ERABLE_SAPPLING;
	public static final DeferredItem<Item> JUDEECERCIS_SAPPLING;
	public static final DeferredItem<Item> OSTRYA_SAPPLING;
	public static final DeferredItem<Item> JACARANDA_SAPPLING;
	public static final DeferredItem<Item> KIWANOSEED;
	public static final DeferredItem<Item> ORANGEBLUESEED;
	public static final DeferredItem<Item> CHERVILSEED;
	public static final DeferredItem<Item> EGGPLANT_SEED;
	public static final DeferredItem<Item> FINDIUM_STAIRS;
	public static final DeferredItem<Item> FINDIUM_SLAB;
	public static final DeferredItem<Item> XPBUSH;
	public static final DeferredItem<Item> XPBUSHON;
	public static final DeferredItem<Item> XPBERRY;
	public static final DeferredItem<Item> COMPRESSEDXPBERRY;
	public static final DeferredItem<Item> PALADIUM_CORE;
	public static final DeferredItem<Item> SLIMEPAD;
	public static final DeferredItem<Item> HEAL_ORB;
	public static final DeferredItem<Item> SPEED_ORB;
	public static final DeferredItem<Item> STRENGH_ORB;
	public static final DeferredItem<Item> JUMP_ORB;
	public static final DeferredItem<Item> KNOCKBACK_ORB;
	public static final DeferredItem<Item> SPEED_MODIFIER;
	public static final DeferredItem<Item> KNOCKBACK_MODIFIER;
	public static final DeferredItem<Item> FLAME_MODIFIER;
	public static final DeferredItem<Item> FORTUNE_MODIFIER;
	public static final DeferredItem<Item> SPEEDSTICK;
	public static final DeferredItem<Item> JUMPSTICK;
	public static final DeferredItem<Item> HYPERJUMPSTICK;
	public static final DeferredItem<Item> HEALSTICK;
	public static final DeferredItem<Item> STRENGHTSTICK;
	public static final DeferredItem<Item> DAMAGESTICK;
	public static final DeferredItem<Item> STICKOFGODS;
	public static final DeferredItem<Item> PALADIUMGREENPICKAXE;
	public static final DeferredItem<Item> PALADIUMGREENAXE;
	public static final DeferredItem<Item> PALADIUMGREENSWORD;
	public static final DeferredItem<Item> PALADIUMGREENSHOVEL;
	public static final DeferredItem<Item> GREEN_PALADIUM_INGOT;
	public static final DeferredItem<Item> PALADIUM_GREEN_ORE;
	public static final DeferredItem<Item> PALADIUM_GREEN_BLOCK;
	public static final DeferredItem<Item> ALCHIMET_1;
	public static final DeferredItem<Item> GRINDER_CASING;
	public static final DeferredItem<Item> GRINDER_FRAME;
	public static final DeferredItem<Item> GRINDER_BLOCK;
	public static final DeferredItem<Item> PALADIUM_FURNACE;
	public static final DeferredItem<Item> PALADIUM_FURNACE_ON;
	public static final DeferredItem<Item> AXE_HEAD;
	public static final DeferredItem<Item> PICKAXE_HEAD;
	public static final DeferredItem<Item> HAMMER_HEAD;
	public static final DeferredItem<Item> FASTSWORD_HEAD;
	public static final DeferredItem<Item> BROADSWORD_HEAD;
	public static final DeferredItem<Item> SHOVEL_HEAD;
	public static final DeferredItem<Item> SWORD_HEAD;
	public static final DeferredItem<Item> AXE_PATERN;
	public static final DeferredItem<Item> PICKAXE_PATTERN;
	public static final DeferredItem<Item> BROADSWORD_PATTERN;
	public static final DeferredItem<Item> BLOCK_PATTERN;
	public static final DeferredItem<Item> FASTSWORD_PATTERN;
	public static final DeferredItem<Item> INGOT_PATTERN;
	public static final DeferredItem<Item> HAMMER_PATTERN;
	public static final DeferredItem<Item> SWORD_PATTERN;
	public static final DeferredItem<Item> SHOVEL_PATTERN;
	public static final DeferredItem<Item> PALADIUMBROADSWORD;
	public static final DeferredItem<Item> TITANEBROADSWORD;
	public static final DeferredItem<Item> AMETHYST_BROADSWORD;
	public static final DeferredItem<Item> AMETHYST_FASTSWORD;
	public static final DeferredItem<Item> AMETHYST_HAMMER;
	public static final DeferredItem<Item> TITANE_HAMMER;
	public static final DeferredItem<Item> PALADIUM_HAMMER;
	public static final DeferredItem<Item> OBSIDIAN_TRAPDOOR;
	public static final DeferredItem<Item> RENFORCED_OBSIDIAN;
	public static final DeferredItem<Item> OBSIDIAN_DOOR;
	public static final DeferredItem<Item> COMPACTED_OBSIDIAN;
	public static final DeferredItem<Item> FAKE_WATER_OBSIDIAN;
	public static final DeferredItem<Item> LAVA_OBSIDIAN;
	public static final DeferredItem<Item> IRON_SPIKE;
	public static final DeferredItem<Item> SPIKE_GOLD;
	public static final DeferredItem<Item> DIAMOND_SPIKE;
	public static final DeferredItem<Item> AMETHYST_SPIKE;
	public static final DeferredItem<Item> TITANE_SPIKE;
	public static final DeferredItem<Item> PALADIUM_SPIKE;
	public static final DeferredItem<Item> GOLD_MIXEDCOAL;
	public static final DeferredItem<Item> AMETHYST_MIXEDCOAL;
	public static final DeferredItem<Item> TITANE_MIXED_COAL;
	public static final DeferredItem<Item> PALADIUM_FORGE;
	public static final DeferredItem<Item> TITANEFASTSWORD;
	public static final DeferredItem<Item> TITANE_SLAB;
	public static final DeferredItem<Item> TITANE_STAIRS;
	public static final DeferredItem<Item> LOADBLOCK_1T;
	public static final DeferredItem<Item> SOCKET_PATTERN;
	public static final DeferredItem<Item> PALADIUMFASTSWORD;
	public static final DeferredItem<Item> SMELT_MODIFIER;
	public static final DeferredItem<Item> ENDIUM_HAMMER;
	public static final DeferredItem<Item> TCV_2;
	public static final DeferredItem<Item> LEGENDARY_STONE_FORTUNE;
	public static final DeferredItem<Item> LEGENDARY_STONE_INVISIBLE;
	public static final DeferredItem<Item> LEGENDARY_STONE_POWER;
	public static final DeferredItem<Item> LEGENDARY_STONE_JOBS;
	public static final DeferredItem<Item> LEGENDARY_STONE_TELEPORTATION;
	public static final DeferredItem<Item> LEGENDARY_STONE_RANDOM;
	public static final DeferredItem<Item> EGGPLANT_0;
	public static final DeferredItem<Item> EGGPLANT_1;
	public static final DeferredItem<Item> EGGPLANT_2;
	public static final DeferredItem<Item> EGGPLANT_3;
	public static final DeferredItem<Item> PALADIUM_MACHINE;
	public static final DeferredItem<Item> LUCKY_BLOCK;
	public static final DeferredItem<Item> CHERVIL_1;
	public static final DeferredItem<Item> CHERVIL_0;
	public static final DeferredItem<Item> CHERVIL_2;
	public static final DeferredItem<Item> CHERVIL_3;
	public static final DeferredItem<Item> KIWANO_4;
	public static final DeferredItem<Item> KIWANO_3;
	public static final DeferredItem<Item> KIWANO_2;
	public static final DeferredItem<Item> KIWANO_1;
	public static final DeferredItem<Item> KIWANO_0;
	public static final DeferredItem<Item> WITHER_SHARD;
	public static final DeferredItem<Item> GREENPALADIUMARMOR_HELMET;
	public static final DeferredItem<Item> GREENPALADIUMARMOR_CHESTPLATE;
	public static final DeferredItem<Item> GREENPALADIUMARMOR_LEGGINGS;
	public static final DeferredItem<Item> GREENPALADIUMARMOR_BOOTS;
	public static final DeferredItem<Item> LUCKY_BETA;
	public static final DeferredItem<Item> WEIGHTED_BOOTS;
	public static final DeferredItem<Item> TRESAURE_FALSE;
	public static final DeferredItem<Item> TRESAURE_TRUE;
	public static final DeferredItem<Item> ALARM;
	public static final DeferredItem<Item> MEGA_SAFE_CHEST;
	public static final DeferredItem<Item> COLORED_LAMP;
	public static final DeferredItem<Item> COLOFUL_LAMP;
	public static final DeferredItem<Item> DYNAMITE;
	public static final DeferredItem<Item> ENDIUM_DYNAMITE;
	public static final DeferredItem<Item> BIG_DYNAMITE;
	public static final DeferredItem<Item> DIAMOND_STRING;
	public static final DeferredItem<Item> PALADIUM_PHONE;
	public static final DeferredItem<Item> FAKE_PALADIUM_ORE;
	public static final DeferredItem<Item> MONEY_OTHER;
	public static final DeferredItem<Item> ORANGEBLUE_1;
	public static final DeferredItem<Item> ORANGEBLUE_0;
	public static final DeferredItem<Item> ORANGEBLUE_2;
	public static final DeferredItem<Item> ORANGEBLUE_3;
	public static final DeferredItem<Item> ORANGEBLUE_4;
	public static final DeferredItem<Item> TRIXIUM_NBT_BLOCK;
	public static final DeferredItem<Item> TRIXIUM;
	public static final DeferredItem<Item> PALADIUM_STAIRS;
	public static final DeferredItem<Item> PALADIUM_SLAB;
	public static final DeferredItem<Item> AMETHYST_STAIRS;
	public static final DeferredItem<Item> AMETHYST_SLAB;
	public static final DeferredItem<Item> FURNACE_UPGRADE;
	public static final DeferredItem<Item> WITHER_IMBUE_POTION;
	public static final DeferredItem<Item> FIRE_IMBUE_POTION;
	public static final DeferredItem<Item> POISON_IMBUE_POTION;
	public static final DeferredItem<Item> PALADIUM_APPLE;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_1;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_2;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_3;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_4;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_5;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_6;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_7;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_8;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_9;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_10;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_11;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_12;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_14;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_15;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_16;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_17;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_18;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_19;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_20;
	public static final DeferredItem<Item> PICKAXEOFTHEGODSLV_13;
	public static final DeferredItem<Item> AMETHYST_EXCAVATOR;
	public static final DeferredItem<Item> TITANEEXCAVATOR;
	public static final DeferredItem<Item> PALADIUMEXCAVATOR;
	public static final DeferredItem<Item> BIG_HOLE_UPGRADE;
	public static final DeferredItem<Item> VOIDSTONE;
	public static final DeferredItem<Item> AUTO_SMELT_UPGRADE_POTG;
	public static final DeferredItem<Item> INFERNALKNOCKER;
	public static final DeferredItem<Item> TRAVELARMOR_HELMET;
	public static final DeferredItem<Item> TRAVELARMOR_CHESTPLATE;
	public static final DeferredItem<Item> TRAVELARMOR_LEGGINGS;
	public static final DeferredItem<Item> TRAVELARMOR_BOOTS;
	public static final DeferredItem<Item> SCUBA_HELMET;
	public static final DeferredItem<Item> WING;
	public static final DeferredItem<Item> ELEVATOR_WHITE;
	public static final DeferredItem<Item> ELEVATO_RRED;
	public static final DeferredItem<Item> ELEVATOR_BLUE;
	public static final DeferredItem<Item> ELEVATOR_GREEN;
	public static final DeferredItem<Item> ELEVATOR_PINK;
	public static final DeferredItem<Item> ELEVATORL_IGHT_BLUE;
	public static final DeferredItem<Item> ELEVATOR_LIGHT_GREEN;
	public static final DeferredItem<Item> ELEVATOR_BROWN;
	public static final DeferredItem<Item> ELEVATOR_ORANGE;
	public static final DeferredItem<Item> MINAGE_VOIDSTONE;
	public static final DeferredItem<Item> CREATIVEPOTG;
	public static final DeferredItem<Item> ELEVATOR_PURPLE;
	public static final DeferredItem<Item> ELEVATOR_GRAY;
	public static final DeferredItem<Item> ELEVATOR_LIGHT_GRAY;
	public static final DeferredItem<Item> ELEVATOR_CYAN;
	public static final DeferredItem<Item> PALADIUMGOLEM_SPAWN_EGG;
	public static final DeferredItem<Item> GUARDIAN_STONE;
	public static final DeferredItem<Item> GUARDIAN_BLOCK;
	public static final DeferredItem<Item> GREEN_PALADIUM_BROADSWORD_HEAD;
	public static final DeferredItem<Item> GREEN_PALADIUM_SWORD_HEAD;
	public static final DeferredItem<Item> GREEN_PALADIUM_PICKAXE_HEAD;
	public static final DeferredItem<Item> GREEN_PALADIUM_AXE_HEAD;
	public static final DeferredItem<Item> GREEN_PALADIUM_SHOVEL_HEAD;
	public static final DeferredItem<Item> HEADENDIUMSWORD;
	public static final DeferredItem<Item> HEAD_ENDIUM_PICKAXE;
	public static final DeferredItem<Item> HEAD_ENDIUM_AXE;
	public static final DeferredItem<Item> GREENPALADIUMBROADSWORD;
	public static final DeferredItem<Item> ONE_MORE_MODIFIER;
	public static final DeferredItem<Item> ENDIUM_BROADSWORD_HEAD;
	public static final DeferredItem<Item> ENDIUMBROADSWORD;
	public static final DeferredItem<Item> GREEN_PALADIUM_HAMMER;
	public static final DeferredItem<Item> GREEN_PALADIUM_HAMMER_HEAD;
	public static final DeferredItem<Item> ENDIUM_HAMMER_HEAD;
	public static final DeferredItem<Item> MAGICAL_TOOL;
	public static final DeferredItem<Item> STONY;
	public static final DeferredItem<Item> CLOUD_BLOCK;
	public static final DeferredItem<Item> CROWN;
	public static final DeferredItem<Item> FACTION_BLOCK;
	public static final DeferredItem<Item> BLACK_LUCKY_BLOCK;
	public static final DeferredItem<Item> ENFYUPOTION;
	public static final DeferredItem<Item> INVISIBLEARMOR_HELMET;
	public static final DeferredItem<Item> INVISIBLEARMOR_CHESTPLATE;
	public static final DeferredItem<Item> INVISIBLEARMOR_LEGGINGS;
	public static final DeferredItem<Item> INVISIBLEARMOR_BOOTS;
	public static final DeferredItem<Item> RAINBOWARMOR_HELMET;
	public static final DeferredItem<Item> RAINBOWARMOR_CHESTPLATE;
	public static final DeferredItem<Item> RAINBOWARMOR_LEGGINGS;
	public static final DeferredItem<Item> RAINBOWARMOR_BOOTS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_1_HELMET;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_1_CHESTPLATE;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_1_LEGGINGS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_1_BOOTS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_2_HELMET;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_2_CHESTPLATE;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_2_LEGGINGS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_2_BOOTS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_3_HELMET;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_3_CHESTPLATE;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_3_LEGGINGS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_3_BOOTS;
	public static final DeferredItem<Item> FLYPOTION;
	public static final DeferredItem<Item> SPACE_FOOD;
	public static final DeferredItem<Item> JUDEECERCIS_DOOR;
	public static final DeferredItem<Item> CHUNKANASLYSER;
	public static final DeferredItem<Item> ENDIUM_LUCKY_BLOCK;
	public static final DeferredItem<Item> ENDIUM_NUGGET_ORE;
	public static final DeferredItem<Item> ENDIUM_SLAB;
	public static final DeferredItem<Item> ENDIUM_STAIRS;
	public static final DeferredItem<Item> GREEN_PALADIUM_STAIRS;
	public static final DeferredItem<Item> GREEN_PALADIUM_SLAB;
	public static final DeferredItem<Item> UPLOADER;
	public static final DeferredItem<Item> INTERNET_CARD;
	public static final DeferredItem<Item> SMALL_RING;
	public static final DeferredItem<Item> MEDIUM_RING;
	public static final DeferredItem<Item> BIG_RING;
	public static final DeferredItem<Item> ENDIUM_SMALL_RING;
	public static final DeferredItem<Item> ENDIUM_MEDIUM_RING;
	public static final DeferredItem<Item> ENDIUM_BIG_RING;
	public static final DeferredItem<Item> OSTRYA_DOOR;
	public static final DeferredItem<Item> ERABLE_DOOR;
	public static final DeferredItem<Item> JACARANDA_DOOR;
	public static final DeferredItem<Item> HDV_BLOCK;
	public static final DeferredItem<Item> ERABLETRAPDOOR;
	public static final DeferredItem<Item> MONEY_ITEM;
	public static final DeferredItem<Item> PALADIUM_PARTICLE;
	public static final DeferredItem<Item> FLATTEN_TITANE_CHEST;
	public static final DeferredItem<Item> GREEN_PALADIUM_SMALL_RING;
	public static final DeferredItem<Item> GREEN_PALADIUM_MEDIUM_RING;
	public static final DeferredItem<Item> GREEN_PALADIUM_BIG_RING;
	public static final DeferredItem<Item> HANG_GLIDER;
	public static final DeferredItem<Item> FLATTEN_PALADIUM_CHEST;
	public static final DeferredItem<Item> FLATTEN_AMETHYST_CHEST;
	public static final DeferredItem<Item> PESYBLPOTION;
	public static final DeferredItem<Item> GREEN_PALADIUM_PARTICLE;
	public static final DeferredItem<Item> COMPRESSED_GREEN_PALADUM;
	public static final DeferredItem<Item> GREENPALADUMEXCATOR;
	public static final DeferredItem<Item> CREATIVE_HAMMER;
	public static final DeferredItem<Item> FLATTEN_GREEN_PALADIUM_CHEST;
	public static final DeferredItem<Item> FLATTEN_ENDIUM_CHEST;
	public static final DeferredItem<Item> MONEY_1K;
	public static final DeferredItem<Item> DOWNLOADER;
	public static final DeferredItem<Item> ALARM_ON;
	public static final DeferredItem<Item> CREATIVE_TRIXIUM_SWORD;
	public static final DeferredItem<Item> DEEPSLATE_AMETHYST_ORE;
	public static final DeferredItem<Item> DEEPSLATE_TITANE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_PALADIUM_ORE;
	public static final DeferredItem<Item> DEEPSLATE_TRIXIUM_ORE;
	public static final DeferredItem<Item> DEEPSLATE_GREEN_PALADIUM_ORE;
	public static final DeferredItem<Item> DEEPSLATE_ENDIUM_NUGGET_ORE;
	public static final DeferredItem<Item> DEEPSLATE_FINDIUM_ORE;
	public static final DeferredItem<Item> TRIXIUM_ORE;
	public static final DeferredItem<Item> TRIXIUM_BLOCK;
	public static final DeferredItem<Item> ENDIUM_POLLEN;
	public static final DeferredItem<Item> POTATO_BACKPACK;
	public static final DeferredItem<Item> PALADIUM_POLLEN;
	public static final DeferredItem<Item> TITANE_POLLEN;
	public static final DeferredItem<Item> AMETHYST_POLLEN;
	public static final DeferredItem<Item> AMETHYST_PARTICLE;
	public static final DeferredItem<Item> TITANE_PARTICLE;
	public static final DeferredItem<Item> DIAMOND_PARTICLE;
	public static final DeferredItem<Item> GOLD_PARTICLE;
	public static final DeferredItem<Item> IRON_PARTICLE;
	public static final DeferredItem<Item> GREENPALADIUMFASTSWORD;
	public static final DeferredItem<Item> GREEN_PALADIUM_FASTSWORD_HEAD;
	public static final DeferredItem<Item> ENDIUMFASTSWORD;
	public static final DeferredItem<Item> ENDIUM_FASTSWORD_HEAD;
	public static final DeferredItem<Item> ENDIUM_SHOVEL_HEAD;
	public static final DeferredItem<Item> ENDIUMSHOVEL;
	public static final DeferredItem<Item> CAVE_BLOCK;
	public static final DeferredItem<Item> ENDIUM_FRAGMENT;
	public static final DeferredItem<Item> FLAT_CHEST_UPGRADE;
	public static final DeferredItem<Item> PALADIUM_CHEST;
	public static final DeferredItem<Item> GREEN_PALADIUM_CHEST;
	public static final DeferredItem<Item> AMETHYST_CHEST;
	public static final DeferredItem<Item> ENDIUM_CHEST;
	public static final DeferredItem<Item> TITANE_CHEST;
	public static final DeferredItem<Item> WOODEN_SPIKE;
	public static final DeferredItem<Item> WOODEN_OBSIDIAN_SPIKE;
	public static final DeferredItem<Item> IRON_OBSIDIAN_SPIKE;
	public static final DeferredItem<Item> GOLDEN_OBSIDIAN_SPIKE;
	public static final DeferredItem<Item> DIAMOND_OBSIDIAN_SPIKE;
	public static final DeferredItem<Item> AMETHYS_TOBSIDIAN_SPIKE;
	public static final DeferredItem<Item> TITANE_OBSIDIAN_SPIKE;
	public static final DeferredItem<Item> PALADIUM_OBSIDIAN_SPIKE;
	public static final DeferredItem<Item> ONLINE_DETECTOR;
	public static final DeferredItem<Item> ONLINE_DETECTOR_ON;
	public static final DeferredItem<Item> COBBLEBREAKER;
	public static final DeferredItem<Item> OBSIDIANPICKAXE;
	public static final DeferredItem<Item> DOLLARS_STONE;
	public static final DeferredItem<Item> COBBLEBREAKER_AMETHYST_UPGRADE;
	public static final DeferredItem<Item> COBBLEBREAKER_TITANE_UPGRADE;
	public static final DeferredItem<Item> COBBLEBREAKER_PALADIUM_UPGRADE;
	public static final DeferredItem<Item> FERTILZED_DIRT;
	public static final DeferredItem<Item> AMETHYST_HOE;
	public static final DeferredItem<Item> TITANEHOE;
	public static final DeferredItem<Item> PALADIUM_HOE;
	public static final DeferredItem<Item> GREEN_PALADIUM_HOE;
	public static final DeferredItem<Item> ENDIUM_HOE;
	public static final DeferredItem<Item> AMETHYST_SEEDPLANTER;
	public static final DeferredItem<Item> TITANE_SEEDPLANTER;
	public static final DeferredItem<Item> PALADIUM_SEEDPLANTER;
	public static final DeferredItem<Item> GREEN_PALADIUM_SEEDPLANTER;
	public static final DeferredItem<Item> ENDIUM_SEEDPLANTER;
	public static final DeferredItem<Item> PRINTINGPRESS;
	public static final DeferredItem<Item> PLATE;
	public static final DeferredItem<Item> TYPESETTINGTABLE;
	public static final DeferredItem<Item> DRAWBRIDGE;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_4_HELMET;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_4_CHESTPLATE;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_4_LEGGINGS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_4_BOOTS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_5_HELMET;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_5_CHESTPLATE;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_5_LEGGINGS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_5_BOOTS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_6_HELMET;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_6_CHESTPLATE;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_6_LEGGINGS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_6_BOOTS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_7_HELMET;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_7_CHESTPLATE;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_7_LEGGINGS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_7_BOOTS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_8_HELMET;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_8_CHESTPLATE;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_8_LEGGINGS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_8_BOOTS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_9_HELMET;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_9_CHESTPLATE;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_9_LEGGINGS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_9_BOOTS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_10_HELMET;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_10_CHESTPLATE;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_10_LEGGINGS;
	public static final DeferredItem<Item> PALADIUMARMORCUSTOM_10_BOOTS;
	public static final DeferredItem<Item> UNKNOWNBLOCK;
	public static final DeferredItem<Item> COMPRESSEDSPONGE;
	public static final DeferredItem<Item> SPONGETNT;
	public static final DeferredItem<Item> LAVASPONGE;
	public static final DeferredItem<Item> WETLAVASPONGE;
	public static final DeferredItem<Item> WITHERTNT;
	public static final DeferredItem<Item> MAGIC_TNT;
	public static final DeferredItem<Item> COMPACTTNT;
	public static final DeferredItem<Item> ENDIUMTNT;
	public static final DeferredItem<Item> RENFORCEDOBSIDIANSTAIRS;
	public static final DeferredItem<Item> OBSIDIANSTAIRS;
	public static final DeferredItem<Item> OBSIDIANSLAB;
	public static final DeferredItem<Item> HARDENED_OBSIDIAN_SLAB;
	public static final DeferredItem<Item> FAKE_WATER_BUCKET;
	public static final DeferredItem<Item> ANGELIC_WATER_BUCKET;
	public static final DeferredItem<Item> SLIME_OBSIDIAN;
	public static final DeferredItem<Item> POISON_OBSIDIAN;
	public static final DeferredItem<Item> SEALEDXPBOTTLE;
	public static final DeferredItem<Item> MIXED_ENDIUM_INGOT;
	public static final DeferredItem<Item> MIXED_ENDIUM_ARMOR_HELMET;
	public static final DeferredItem<Item> MIXED_ENDIUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> MIXED_ENDIUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> MIXED_ENDIUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> DOUBLEEXPPOTION;
	public static final DeferredItem<Item> X_10XPPOTION;
	public static final DeferredItem<Item> XPBOTTLE;
	public static final DeferredItem<Item> EXTRACTOR;
	public static final DeferredItem<Item> BOOM_OBSIDIAN;
	public static final DeferredItem<Item> MEGABOOMOBSIDIAN;
	public static final DeferredItem<Item> HARPAGOPHYTUM;
	public static final DeferredItem<Item> GLUEBALL_RED;
	public static final DeferredItem<Item> GREEN_GLUEBALL;
	public static final DeferredItem<Item> GLUEBALL_LIGHT_GREEN;
	public static final DeferredItem<Item> GLUEBALL_DARK_GREEN;
	public static final DeferredItem<Item> GLUEBALL_BLUE;
	public static final DeferredItem<Item> GLUEBALL_PURPLE;
	public static final DeferredItem<Item> GLUEBALL_YELLOW;
	public static final DeferredItem<Item> GLUEBALL_CYAN;
	public static final DeferredItem<Item> GLUEBALL_ORANGE;
	public static final DeferredItem<Item> GLUEBALL_GRAY;
	public static final DeferredItem<Item> GLUEBALLPATTERN;
	public static final DeferredItem<Item> DISC_MII_CHALENGE;
	public static final DeferredItem<Item> DISC_FUZEIII;
	public static final DeferredItem<Item> DISC_ANTI_FUZE;
	public static final DeferredItem<Item> DISC_ROULETTE_PALADIENNE;
	public static final DeferredItem<Item> DISC_CLASH_KUMIZ;
	public static final DeferredItem<Item> SLIMEPAD_RED;
	public static final DeferredItem<Item> SLIMEPAD_BLUE;
	public static final DeferredItem<Item> SLIMEPAD_ORANGE;
	public static final DeferredItem<Item> SLIMEPAD_PURPLE;
	public static final DeferredItem<Item> SWITCHARROWITEM;
	public static final DeferredItem<Item> AMETHYST_BACKPACK;
	public static final DeferredItem<Item> TITANE_BACKPACK;
	public static final DeferredItem<Item> PALADUM_BACKPACK;
	public static final DeferredItem<Item> ENDIUM_BACKPACK;
	public static final DeferredItem<Item> TOTEMFERTILITY;
	public static final DeferredItem<Item> GODVILLAGER_SPAWN_EGG;
	public static final DeferredItem<Item> XPBUSHLOW;
	public static final DeferredItem<Item> CHESTEXPLORER;
	public static final DeferredItem<Item> PALADIUMRAWORE;
	public static final DeferredItem<Item> TITANERAWORE;
	public static final DeferredItem<Item> AMETHYSTRAWORE;
	public static final DeferredItem<Item> GREENPALADIUMRAWORE;
	public static final DeferredItem<Item> ROTATED_PALADIUM_HOPPER;
	public static final DeferredItem<Item> PALADIUM_HOPPER;
	public static final DeferredItem<Item> TRIXIUMSLAB;
	public static final DeferredItem<Item> TRIXIUMSTAIRS;
	public static final DeferredItem<Item> COBBLEBREAKERSERVER;
	public static final DeferredItem<Item> ROTATED_SLIMEPAD;
	public static final DeferredItem<Item> ROTATED_RED_SLIMEPAD;
	public static final DeferredItem<Item> ROTATED_PURPLE_SLIMEPAD;
	public static final DeferredItem<Item> ROTATED_BLUE_SLIMEPAD;
	public static final DeferredItem<Item> ROTATED_ORANGE_SLIMEPAD;
	public static final DeferredItem<Item> WITHEREDOBSIDIAN_0;
	public static final DeferredItem<Item> WITHEREDOBSIDIAN_1;
	public static final DeferredItem<Item> WITHEREDOBSIDIAN_2;
	public static final DeferredItem<Item> WITHEREDOBSIDIAN_3;
	public static final DeferredItem<Item> WITHEREDOBSIDIAN_4;
	public static final DeferredItem<Item> WITHEREDOBSIDIAN_5;
	public static final DeferredItem<Item> WITHEREDOBSIDIAN_6;
	public static final DeferredItem<Item> WITHEREDOBSIDIAN_7;
	public static final DeferredItem<Item> WITHEREDOBSIDIAN_8;
	public static final DeferredItem<Item> WITHEREDOBSIDIAN_9;
	public static final DeferredItem<Item> WITHEREDOBSIDIAN_10;
	public static final DeferredItem<Item> WITHEREDOBSIDIAN_11;
	public static final DeferredItem<Item> WITHEREDOBSIDIAN_12;
	public static final DeferredItem<Item> WITHEREDOBSIDIAN_13;
	public static final DeferredItem<Item> MINE_CLEARER;
	public static final DeferredItem<Item> SOFT_STONE;
	public static final DeferredItem<Item> SOFTENED_AMETHYST_ORE;
	public static final DeferredItem<Item> SOFTENED_TITANE_ORE;
	public static final DeferredItem<Item> SOFTENED_PALADIUM_ORE;
	public static final DeferredItem<Item> SOFTENED_TRIXIUM_ORE;
	public static final DeferredItem<Item> SOFTENED_GREEN_PALADIUM_ORE;
	public static final DeferredItem<Item> SOFTENED_FINDIUM_ORE;
	public static final DeferredItem<Item> SOFTENED_ENDIUM_NUGGET_ORE;
	public static final DeferredItem<Item> MINERJOBSITEM;
	public static final DeferredItem<Item> FARMERJOBSITEM;
	public static final DeferredItem<Item> HUNTERJOBSITEM;
	public static final DeferredItem<Item> ALCHIMISTJOBSITEM;
	public static final DeferredItem<Item> CUSTOMAIR;
	public static final DeferredItem<Item> COBBLED_SOFT_STONE;
	public static final DeferredItem<Item> SOFTSTONESLAB;
	public static final DeferredItem<Item> SOFTSTONESTAIRS;
	public static final DeferredItem<Item> COBBLEDSOFTSTONESLAB;
	public static final DeferredItem<Item> COBBLEDSOFTSTONESTAIRS;
	public static final DeferredItem<Item> SOFTENED_COAL_ORE;
	public static final DeferredItem<Item> SOFTENED_IRON_ORE;
	public static final DeferredItem<Item> SOFTENED_GOLD_ORE;
	public static final DeferredItem<Item> SOFTENED_DIAMOND_ORE;
	public static final DeferredItem<Item> SOFTENED_REDSTONE_ORE;
	public static final DeferredItem<Item> SOFTENED_LAPIS_LAZULIS_ORE;
	public static final DeferredItem<Item> PIGARMOR_HELMET;
	public static final DeferredItem<Item> PIGARMOR_CHESTPLATE;
	public static final DeferredItem<Item> PIGARMOR_LEGGINGS;
	public static final DeferredItem<Item> PIGARMOR_BOOTS;
	public static final DeferredItem<Item> COMPRESSEDENDIUM;
	public static final DeferredItem<Item> EXTRACTOR_ITEM;
	public static final DeferredItem<Item> FLOWERTOTEM;
	public static final DeferredItem<Item> MINERALFLOWER;
	public static final DeferredItem<Item> ENDIUMFLOWER;
	public static final DeferredItem<Item> ENDIUMFLOWERON;
	public static final DeferredItem<Item> CLATHRUSARCHERI;
	public static final DeferredItem<Item> PALADIUMFLOWER;
	public static final DeferredItem<Item> DANKAROCTEST_1_SPAWN_EGG;
	public static final DeferredItem<Item> DANKABLOCK;
	public static final DeferredItem<Item> PALADIUMINK;
	public static final DeferredItem<Item> UNCLAIMFINDER;
	public static final DeferredItem<Item> UNCLAIMFINDERORANGE;
	public static final DeferredItem<Item> UNCLAIMFINDERRED;
	public static final DeferredItem<Item> UNCLAIMFINDERBLUE;
	public static final DeferredItem<Item> POCKETENDERCHEST;
	public static final DeferredItem<Item> CAVERNEHAMMER;
	public static final DeferredItem<Item> BROKENSPAWNER;
	public static final DeferredItem<Item> SPAWNCONTROLLER;
	public static final DeferredItem<Item> EMPTYSPAWNER;
	public static final DeferredItem<Item> DIAMONDINFUSEDOBSIDIAN;
	public static final DeferredItem<Item> AMETHYSTINFUSEDOBSIDIAN;
	public static final DeferredItem<Item> TITANEINFUSEDOBSIDIAN;
	public static final DeferredItem<Item> PALADIUMINFUSEDOBSIDIAN;
	public static final DeferredItem<Item> EMPTYSPAWNERITEM;
	static {
		PALADIUM_INGOT = register("paladium_ingot", PaladiumIngotItem::new);
		PALADIUM_ORE = block(PalamodModBlocks.PALADIUM_ORE);
		PALADIUM_BLOCK = block(PalamodModBlocks.PALADIUM_BLOCK);
		PALADIUM_PICKAXE = register("paladium_pickaxe", PaladiumPickaxeItem::new);
		PALADIUM_AXE = register("paladium_axe", PaladiumAxeItem::new);
		PALADIUM_SWORD = register("paladium_sword", PaladiumSwordItem::new);
		PALADIUM_SHOVEL = register("paladium_shovel", PaladiumShovelItem::new);
		PALADIUM_ARMOR_HELMET = register("paladium_armor_helmet", PaladiumArmorItem.Helmet::new);
		PALADIUM_ARMOR_CHESTPLATE = register("paladium_armor_chestplate", PaladiumArmorItem.Chestplate::new);
		PALADIUM_ARMOR_LEGGINGS = register("paladium_armor_leggings", PaladiumArmorItem.Leggings::new);
		PALADIUM_ARMOR_BOOTS = register("paladium_armor_boots", PaladiumArmorItem.Boots::new);
		TITANE_INGOT = register("titane_ingot", TitaneIngotItem::new);
		TITANE_ORE = block(PalamodModBlocks.TITANE_ORE);
		TITANE_BLOCK = block(PalamodModBlocks.TITANE_BLOCK);
		TITANE_PICKAXE = register("titane_pickaxe", TitanePickaxeItem::new);
		TITANE_AXE = register("titane_axe", TitaneAxeItem::new);
		TITANE_SWORD = register("titane_sword", TitaneSwordItem::new);
		TITANE_SHOVEL = register("titane_shovel", TitaneShovelItem::new);
		TITANE_ARMOR_HELMET = register("titane_armor_helmet", TitaneArmorItem.Helmet::new);
		TITANE_ARMOR_CHESTPLATE = register("titane_armor_chestplate", TitaneArmorItem.Chestplate::new);
		TITANE_ARMOR_LEGGINGS = register("titane_armor_leggings", TitaneArmorItem.Leggings::new);
		TITANE_ARMOR_BOOTS = register("titane_armor_boots", TitaneArmorItem.Boots::new);
		AMETHYST = register("amethyst", AmethysteItem::new);
		AMETHYST_ORE = block(PalamodModBlocks.AMETHYST_ORE);
		AMETHYST_BLOCK = block(PalamodModBlocks.AMETHYST_BLOCK);
		AMETHYST_PICKAXE = register("amethyst_pickaxe", AmethystePickaxeItem::new);
		AMETHYST_AXE = register("amethyst_axe", AmethysteAxeItem::new);
		AMETHYST_SWORD = register("amethyst_sword", AmethysteSwordItem::new);
		AMETHYST_SHOVEL = register("amethyst_shovel", AmethysteShovelItem::new);
		AMETHYST_ARMOR_HELMET = register("amethyst_armor_helmet", AmethysteArmorItem.Helmet::new);
		AMETHYST_ARMOR_CHESTPLATE = register("amethyst_armor_chestplate", AmethysteArmorItem.Chestplate::new);
		AMETHYST_ARMOR_LEGGINGS = register("amethyst_armor_leggings", AmethysteArmorItem.Leggings::new);
		AMETHYST_ARMOR_BOOTS = register("amethyst_armor_boots", AmethysteArmorItem.Boots::new);
		PALADIUM_CRUSHER = block(PalamodModBlocks.PALADIUM_CRUSHER);
		PALADIUM_MIXED_CHARCOAL = register("paladium_mixed_charcoal", PalamixedcharoalItem::new);
		EGGPLANT = register("eggplant", EggplantItem::new);
		ORANGEBLUE = register("orangeblue", OrangeblueItem::new);
		KIWANO = register("kiwano", KiwanoItem::new);
		CHERVIL = register("chervil", ChervilItem::new);
		ENDIUM_INGOT = register("endium_ingot", EndiumIngotItem::new);
		ENDIUM_BLOCK = register("endium_block", EndiumBlockBlock.Item::new);
		ENDIUM_PICKAXE = register("endium_pickaxe", EndiumPickaxeItem::new);
		ENDIUM_AXE = register("endium_axe", EndiumAxeItem::new);
		ENDIUM_SWORD = register("endium_sword", EndiumSwordItem::new);
		ENDIUM_ARMOR_HELMET = register("endium_armor_helmet", EndiumArmorItem.Helmet::new);
		ENDIUM_ARMOR_CHESTPLATE = register("endium_armor_chestplate", EndiumArmorItem.Chestplate::new);
		ENDIUM_ARMOR_LEGGINGS = register("endium_armor_leggings", EndiumArmorItem.Leggings::new);
		ENDIUM_ARMOR_BOOTS = register("endium_armor_boots", EndiumArmorItem.Boots::new);
		ENDIUM_NUGGET = register("endium_nugget", EndiumnuggetItem::new);
		PALADIUM_STICK = register("paladium_stick", PaladiumstickItem::new);
		TITANE_STICK = register("titane_stick", TitanestickItem::new);
		AMETHYST_STICK = register("amethyst_stick", AmethytestickItem::new);
		COMPRESSED_AMETHYST = register("compressed_amethyst", CompressedamethysteItem::new);
		COMPRESSED_TITANE = register("compressed_titane", CompressedtitaneItem::new);
		COMPRESSED_PALADIUM = register("compressed_paladium", CompressedpaladiumItem::new);
		FINDIUM = register("findium", FindiumItem::new);
		FINDIUM_ORE = block(PalamodModBlocks.FINDIUM_ORE);
		FINDIUM_BLOCK = block(PalamodModBlocks.FINDIUM_BLOCK);
		OSTRYA_WOOD_WOOD = block(PalamodModBlocks.OSTRYA_WOOD_WOOD);
		OSTRYA_WOOD_LOG = block(PalamodModBlocks.OSTRYA_WOOD_LOG);
		OSTRYA_WOOD_PLANKS = block(PalamodModBlocks.OSTRYA_WOOD_PLANKS);
		OSTRYA_WOOD_LEAVES = block(PalamodModBlocks.OSTRYA_WOOD_LEAVES);
		OSTRYA_WOOD_STAIRS = block(PalamodModBlocks.OSTRYA_WOOD_STAIRS);
		OSTRYA_WOOD_SLAB = block(PalamodModBlocks.OSTRYA_WOOD_SLAB);
		OSTRYA_WOOD_FENCE = block(PalamodModBlocks.OSTRYA_WOOD_FENCE);
		OSTRYA_WOOD_FENCE_GATE = block(PalamodModBlocks.OSTRYA_WOOD_FENCE_GATE);
		JACARANDA_WOOD = block(PalamodModBlocks.JACARANDA_WOOD);
		JACARANDA_LOG = block(PalamodModBlocks.JACARANDA_LOG);
		JACARANDA_PLANKS = block(PalamodModBlocks.JACARANDA_PLANKS);
		JACARANDA_LEAVES = block(PalamodModBlocks.JACARANDA_LEAVES);
		JACARANDA_STAIRS = block(PalamodModBlocks.JACARANDA_STAIRS);
		JACARANDA_SLAB = block(PalamodModBlocks.JACARANDA_SLAB);
		JACARANDA_FENCE = block(PalamodModBlocks.JACARANDA_FENCE);
		JACARANDA_FENCE_GATE = block(PalamodModBlocks.JACARANDA_FENCE_GATE);
		NBT_BLOCK = block(PalamodModBlocks.NBT_BLOCK);
		JUDEECERCIS_WOOD = block(PalamodModBlocks.JUDEECERCIS_WOOD);
		JUDEECERCIS_LOG = block(PalamodModBlocks.JUDEECERCIS_LOG);
		JUDEECERCIS_PLANKS = block(PalamodModBlocks.JUDEECERCIS_PLANKS);
		JUDEECERCIS_LEAVES = block(PalamodModBlocks.JUDEECERCIS_LEAVES);
		JUDEECERCIS_STAIRS = block(PalamodModBlocks.JUDEECERCIS_STAIRS);
		JUDEECERCIS_SLAB = block(PalamodModBlocks.JUDEECERCIS_SLAB);
		JUDEECERCIS_FENCE = block(PalamodModBlocks.JUDEECERCIS_FENCE);
		JUDEECERCIS_FENCE_GATE = block(PalamodModBlocks.JUDEECERCIS_FENCE_GATE);
		ERABLE_WOOD = block(PalamodModBlocks.ERABLE_WOOD);
		ERABLE_LOG = block(PalamodModBlocks.ERABLE_LOG);
		ERABLE_PLANKS = block(PalamodModBlocks.ERABLE_PLANKS);
		ERABLE_LEAVES = block(PalamodModBlocks.ERABLE_LEAVES);
		ERABLE_STAIRS = block(PalamodModBlocks.ERABLE_STAIRS);
		ERABLE_SLAB = block(PalamodModBlocks.ERABLE_SLAB);
		ERABLE_FENCE = block(PalamodModBlocks.ERABLE_FENCE);
		ERABLE_FENCE_GATE = block(PalamodModBlocks.ERABLE_FENCE_GATE);
		ERABLE_SAPPLING = block(PalamodModBlocks.ERABLE_SAPPLING);
		JUDEECERCIS_SAPPLING = block(PalamodModBlocks.JUDEECERCIS_SAPPLING);
		OSTRYA_SAPPLING = block(PalamodModBlocks.OSTRYA_SAPPLING);
		JACARANDA_SAPPLING = block(PalamodModBlocks.JACARANDA_SAPPLING);
		KIWANOSEED = register("kiwanoseed", KiwanoseedItem::new);
		ORANGEBLUESEED = register("orangeblueseed", OrangeblueseedItem::new);
		CHERVILSEED = register("chervilseed", ChervilseedItem::new);
		EGGPLANT_SEED = register("eggplant_seed", EggplantseedItem::new);
		FINDIUM_STAIRS = block(PalamodModBlocks.FINDIUM_STAIRS);
		FINDIUM_SLAB = block(PalamodModBlocks.FINDIUM_SLAB);
		XPBUSH = block(PalamodModBlocks.XPBUSH);
		XPBUSHON = block(PalamodModBlocks.XPBUSHON);
		XPBERRY = register("xpberry", XpberryItem::new);
		COMPRESSEDXPBERRY = register("compressedxpberry", CompressedxpberryItem::new);
		PALADIUM_CORE = register("paladium_core", PaladiumcoreItem::new);
		SLIMEPAD = block(PalamodModBlocks.SLIMEPAD);
		HEAL_ORB = register("heal_orb", HealorbItem::new);
		SPEED_ORB = register("speed_orb", SpeedorbItem::new);
		STRENGH_ORB = register("strengh_orb", StrenghorbItem::new);
		JUMP_ORB = register("jump_orb", JumporbItem::new);
		KNOCKBACK_ORB = register("knockback_orb", KnockbackorbItem::new);
		SPEED_MODIFIER = register("speed_modifier", SpeedmodifierItem::new);
		KNOCKBACK_MODIFIER = register("knockback_modifier", KnockbackmodifierItem::new);
		FLAME_MODIFIER = register("flame_modifier", FlamemodifierItem::new);
		FORTUNE_MODIFIER = register("fortune_modifier", ForturnemodifierItem::new);
		SPEEDSTICK = register("speedstick", SpeedstickItem::new);
		JUMPSTICK = register("jumpstick", JumpstickItem::new);
		HYPERJUMPSTICK = register("hyperjumpstick", HyperjumpstickItem::new);
		HEALSTICK = register("healstick", HealstickItem::new);
		STRENGHTSTICK = register("strenghtstick", StrenghtstickItem::new);
		DAMAGESTICK = register("damagestick", DamagestickItem::new);
		STICKOFGODS = register("stickofgods", StickofgodsItem::new);
		PALADIUMGREENPICKAXE = register("paladiumgreenpickaxe", PaladiumgreenpickaxeItem::new);
		PALADIUMGREENAXE = register("paladiumgreenaxe", PaladiumgreenaxeItem::new);
		PALADIUMGREENSWORD = register("paladiumgreensword", PaladiumgreenswordItem::new);
		PALADIUMGREENSHOVEL = register("paladiumgreenshovel", PaladiumgreenshovelItem::new);
		GREEN_PALADIUM_INGOT = register("green_paladium_ingot", PaladiumGreeningotItem::new);
		PALADIUM_GREEN_ORE = block(PalamodModBlocks.PALADIUM_GREEN_ORE);
		PALADIUM_GREEN_BLOCK = block(PalamodModBlocks.PALADIUM_GREEN_BLOCK);
		ALCHIMET_1 = block(PalamodModBlocks.ALCHIMET_1);
		GRINDER_CASING = block(PalamodModBlocks.GRINDER_CASING);
		GRINDER_FRAME = block(PalamodModBlocks.GRINDER_FRAME);
		GRINDER_BLOCK = block(PalamodModBlocks.GRINDER_BLOCK);
		PALADIUM_FURNACE = block(PalamodModBlocks.PALADIUM_FURNACE);
		PALADIUM_FURNACE_ON = register("paladium_furnace_on", PaladiumfurnaceonBlock.Item::new);
		AXE_HEAD = register("axe_head", AxeheadItem::new);
		PICKAXE_HEAD = register("pickaxe_head", PickaxeheadItem::new);
		HAMMER_HEAD = register("hammer_head", HammerheadItem::new);
		FASTSWORD_HEAD = register("fastsword_head", FastswordheadItem::new);
		BROADSWORD_HEAD = register("broadsword_head", BroadswordheadItem::new);
		SHOVEL_HEAD = register("shovel_head", ShovelheadItem::new);
		SWORD_HEAD = register("sword_head", SwordheadItem::new);
		AXE_PATERN = register("axe_patern", AxeparternItem::new);
		PICKAXE_PATTERN = register("pickaxe_pattern", PickaxepaternItem::new);
		BROADSWORD_PATTERN = register("broadsword_pattern", BroadswordpaternItem::new);
		BLOCK_PATTERN = register("block_pattern", BlockpaternItem::new);
		FASTSWORD_PATTERN = register("fastsword_pattern", FastswordpaternItem::new);
		INGOT_PATTERN = register("ingot_pattern", IngotpaternItem::new);
		HAMMER_PATTERN = register("hammer_pattern", HammerpaternItem::new);
		SWORD_PATTERN = register("sword_pattern", SwordpaternItem::new);
		SHOVEL_PATTERN = register("shovel_pattern", ShovelpaternItem::new);
		PALADIUMBROADSWORD = register("paladiumbroadsword", PaladiumbroadswordItem::new);
		TITANEBROADSWORD = register("titanebroadsword", TitanebroadswordItem::new);
		AMETHYST_BROADSWORD = register("amethyst_broadsword", AmethystebroadswordItem::new);
		AMETHYST_FASTSWORD = register("amethyst_fastsword", AmethystefastswordItem::new);
		AMETHYST_HAMMER = register("amethyst_hammer", AmethystehammerItem::new);
		TITANE_HAMMER = register("titane_hammer", TitanehammerItem::new);
		PALADIUM_HAMMER = register("paladium_hammer", PaladiumhammerItem::new);
		OBSIDIAN_TRAPDOOR = block(PalamodModBlocks.OBSIDIAN_TRAPDOOR);
		RENFORCED_OBSIDIAN = block(PalamodModBlocks.RENFORCED_OBSIDIAN);
		OBSIDIAN_DOOR = doubleBlock(PalamodModBlocks.OBSIDIAN_DOOR);
		COMPACTED_OBSIDIAN = block(PalamodModBlocks.COMPACTED_OBSIDIAN);
		FAKE_WATER_OBSIDIAN = block(PalamodModBlocks.FAKE_WATER_OBSIDIAN);
		LAVA_OBSIDIAN = block(PalamodModBlocks.LAVA_OBSIDIAN);
		IRON_SPIKE = block(PalamodModBlocks.IRON_SPIKE);
		SPIKE_GOLD = block(PalamodModBlocks.SPIKE_GOLD);
		DIAMOND_SPIKE = block(PalamodModBlocks.DIAMOND_SPIKE);
		AMETHYST_SPIKE = block(PalamodModBlocks.AMETHYST_SPIKE);
		TITANE_SPIKE = block(PalamodModBlocks.TITANE_SPIKE);
		PALADIUM_SPIKE = block(PalamodModBlocks.PALADIUM_SPIKE);
		GOLD_MIXEDCOAL = register("gold_mixedcoal", GoldmixedcoalItem::new);
		AMETHYST_MIXEDCOAL = register("amethyst_mixedcoal", AmethystmixedcoalItem::new);
		TITANE_MIXED_COAL = register("titane_mixed_coal", TitanemixedcoalItem::new);
		PALADIUM_FORGE = block(PalamodModBlocks.PALADIUM_FORGE);
		TITANEFASTSWORD = register("titanefastsword", TitanefastswordItem::new);
		TITANE_SLAB = block(PalamodModBlocks.TITANE_SLAB);
		TITANE_STAIRS = block(PalamodModBlocks.TITANE_STAIRS);
		LOADBLOCK_1T = block(PalamodModBlocks.LOADBLOCK_1T);
		SOCKET_PATTERN = register("socket_pattern", SocketpaternItem::new);
		PALADIUMFASTSWORD = register("paladiumfastsword", PaladiumfastswordItem::new);
		SMELT_MODIFIER = register("smelt_modifier", SmeltmodifierItem::new);
		ENDIUM_HAMMER = register("endium_hammer", EndiumhammerItem::new);
		TCV_2 = block(PalamodModBlocks.TCV_2);
		LEGENDARY_STONE_FORTUNE = register("legendary_stone_fortune", LegendarystonefortuneItem::new);
		LEGENDARY_STONE_INVISIBLE = register("legendary_stone_invisible", LegendarystoneinvisibleItem::new);
		LEGENDARY_STONE_POWER = register("legendary_stone_power", LegendarystonepowerItem::new);
		LEGENDARY_STONE_JOBS = register("legendary_stone_jobs", LegendarystonejobsItem::new);
		LEGENDARY_STONE_TELEPORTATION = register("legendary_stone_teleportation", LegendarystoneteleportationItem::new);
		LEGENDARY_STONE_RANDOM = register("legendary_stone_random", LegendarystonerandomItem::new);
		EGGPLANT_0 = block(PalamodModBlocks.EGGPLANT_0);
		EGGPLANT_1 = block(PalamodModBlocks.EGGPLANT_1);
		EGGPLANT_2 = block(PalamodModBlocks.EGGPLANT_2);
		EGGPLANT_3 = block(PalamodModBlocks.EGGPLANT_3);
		PALADIUM_MACHINE = block(PalamodModBlocks.PALADIUM_MACHINE);
		LUCKY_BLOCK = block(PalamodModBlocks.LUCKY_BLOCK);
		CHERVIL_1 = block(PalamodModBlocks.CHERVIL_1);
		CHERVIL_0 = block(PalamodModBlocks.CHERVIL_0);
		CHERVIL_2 = block(PalamodModBlocks.CHERVIL_2);
		CHERVIL_3 = block(PalamodModBlocks.CHERVIL_3);
		KIWANO_4 = block(PalamodModBlocks.KIWANO_4);
		KIWANO_3 = block(PalamodModBlocks.KIWANO_3);
		KIWANO_2 = block(PalamodModBlocks.KIWANO_2);
		KIWANO_1 = block(PalamodModBlocks.KIWANO_1);
		KIWANO_0 = block(PalamodModBlocks.KIWANO_0);
		WITHER_SHARD = register("wither_shard", WithershardItem::new);
		GREENPALADIUMARMOR_HELMET = register("greenpaladiumarmor_helmet", GreenpaladiumarmorItem.Helmet::new);
		GREENPALADIUMARMOR_CHESTPLATE = register("greenpaladiumarmor_chestplate", GreenpaladiumarmorItem.Chestplate::new);
		GREENPALADIUMARMOR_LEGGINGS = register("greenpaladiumarmor_leggings", GreenpaladiumarmorItem.Leggings::new);
		GREENPALADIUMARMOR_BOOTS = register("greenpaladiumarmor_boots", GreenpaladiumarmorItem.Boots::new);
		LUCKY_BETA = register("lucky_beta", LuckybetaItem::new);
		WEIGHTED_BOOTS = register("weighted_boots", WeightedItem.Boots::new);
		TRESAURE_FALSE = block(PalamodModBlocks.TRESAURE_FALSE);
		TRESAURE_TRUE = block(PalamodModBlocks.TRESAURE_TRUE);
		ALARM = block(PalamodModBlocks.ALARM);
		MEGA_SAFE_CHEST = block(PalamodModBlocks.MEGA_SAFE_CHEST);
		COLORED_LAMP = block(PalamodModBlocks.COLORED_LAMP);
		COLOFUL_LAMP = block(PalamodModBlocks.COLOFUL_LAMP);
		DYNAMITE = register("dynamite", DynamiteItem::new);
		ENDIUM_DYNAMITE = register("endium_dynamite", EndiumdynaItem::new);
		BIG_DYNAMITE = register("big_dynamite", BigdynamiteItem::new);
		DIAMOND_STRING = register("diamond_string", DiamondstringItem::new);
		PALADIUM_PHONE = register("paladium_phone", PaladiumphoneItem::new);
		FAKE_PALADIUM_ORE = block(PalamodModBlocks.FAKE_PALADIUM_ORE);
		MONEY_OTHER = register("money_other", MoneyotherItem::new);
		ORANGEBLUE_1 = block(PalamodModBlocks.ORANGEBLUE_1);
		ORANGEBLUE_0 = block(PalamodModBlocks.ORANGEBLUE_0);
		ORANGEBLUE_2 = block(PalamodModBlocks.ORANGEBLUE_2);
		ORANGEBLUE_3 = block(PalamodModBlocks.ORANGEBLUE_3);
		ORANGEBLUE_4 = block(PalamodModBlocks.ORANGEBLUE_4);
		TRIXIUM_NBT_BLOCK = register("trixium_nbt_block", TrixiumnbtblockBlock.Item::new);
		TRIXIUM = register("trixium", TrixiumItem::new);
		PALADIUM_STAIRS = block(PalamodModBlocks.PALADIUM_STAIRS);
		PALADIUM_SLAB = block(PalamodModBlocks.PALADIUM_SLAB);
		AMETHYST_STAIRS = block(PalamodModBlocks.AMETHYST_STAIRS);
		AMETHYST_SLAB = block(PalamodModBlocks.AMETHYST_SLAB);
		FURNACE_UPGRADE = register("furnace_upgrade", FurnaceupgradeItem::new);
		WITHER_IMBUE_POTION = register("wither_imbue_potion", WitherimbuepotionItem::new);
		FIRE_IMBUE_POTION = register("fire_imbue_potion", FireimbuepotionItem::new);
		POISON_IMBUE_POTION = register("poison_imbue_potion", PoisonimbuepotionItem::new);
		PALADIUM_APPLE = register("paladium_apple", PaladiumappleItem::new);
		PICKAXEOFTHEGODSLV_1 = register("pickaxeofthegodslv_1", Pickaxeofthegodslv1Item::new);
		PICKAXEOFTHEGODSLV_2 = register("pickaxeofthegodslv_2", Pickaxeofthegodslv2Item::new);
		PICKAXEOFTHEGODSLV_3 = register("pickaxeofthegodslv_3", Pickaxeofthegodslv3Item::new);
		PICKAXEOFTHEGODSLV_4 = register("pickaxeofthegodslv_4", Pickaxeofthegodslv4Item::new);
		PICKAXEOFTHEGODSLV_5 = register("pickaxeofthegodslv_5", Pickaxeofthegodslv5Item::new);
		PICKAXEOFTHEGODSLV_6 = register("pickaxeofthegodslv_6", Pickaxeofthegodslv6Item::new);
		PICKAXEOFTHEGODSLV_7 = register("pickaxeofthegodslv_7", Pickaxeofthegodslv7Item::new);
		PICKAXEOFTHEGODSLV_8 = register("pickaxeofthegodslv_8", Pickaxeofthegodslv8Item::new);
		PICKAXEOFTHEGODSLV_9 = register("pickaxeofthegodslv_9", Pickaxeofthegodslv9Item::new);
		PICKAXEOFTHEGODSLV_10 = register("pickaxeofthegodslv_10", Pickaxeofthegodslv10Item::new);
		PICKAXEOFTHEGODSLV_11 = register("pickaxeofthegodslv_11", Pickaxeofthegodslv11Item::new);
		PICKAXEOFTHEGODSLV_12 = register("pickaxeofthegodslv_12", Pickaxeofthegodslv12Item::new);
		PICKAXEOFTHEGODSLV_14 = register("pickaxeofthegodslv_14", Pickaxeofthegodslv14Item::new);
		PICKAXEOFTHEGODSLV_15 = register("pickaxeofthegodslv_15", Pickaxeofthegodslv15Item::new);
		PICKAXEOFTHEGODSLV_16 = register("pickaxeofthegodslv_16", Pickaxeofthegodslv16Item::new);
		PICKAXEOFTHEGODSLV_17 = register("pickaxeofthegodslv_17", Pickaxeofthegodslv17Item::new);
		PICKAXEOFTHEGODSLV_18 = register("pickaxeofthegodslv_18", Pickaxeofthegodslv18Item::new);
		PICKAXEOFTHEGODSLV_19 = register("pickaxeofthegodslv_19", Pickaxeofthegodslv19Item::new);
		PICKAXEOFTHEGODSLV_20 = register("pickaxeofthegodslv_20", Pickaxeofthegodslv20Item::new);
		PICKAXEOFTHEGODSLV_13 = register("pickaxeofthegodslv_13", Pickaxeofthegodslv13Item::new);
		AMETHYST_EXCAVATOR = register("amethyst_excavator", AmethystexacvatorItem::new);
		TITANEEXCAVATOR = register("titaneexcavator", TitaneexcavatorItem::new);
		PALADIUMEXCAVATOR = register("paladiumexcavator", PaladiumexcavatorItem::new);
		BIG_HOLE_UPGRADE = register("big_hole_upgrade", BigholeupgradeItem::new);
		VOIDSTONE = register("voidstone", VoidstoneItem::new);
		AUTO_SMELT_UPGRADE_POTG = register("auto_smelt_upgrade_potg", AutosmeltupgradepotgItem::new);
		INFERNALKNOCKER = register("infernalknocker", InfernalknockerItem::new);
		TRAVELARMOR_HELMET = register("travelarmor_helmet", TravelarmorItem.Helmet::new);
		TRAVELARMOR_CHESTPLATE = register("travelarmor_chestplate", TravelarmorItem.Chestplate::new);
		TRAVELARMOR_LEGGINGS = register("travelarmor_leggings", TravelarmorItem.Leggings::new);
		TRAVELARMOR_BOOTS = register("travelarmor_boots", TravelarmorItem.Boots::new);
		SCUBA_HELMET = register("scuba_helmet", ScubaItem.Helmet::new);
		WING = register("wing", WingItem::new);
		ELEVATOR_WHITE = block(PalamodModBlocks.ELEVATOR_WHITE);
		ELEVATO_RRED = block(PalamodModBlocks.ELEVATO_RRED);
		ELEVATOR_BLUE = block(PalamodModBlocks.ELEVATOR_BLUE);
		ELEVATOR_GREEN = block(PalamodModBlocks.ELEVATOR_GREEN);
		ELEVATOR_PINK = block(PalamodModBlocks.ELEVATOR_PINK);
		ELEVATORL_IGHT_BLUE = block(PalamodModBlocks.ELEVATORL_IGHT_BLUE);
		ELEVATOR_LIGHT_GREEN = block(PalamodModBlocks.ELEVATOR_LIGHT_GREEN);
		ELEVATOR_BROWN = block(PalamodModBlocks.ELEVATOR_BROWN);
		ELEVATOR_ORANGE = block(PalamodModBlocks.ELEVATOR_ORANGE);
		MINAGE_VOIDSTONE = register("minage_voidstone", MinagevoidstoneItem::new);
		CREATIVEPOTG = register("creativepotg", CreativepotgItem::new);
		ELEVATOR_PURPLE = block(PalamodModBlocks.ELEVATOR_PURPLE);
		ELEVATOR_GRAY = block(PalamodModBlocks.ELEVATOR_GRAY);
		ELEVATOR_LIGHT_GRAY = block(PalamodModBlocks.ELEVATOR_LIGHT_GRAY);
		ELEVATOR_CYAN = block(PalamodModBlocks.ELEVATOR_CYAN);
		PALADIUMGOLEM_SPAWN_EGG = register("paladiumgolem_spawn_egg", properties -> new SpawnEggItem(PalamodModEntities.PALADIUMGOLEM.get(), properties));
		GUARDIAN_STONE = register("guardian_stone", GuardianstoneItem::new);
		GUARDIAN_BLOCK = register("guardian_block", GuardianblockBlock.Item::new);
		GREEN_PALADIUM_BROADSWORD_HEAD = register("green_paladium_broadsword_head", HeadgreenbroadswordItem::new);
		GREEN_PALADIUM_SWORD_HEAD = register("green_paladium_sword_head", HeadgreenswordItem::new);
		GREEN_PALADIUM_PICKAXE_HEAD = register("green_paladium_pickaxe_head", HeadgreenpickaxeItem::new);
		GREEN_PALADIUM_AXE_HEAD = register("green_paladium_axe_head", HeadgreenaxeItem::new);
		GREEN_PALADIUM_SHOVEL_HEAD = register("green_paladium_shovel_head", HeadgreenshovelItem::new);
		HEADENDIUMSWORD = register("headendiumsword", HeadendiumswordItem::new);
		HEAD_ENDIUM_PICKAXE = register("head_endium_pickaxe", HeadendiumpickaxeItem::new);
		HEAD_ENDIUM_AXE = register("head_endium_axe", HeadendiumaxeItem::new);
		GREENPALADIUMBROADSWORD = register("greenpaladiumbroadsword", GreenpaladiumbroadswordItem::new);
		ONE_MORE_MODIFIER = register("one_more_modifier", OnemoremodifierItem::new);
		ENDIUM_BROADSWORD_HEAD = register("endium_broadsword_head", EndiumbroadswordheadItem::new);
		ENDIUMBROADSWORD = register("endiumbroadsword", EndiumbroadswordItem::new);
		GREEN_PALADIUM_HAMMER = register("green_paladium_hammer", GreenpaladiumhammerItem::new);
		GREEN_PALADIUM_HAMMER_HEAD = register("green_paladium_hammer_head", GreenpaladiumhammerheadItem::new);
		ENDIUM_HAMMER_HEAD = register("endium_hammer_head", EndiumhammerheadItem::new);
		MAGICAL_TOOL = register("magical_tool", MagicaltoolItem::new);
		STONY = register("stony", StonyBlock.Item::new);
		CLOUD_BLOCK = block(PalamodModBlocks.CLOUD_BLOCK);
		CROWN = block(PalamodModBlocks.CROWN);
		FACTION_BLOCK = block(PalamodModBlocks.FACTION_BLOCK);
		BLACK_LUCKY_BLOCK = register("black_lucky_block", BlackluckyblockBlock.Item::new);
		ENFYUPOTION = register("enfyupotion", EnfyupotionItem::new);
		INVISIBLEARMOR_HELMET = register("invisiblearmor_helmet", InvisiblearmorItem.Helmet::new);
		INVISIBLEARMOR_CHESTPLATE = register("invisiblearmor_chestplate", InvisiblearmorItem.Chestplate::new);
		INVISIBLEARMOR_LEGGINGS = register("invisiblearmor_leggings", InvisiblearmorItem.Leggings::new);
		INVISIBLEARMOR_BOOTS = register("invisiblearmor_boots", InvisiblearmorItem.Boots::new);
		RAINBOWARMOR_HELMET = register("rainbowarmor_helmet", RanbowarmorItem.Helmet::new);
		RAINBOWARMOR_CHESTPLATE = register("rainbowarmor_chestplate", RanbowarmorItem.Chestplate::new);
		RAINBOWARMOR_LEGGINGS = register("rainbowarmor_leggings", RanbowarmorItem.Leggings::new);
		RAINBOWARMOR_BOOTS = register("rainbowarmor_boots", RanbowarmorItem.Boots::new);
		PALADIUMARMORCUSTOM_1_HELMET = register("paladiumarmorcustom_1_helmet", Paladiumarmorcustom1Item.Helmet::new);
		PALADIUMARMORCUSTOM_1_CHESTPLATE = register("paladiumarmorcustom_1_chestplate", Paladiumarmorcustom1Item.Chestplate::new);
		PALADIUMARMORCUSTOM_1_LEGGINGS = register("paladiumarmorcustom_1_leggings", Paladiumarmorcustom1Item.Leggings::new);
		PALADIUMARMORCUSTOM_1_BOOTS = register("paladiumarmorcustom_1_boots", Paladiumarmorcustom1Item.Boots::new);
		PALADIUMARMORCUSTOM_2_HELMET = register("paladiumarmorcustom_2_helmet", Paladiumarmorcustom2Item.Helmet::new);
		PALADIUMARMORCUSTOM_2_CHESTPLATE = register("paladiumarmorcustom_2_chestplate", Paladiumarmorcustom2Item.Chestplate::new);
		PALADIUMARMORCUSTOM_2_LEGGINGS = register("paladiumarmorcustom_2_leggings", Paladiumarmorcustom2Item.Leggings::new);
		PALADIUMARMORCUSTOM_2_BOOTS = register("paladiumarmorcustom_2_boots", Paladiumarmorcustom2Item.Boots::new);
		PALADIUMARMORCUSTOM_3_HELMET = register("paladiumarmorcustom_3_helmet", Paladiumarmorcustom3Item.Helmet::new);
		PALADIUMARMORCUSTOM_3_CHESTPLATE = register("paladiumarmorcustom_3_chestplate", Paladiumarmorcustom3Item.Chestplate::new);
		PALADIUMARMORCUSTOM_3_LEGGINGS = register("paladiumarmorcustom_3_leggings", Paladiumarmorcustom3Item.Leggings::new);
		PALADIUMARMORCUSTOM_3_BOOTS = register("paladiumarmorcustom_3_boots", Paladiumarmorcustom3Item.Boots::new);
		FLYPOTION = register("flypotion", FlypotionItem::new);
		SPACE_FOOD = register("space_food", SpacefoodItem::new);
		JUDEECERCIS_DOOR = doubleBlock(PalamodModBlocks.JUDEECERCIS_DOOR);
		CHUNKANASLYSER = register("chunkanaslyser", ChunkanaslyserItem::new);
		ENDIUM_LUCKY_BLOCK = block(PalamodModBlocks.ENDIUM_LUCKY_BLOCK);
		ENDIUM_NUGGET_ORE = block(PalamodModBlocks.ENDIUM_NUGGET_ORE);
		ENDIUM_SLAB = block(PalamodModBlocks.ENDIUM_SLAB);
		ENDIUM_STAIRS = block(PalamodModBlocks.ENDIUM_STAIRS);
		GREEN_PALADIUM_STAIRS = block(PalamodModBlocks.GREEN_PALADIUM_STAIRS);
		GREEN_PALADIUM_SLAB = block(PalamodModBlocks.GREEN_PALADIUM_SLAB);
		UPLOADER = block(PalamodModBlocks.UPLOADER);
		INTERNET_CARD = register("internet_card", InternetcardItem::new);
		SMALL_RING = register("small_ring", SmallringItem::new);
		MEDIUM_RING = register("medium_ring", MediumringItem::new);
		BIG_RING = register("big_ring", BigringItem::new);
		ENDIUM_SMALL_RING = register("endium_small_ring", EndiumsmallringItem::new);
		ENDIUM_MEDIUM_RING = register("endium_medium_ring", EndiummediumringItem::new);
		ENDIUM_BIG_RING = register("endium_big_ring", EndiumbigringItem::new);
		OSTRYA_DOOR = doubleBlock(PalamodModBlocks.OSTRYA_DOOR);
		ERABLE_DOOR = doubleBlock(PalamodModBlocks.ERABLE_DOOR);
		JACARANDA_DOOR = doubleBlock(PalamodModBlocks.JACARANDA_DOOR);
		HDV_BLOCK = block(PalamodModBlocks.HDV_BLOCK);
		ERABLETRAPDOOR = block(PalamodModBlocks.ERABLETRAPDOOR);
		MONEY_ITEM = register("money_item", MoneyitemItem::new);
		PALADIUM_PARTICLE = register("paladium_particle", PaladiumparticleItem::new);
		FLATTEN_TITANE_CHEST = block(PalamodModBlocks.FLATTEN_TITANE_CHEST);
		GREEN_PALADIUM_SMALL_RING = register("green_paladium_small_ring", SmallringgreenpaladiumItem::new);
		GREEN_PALADIUM_MEDIUM_RING = register("green_paladium_medium_ring", MediumringgreenpaladiumItem::new);
		GREEN_PALADIUM_BIG_RING = register("green_paladium_big_ring", BigringgreenpaladiumItem::new);
		HANG_GLIDER = register("hang_glider", HanggliderItem::new);
		FLATTEN_PALADIUM_CHEST = block(PalamodModBlocks.FLATTEN_PALADIUM_CHEST);
		FLATTEN_AMETHYST_CHEST = block(PalamodModBlocks.FLATTEN_AMETHYST_CHEST);
		PESYBLPOTION = register("pesyblpotion", PesyblpotionItem::new);
		GREEN_PALADIUM_PARTICLE = register("green_paladium_particle", GreenpaladiumparticleItem::new);
		COMPRESSED_GREEN_PALADUM = register("compressed_green_paladum", CompressedgreenpaladumItem::new);
		GREENPALADUMEXCATOR = register("greenpaladumexcator", GreenpaladumexcatorItem::new);
		CREATIVE_HAMMER = register("creative_hammer", CreativehammerItem::new);
		FLATTEN_GREEN_PALADIUM_CHEST = block(PalamodModBlocks.FLATTEN_GREEN_PALADIUM_CHEST);
		FLATTEN_ENDIUM_CHEST = block(PalamodModBlocks.FLATTEN_ENDIUM_CHEST);
		MONEY_1K = register("money_1k", Moneye1k1Item::new);
		DOWNLOADER = block(PalamodModBlocks.DOWNLOADER);
		ALARM_ON = block(PalamodModBlocks.ALARM_ON);
		CREATIVE_TRIXIUM_SWORD = register("creative_trixium_sword", CreativetrixiumswordItem::new);
		DEEPSLATE_AMETHYST_ORE = block(PalamodModBlocks.DEEPSLATE_AMETHYST_ORE);
		DEEPSLATE_TITANE_ORE = block(PalamodModBlocks.DEEPSLATE_TITANE_ORE);
		DEEPSLATE_PALADIUM_ORE = block(PalamodModBlocks.DEEPSLATE_PALADIUM_ORE);
		DEEPSLATE_TRIXIUM_ORE = block(PalamodModBlocks.DEEPSLATE_TRIXIUM_ORE);
		DEEPSLATE_GREEN_PALADIUM_ORE = block(PalamodModBlocks.DEEPSLATE_GREEN_PALADIUM_ORE);
		DEEPSLATE_ENDIUM_NUGGET_ORE = block(PalamodModBlocks.DEEPSLATE_ENDIUM_NUGGET_ORE);
		DEEPSLATE_FINDIUM_ORE = block(PalamodModBlocks.DEEPSLATE_FINDIUM_ORE);
		TRIXIUM_ORE = block(PalamodModBlocks.TRIXIUM_ORE);
		TRIXIUM_BLOCK = block(PalamodModBlocks.TRIXIUM_BLOCK);
		ENDIUM_POLLEN = register("endium_pollen", EndiumpollenItem::new);
		POTATO_BACKPACK = register("potato_backpack", PotatobackpackItem::new);
		PALADIUM_POLLEN = register("paladium_pollen", PaladiumpollenItem::new);
		TITANE_POLLEN = register("titane_pollen", TitanepollenItem::new);
		AMETHYST_POLLEN = register("amethyst_pollen", AmethystpollenItem::new);
		AMETHYST_PARTICLE = register("amethyst_particle", AmethystparticleItem::new);
		TITANE_PARTICLE = register("titane_particle", TitaneparticleItem::new);
		DIAMOND_PARTICLE = register("diamond_particle", DiamondparticleItem::new);
		GOLD_PARTICLE = register("gold_particle", GoldparticleItem::new);
		IRON_PARTICLE = register("iron_particle", IronparticleItem::new);
		GREENPALADIUMFASTSWORD = register("greenpaladiumfastsword", GreenpaladiumfastswordItem::new);
		GREEN_PALADIUM_FASTSWORD_HEAD = register("green_paladium_fastsword_head", GreenpaladiumfastswordheadItem::new);
		ENDIUMFASTSWORD = register("endiumfastsword", EndiumfastswordItem::new);
		ENDIUM_FASTSWORD_HEAD = register("endium_fastsword_head", EndiumfastswordheadItem::new);
		ENDIUM_SHOVEL_HEAD = register("endium_shovel_head", EndiumshovelheadItem::new);
		ENDIUMSHOVEL = register("endiumshovel", EndiumshovelItem::new);
		CAVE_BLOCK = block(PalamodModBlocks.CAVE_BLOCK);
		ENDIUM_FRAGMENT = register("endium_fragment", EndiumfragmentItem::new);
		FLAT_CHEST_UPGRADE = register("flat_chest_upgrade", FlatchestupgradeItem::new);
		PALADIUM_CHEST = block(PalamodModBlocks.PALADIUM_CHEST);
		GREEN_PALADIUM_CHEST = block(PalamodModBlocks.GREEN_PALADIUM_CHEST);
		AMETHYST_CHEST = block(PalamodModBlocks.AMETHYST_CHEST);
		ENDIUM_CHEST = block(PalamodModBlocks.ENDIUM_CHEST);
		TITANE_CHEST = block(PalamodModBlocks.TITANE_CHEST);
		WOODEN_SPIKE = block(PalamodModBlocks.WOODEN_SPIKE);
		WOODEN_OBSIDIAN_SPIKE = block(PalamodModBlocks.WOODEN_OBSIDIAN_SPIKE);
		IRON_OBSIDIAN_SPIKE = block(PalamodModBlocks.IRON_OBSIDIAN_SPIKE);
		GOLDEN_OBSIDIAN_SPIKE = block(PalamodModBlocks.GOLDEN_OBSIDIAN_SPIKE);
		DIAMOND_OBSIDIAN_SPIKE = block(PalamodModBlocks.DIAMOND_OBSIDIAN_SPIKE);
		AMETHYS_TOBSIDIAN_SPIKE = block(PalamodModBlocks.AMETHYS_TOBSIDIAN_SPIKE);
		TITANE_OBSIDIAN_SPIKE = block(PalamodModBlocks.TITANE_OBSIDIAN_SPIKE);
		PALADIUM_OBSIDIAN_SPIKE = block(PalamodModBlocks.PALADIUM_OBSIDIAN_SPIKE);
		ONLINE_DETECTOR = block(PalamodModBlocks.ONLINE_DETECTOR);
		ONLINE_DETECTOR_ON = block(PalamodModBlocks.ONLINE_DETECTOR_ON);
		COBBLEBREAKER = block(PalamodModBlocks.COBBLEBREAKER);
		OBSIDIANPICKAXE = register("obsidianpickaxe", ObsidianpickaxeItem::new);
		DOLLARS_STONE = register("dollars_stone", MoulastoneItem::new);
		COBBLEBREAKER_AMETHYST_UPGRADE = register("cobblebreaker_amethyst_upgrade", CobblebreakeramethystupgradeItem::new);
		COBBLEBREAKER_TITANE_UPGRADE = register("cobblebreaker_titane_upgrade", CobblebreakertitaneupgradeItem::new);
		COBBLEBREAKER_PALADIUM_UPGRADE = register("cobblebreaker_paladium_upgrade", CobblebreakerpaladiumupgradeItem::new);
		FERTILZED_DIRT = block(PalamodModBlocks.FERTILZED_DIRT);
		AMETHYST_HOE = register("amethyst_hoe", AmethtysthoeItem::new);
		TITANEHOE = register("titanehoe", TitanehoeItem::new);
		PALADIUM_HOE = register("paladium_hoe", PaladiumhoeItem::new);
		GREEN_PALADIUM_HOE = register("green_paladium_hoe", GreenpaladiumhoeItem::new);
		ENDIUM_HOE = register("endium_hoe", EndiumhoeItem::new);
		AMETHYST_SEEDPLANTER = register("amethyst_seedplanter", AmethystseedplanterItem::new);
		TITANE_SEEDPLANTER = register("titane_seedplanter", TitaneseedplanterItem::new);
		PALADIUM_SEEDPLANTER = register("paladium_seedplanter", PaladiumseedplanterItem::new);
		GREEN_PALADIUM_SEEDPLANTER = register("green_paladium_seedplanter", GreenpaladiumseedplanterItem::new);
		ENDIUM_SEEDPLANTER = register("endium_seedplanter", EndiumseedplanterItem::new);
		PRINTINGPRESS = register("printingpress", PrintingpressBlock.Item::new);
		PLATE = register("plate", PlateItem::new);
		TYPESETTINGTABLE = register("typesettingtable", TypesettingtableBlock.Item::new);
		DRAWBRIDGE = register("drawbridge", DrawbridgeBlock.Item::new);
		PALADIUMARMORCUSTOM_4_HELMET = register("paladiumarmorcustom_4_helmet", Paladiumarmorcustom4Item.Helmet::new);
		PALADIUMARMORCUSTOM_4_CHESTPLATE = register("paladiumarmorcustom_4_chestplate", Paladiumarmorcustom4Item.Chestplate::new);
		PALADIUMARMORCUSTOM_4_LEGGINGS = register("paladiumarmorcustom_4_leggings", Paladiumarmorcustom4Item.Leggings::new);
		PALADIUMARMORCUSTOM_4_BOOTS = register("paladiumarmorcustom_4_boots", Paladiumarmorcustom4Item.Boots::new);
		PALADIUMARMORCUSTOM_5_HELMET = register("paladiumarmorcustom_5_helmet", Paladiumarmorcustom5Item.Helmet::new);
		PALADIUMARMORCUSTOM_5_CHESTPLATE = register("paladiumarmorcustom_5_chestplate", Paladiumarmorcustom5Item.Chestplate::new);
		PALADIUMARMORCUSTOM_5_LEGGINGS = register("paladiumarmorcustom_5_leggings", Paladiumarmorcustom5Item.Leggings::new);
		PALADIUMARMORCUSTOM_5_BOOTS = register("paladiumarmorcustom_5_boots", Paladiumarmorcustom5Item.Boots::new);
		PALADIUMARMORCUSTOM_6_HELMET = register("paladiumarmorcustom_6_helmet", Paladiumarmorcustom6Item.Helmet::new);
		PALADIUMARMORCUSTOM_6_CHESTPLATE = register("paladiumarmorcustom_6_chestplate", Paladiumarmorcustom6Item.Chestplate::new);
		PALADIUMARMORCUSTOM_6_LEGGINGS = register("paladiumarmorcustom_6_leggings", Paladiumarmorcustom6Item.Leggings::new);
		PALADIUMARMORCUSTOM_6_BOOTS = register("paladiumarmorcustom_6_boots", Paladiumarmorcustom6Item.Boots::new);
		PALADIUMARMORCUSTOM_7_HELMET = register("paladiumarmorcustom_7_helmet", Paladiumarmorcustom7Item.Helmet::new);
		PALADIUMARMORCUSTOM_7_CHESTPLATE = register("paladiumarmorcustom_7_chestplate", Paladiumarmorcustom7Item.Chestplate::new);
		PALADIUMARMORCUSTOM_7_LEGGINGS = register("paladiumarmorcustom_7_leggings", Paladiumarmorcustom7Item.Leggings::new);
		PALADIUMARMORCUSTOM_7_BOOTS = register("paladiumarmorcustom_7_boots", Paladiumarmorcustom7Item.Boots::new);
		PALADIUMARMORCUSTOM_8_HELMET = register("paladiumarmorcustom_8_helmet", Paladiumarmorcustom8Item.Helmet::new);
		PALADIUMARMORCUSTOM_8_CHESTPLATE = register("paladiumarmorcustom_8_chestplate", Paladiumarmorcustom8Item.Chestplate::new);
		PALADIUMARMORCUSTOM_8_LEGGINGS = register("paladiumarmorcustom_8_leggings", Paladiumarmorcustom8Item.Leggings::new);
		PALADIUMARMORCUSTOM_8_BOOTS = register("paladiumarmorcustom_8_boots", Paladiumarmorcustom8Item.Boots::new);
		PALADIUMARMORCUSTOM_9_HELMET = register("paladiumarmorcustom_9_helmet", Paladiumarmorcustom9Item.Helmet::new);
		PALADIUMARMORCUSTOM_9_CHESTPLATE = register("paladiumarmorcustom_9_chestplate", Paladiumarmorcustom9Item.Chestplate::new);
		PALADIUMARMORCUSTOM_9_LEGGINGS = register("paladiumarmorcustom_9_leggings", Paladiumarmorcustom9Item.Leggings::new);
		PALADIUMARMORCUSTOM_9_BOOTS = register("paladiumarmorcustom_9_boots", Paladiumarmorcustom9Item.Boots::new);
		PALADIUMARMORCUSTOM_10_HELMET = register("paladiumarmorcustom_10_helmet", Paladiumarmorcustom10Item.Helmet::new);
		PALADIUMARMORCUSTOM_10_CHESTPLATE = register("paladiumarmorcustom_10_chestplate", Paladiumarmorcustom10Item.Chestplate::new);
		PALADIUMARMORCUSTOM_10_LEGGINGS = register("paladiumarmorcustom_10_leggings", Paladiumarmorcustom10Item.Leggings::new);
		PALADIUMARMORCUSTOM_10_BOOTS = register("paladiumarmorcustom_10_boots", Paladiumarmorcustom10Item.Boots::new);
		UNKNOWNBLOCK = block(PalamodModBlocks.UNKNOWNBLOCK);
		COMPRESSEDSPONGE = block(PalamodModBlocks.COMPRESSEDSPONGE);
		SPONGETNT = block(PalamodModBlocks.SPONGETNT);
		LAVASPONGE = block(PalamodModBlocks.LAVASPONGE);
		WETLAVASPONGE = block(PalamodModBlocks.WETLAVASPONGE);
		WITHERTNT = block(PalamodModBlocks.WITHERTNT);
		MAGIC_TNT = block(PalamodModBlocks.MAGIC_TNT);
		COMPACTTNT = block(PalamodModBlocks.COMPACTTNT);
		ENDIUMTNT = block(PalamodModBlocks.ENDIUMTNT);
		RENFORCEDOBSIDIANSTAIRS = block(PalamodModBlocks.RENFORCEDOBSIDIANSTAIRS);
		OBSIDIANSTAIRS = block(PalamodModBlocks.OBSIDIANSTAIRS);
		OBSIDIANSLAB = block(PalamodModBlocks.OBSIDIANSLAB);
		HARDENED_OBSIDIAN_SLAB = block(PalamodModBlocks.HARDENED_OBSIDIAN_SLAB);
		FAKE_WATER_BUCKET = register("fake_water_bucket", FakewterItem::new);
		ANGELIC_WATER_BUCKET = register("angelic_water_bucket", AngelicwterItem::new);
		SLIME_OBSIDIAN = block(PalamodModBlocks.SLIME_OBSIDIAN);
		POISON_OBSIDIAN = block(PalamodModBlocks.POISON_OBSIDIAN);
		SEALEDXPBOTTLE = register("sealedxpbottle", SealedxpbottleItem::new);
		MIXED_ENDIUM_INGOT = register("mixed_endium_ingot", MixedendiumingotItem::new);
		MIXED_ENDIUM_ARMOR_HELMET = register("mixed_endium_armor_helmet", MixedendiumarmorItem.Helmet::new);
		MIXED_ENDIUM_ARMOR_CHESTPLATE = register("mixed_endium_armor_chestplate", MixedendiumarmorItem.Chestplate::new);
		MIXED_ENDIUM_ARMOR_LEGGINGS = register("mixed_endium_armor_leggings", MixedendiumarmorItem.Leggings::new);
		MIXED_ENDIUM_ARMOR_BOOTS = register("mixed_endium_armor_boots", MixedendiumarmorItem.Boots::new);
		DOUBLEEXPPOTION = register("doubleexppotion", DoubleexppotionItem::new);
		X_10XPPOTION = register("x_10xppotion", X10xppotionItem::new);
		XPBOTTLE = register("xpbottle", XpbottleItem::new);
		EXTRACTOR = block(PalamodModBlocks.EXTRACTOR);
		BOOM_OBSIDIAN = block(PalamodModBlocks.BOOM_OBSIDIAN);
		MEGABOOMOBSIDIAN = block(PalamodModBlocks.MEGABOOMOBSIDIAN);
		HARPAGOPHYTUM = block(PalamodModBlocks.HARPAGOPHYTUM);
		GLUEBALL_RED = block(PalamodModBlocks.GLUEBALL_RED);
		GREEN_GLUEBALL = block(PalamodModBlocks.GREEN_GLUEBALL);
		GLUEBALL_LIGHT_GREEN = block(PalamodModBlocks.GLUEBALL_LIGHT_GREEN);
		GLUEBALL_DARK_GREEN = block(PalamodModBlocks.GLUEBALL_DARK_GREEN);
		GLUEBALL_BLUE = block(PalamodModBlocks.GLUEBALL_BLUE);
		GLUEBALL_PURPLE = block(PalamodModBlocks.GLUEBALL_PURPLE);
		GLUEBALL_YELLOW = block(PalamodModBlocks.GLUEBALL_YELLOW);
		GLUEBALL_CYAN = block(PalamodModBlocks.GLUEBALL_CYAN);
		GLUEBALL_ORANGE = block(PalamodModBlocks.GLUEBALL_ORANGE);
		GLUEBALL_GRAY = block(PalamodModBlocks.GLUEBALL_GRAY);
		GLUEBALLPATTERN = register("glueballpattern", GlueballpaternItem::new);
		DISC_MII_CHALENGE = register("disc_mii_chalenge", MiichalengeItem::new);
		DISC_FUZEIII = register("disc_fuzeiii", FuzediscItem::new);
		DISC_ANTI_FUZE = register("disc_anti_fuze", AntifuzediscItem::new);
		DISC_ROULETTE_PALADIENNE = register("disc_roulette_paladienne", RoulettepaladiennediscItem::new);
		DISC_CLASH_KUMIZ = register("disc_clash_kumiz", ClashkumizItem::new);
		SLIMEPAD_RED = block(PalamodModBlocks.SLIMEPAD_RED);
		SLIMEPAD_BLUE = block(PalamodModBlocks.SLIMEPAD_BLUE);
		SLIMEPAD_ORANGE = block(PalamodModBlocks.SLIMEPAD_ORANGE);
		SLIMEPAD_PURPLE = block(PalamodModBlocks.SLIMEPAD_PURPLE);
		SWITCHARROWITEM = register("switcharrowitem", SwitcharrowitemItem::new);
		AMETHYST_BACKPACK = register("amethyst_backpack", AmethystbackpackItem::new);
		TITANE_BACKPACK = register("titane_backpack", TitanebackpackItem::new);
		PALADUM_BACKPACK = register("paladum_backpack", PaladumbackpackItem::new);
		ENDIUM_BACKPACK = register("endium_backpack", EndiumbackpackItem::new);
		TOTEMFERTILITY = block(PalamodModBlocks.TOTEMFERTILITY);
		GODVILLAGER_SPAWN_EGG = register("godvillager_spawn_egg", properties -> new SpawnEggItem(PalamodModEntities.GODVILLAGER.get(), properties));
		XPBUSHLOW = block(PalamodModBlocks.XPBUSHLOW);
		CHESTEXPLORER = register("chestexplorer", ChestexplorerItem::new);
		PALADIUMRAWORE = register("paladiumrawore", PaladiumraworeItem::new);
		TITANERAWORE = register("titanerawore", TitaneraworeItem::new);
		AMETHYSTRAWORE = register("amethystrawore", AmethystraworeItem::new);
		GREENPALADIUMRAWORE = register("greenpaladiumrawore", GreenpaladiumraworeItem::new);
		ROTATED_PALADIUM_HOPPER = register("rotated_paladium_hopper", PaladiumhopperBlock.Item::new);
		PALADIUM_HOPPER = block(PalamodModBlocks.PALADIUM_HOPPER);
		TRIXIUMSLAB = block(PalamodModBlocks.TRIXIUMSLAB);
		TRIXIUMSTAIRS = block(PalamodModBlocks.TRIXIUMSTAIRS);
		COBBLEBREAKERSERVER = block(PalamodModBlocks.COBBLEBREAKERSERVER);
		ROTATED_SLIMEPAD = block(PalamodModBlocks.ROTATED_SLIMEPAD);
		ROTATED_RED_SLIMEPAD = block(PalamodModBlocks.ROTATED_RED_SLIMEPAD);
		ROTATED_PURPLE_SLIMEPAD = block(PalamodModBlocks.ROTATED_PURPLE_SLIMEPAD);
		ROTATED_BLUE_SLIMEPAD = block(PalamodModBlocks.ROTATED_BLUE_SLIMEPAD);
		ROTATED_ORANGE_SLIMEPAD = block(PalamodModBlocks.ROTATED_ORANGE_SLIMEPAD);
		WITHEREDOBSIDIAN_0 = block(PalamodModBlocks.WITHEREDOBSIDIAN_0);
		WITHEREDOBSIDIAN_1 = block(PalamodModBlocks.WITHEREDOBSIDIAN_1);
		WITHEREDOBSIDIAN_2 = block(PalamodModBlocks.WITHEREDOBSIDIAN_2);
		WITHEREDOBSIDIAN_3 = block(PalamodModBlocks.WITHEREDOBSIDIAN_3);
		WITHEREDOBSIDIAN_4 = block(PalamodModBlocks.WITHEREDOBSIDIAN_4);
		WITHEREDOBSIDIAN_5 = block(PalamodModBlocks.WITHEREDOBSIDIAN_5);
		WITHEREDOBSIDIAN_6 = block(PalamodModBlocks.WITHEREDOBSIDIAN_6);
		WITHEREDOBSIDIAN_7 = block(PalamodModBlocks.WITHEREDOBSIDIAN_7);
		WITHEREDOBSIDIAN_8 = block(PalamodModBlocks.WITHEREDOBSIDIAN_8);
		WITHEREDOBSIDIAN_9 = block(PalamodModBlocks.WITHEREDOBSIDIAN_9);
		WITHEREDOBSIDIAN_10 = block(PalamodModBlocks.WITHEREDOBSIDIAN_10);
		WITHEREDOBSIDIAN_11 = block(PalamodModBlocks.WITHEREDOBSIDIAN_11);
		WITHEREDOBSIDIAN_12 = block(PalamodModBlocks.WITHEREDOBSIDIAN_12);
		WITHEREDOBSIDIAN_13 = block(PalamodModBlocks.WITHEREDOBSIDIAN_13);
		MINE_CLEARER = register("mine_clearer", MineclearerItem::new);
		SOFT_STONE = block(PalamodModBlocks.SOFT_STONE);
		SOFTENED_AMETHYST_ORE = block(PalamodModBlocks.SOFTENED_AMETHYST_ORE);
		SOFTENED_TITANE_ORE = block(PalamodModBlocks.SOFTENED_TITANE_ORE);
		SOFTENED_PALADIUM_ORE = block(PalamodModBlocks.SOFTENED_PALADIUM_ORE);
		SOFTENED_TRIXIUM_ORE = block(PalamodModBlocks.SOFTENED_TRIXIUM_ORE);
		SOFTENED_GREEN_PALADIUM_ORE = block(PalamodModBlocks.SOFTENED_GREEN_PALADIUM_ORE);
		SOFTENED_FINDIUM_ORE = block(PalamodModBlocks.SOFTENED_FINDIUM_ORE);
		SOFTENED_ENDIUM_NUGGET_ORE = block(PalamodModBlocks.SOFTENED_ENDIUM_NUGGET_ORE);
		MINERJOBSITEM = register("minerjobsitem", MinerjobsitemItem::new);
		FARMERJOBSITEM = register("farmerjobsitem", FarmerjobsitemItem::new);
		HUNTERJOBSITEM = register("hunterjobsitem", HunterjobsitemItem::new);
		ALCHIMISTJOBSITEM = register("alchimistjobsitem", AlchimistjobsitemItem::new);
		CUSTOMAIR = register("customair", CustomairItem::new);
		COBBLED_SOFT_STONE = block(PalamodModBlocks.COBBLED_SOFT_STONE);
		SOFTSTONESLAB = block(PalamodModBlocks.SOFTSTONESLAB);
		SOFTSTONESTAIRS = block(PalamodModBlocks.SOFTSTONESTAIRS);
		COBBLEDSOFTSTONESLAB = block(PalamodModBlocks.COBBLEDSOFTSTONESLAB);
		COBBLEDSOFTSTONESTAIRS = block(PalamodModBlocks.COBBLEDSOFTSTONESTAIRS);
		SOFTENED_COAL_ORE = block(PalamodModBlocks.SOFTENED_COAL_ORE);
		SOFTENED_IRON_ORE = block(PalamodModBlocks.SOFTENED_IRON_ORE);
		SOFTENED_GOLD_ORE = block(PalamodModBlocks.SOFTENED_GOLD_ORE);
		SOFTENED_DIAMOND_ORE = block(PalamodModBlocks.SOFTENED_DIAMOND_ORE);
		SOFTENED_REDSTONE_ORE = block(PalamodModBlocks.SOFTENED_REDSTONE_ORE);
		SOFTENED_LAPIS_LAZULIS_ORE = block(PalamodModBlocks.SOFTENED_LAPIS_LAZULIS_ORE);
		PIGARMOR_HELMET = register("pigarmor_helmet", PigarmorItem.Helmet::new);
		PIGARMOR_CHESTPLATE = register("pigarmor_chestplate", PigarmorItem.Chestplate::new);
		PIGARMOR_LEGGINGS = register("pigarmor_leggings", PigarmorItem.Leggings::new);
		PIGARMOR_BOOTS = register("pigarmor_boots", PigarmorItem.Boots::new);
		COMPRESSEDENDIUM = register("compressedendium", CompressedendiumItem::new);
		EXTRACTOR_ITEM = register("extractor_item", ExtractorItem::new);
		FLOWERTOTEM = block(PalamodModBlocks.FLOWERTOTEM);
		MINERALFLOWER = block(PalamodModBlocks.MINERALFLOWER);
		ENDIUMFLOWER = block(PalamodModBlocks.ENDIUMFLOWER);
		ENDIUMFLOWERON = block(PalamodModBlocks.ENDIUMFLOWERON);
		CLATHRUSARCHERI = block(PalamodModBlocks.CLATHRUSARCHERI);
		PALADIUMFLOWER = block(PalamodModBlocks.PALADIUMFLOWER);
		DANKAROCTEST_1_SPAWN_EGG = register("dankaroctest_1_spawn_egg", properties -> new SpawnEggItem(PalamodModEntities.DANKAROCTEST_1.get(), properties));
		DANKABLOCK = block(PalamodModBlocks.DANKABLOCK);
		PALADIUMINK = register("paladiumink", PaladiuminkItem::new);
		UNCLAIMFINDER = register("unclaimfinder", UnclaimfinderItem::new);
		UNCLAIMFINDERORANGE = register("unclaimfinderorange", UnclaimfinderorangeItem::new);
		UNCLAIMFINDERRED = register("unclaimfinderred", UnclaimfinderredItem::new);
		UNCLAIMFINDERBLUE = register("unclaimfinderblue", UnclaimfinderblueItem::new);
		POCKETENDERCHEST = register("pocketenderchest", PocketenderchestItem::new);
		CAVERNEHAMMER = register("cavernehammer", CavernehammerItem::new);
		BROKENSPAWNER = register("brokenspawner", properties -> new BrokenspawnerBlock.Item(properties.stacksTo(1)));
		SPAWNCONTROLLER = block(PalamodModBlocks.SPAWNCONTROLLER);
		EMPTYSPAWNER = block(PalamodModBlocks.EMPTYSPAWNER);
		DIAMONDINFUSEDOBSIDIAN = block(PalamodModBlocks.DIAMONDINFUSEDOBSIDIAN);
		AMETHYSTINFUSEDOBSIDIAN = block(PalamodModBlocks.AMETHYSTINFUSEDOBSIDIAN);
		TITANEINFUSEDOBSIDIAN = block(PalamodModBlocks.TITANEINFUSEDOBSIDIAN);
		PALADIUMINFUSEDOBSIDIAN = block(PalamodModBlocks.PALADIUMINFUSEDOBSIDIAN);
		EMPTYSPAWNERITEM = register("emptyspawneritem", EmptyspawneritemItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), properties);
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return doubleBlock(block, new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new DoubleHighBlockItem(block.get(), prop), properties);
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new PaladiumphoneInventoryCapability(stack), PALADIUM_PHONE.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new VoidstoneInventoryCapability(stack), VOIDSTONE.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new MinerjobsitemInventoryCapability(stack), MINERJOBSITEM.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new FarmerjobsitemInventoryCapability(stack), FARMERJOBSITEM.get());
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), FAKE_WATER_BUCKET.get());
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), ANGELIC_WATER_BUCKET.get());
	}

	@EventBusSubscriber(Dist.CLIENT)
	public static class ItemsClientSideHandler {
		@SubscribeEvent
		public static void registerItemModelProperties(RegisterRangeSelectItemModelPropertyEvent event) {
			event.register(ResourceLocation.parse("palamod:xpbottle/xp"), XpbottleItem.XpProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("palamod:xpbottle/jobs_type"), XpbottleItem.JobsTypeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("palamod:emptyspawneritem/souls"), EmptyspawneritemItem.SoulsProperty.MAP_CODEC);
		}
	}
}