/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package palamod.init;

import palamod.block.*;

import palamod.PalamodMod;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

public class PalamodModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(PalamodMod.MODID);
	public static final DeferredBlock<Block> PALADIUM_ORE;
	public static final DeferredBlock<Block> PALADIUM_BLOCK;
	public static final DeferredBlock<Block> TITANE_ORE;
	public static final DeferredBlock<Block> TITANE_BLOCK;
	public static final DeferredBlock<Block> AMETHYST_ORE;
	public static final DeferredBlock<Block> AMETHYST_BLOCK;
	public static final DeferredBlock<Block> PALADIUM_CRUSHER;
	public static final DeferredBlock<Block> ENDIUM_BLOCK;
	public static final DeferredBlock<Block> FINDIUM_ORE;
	public static final DeferredBlock<Block> FINDIUM_BLOCK;
	public static final DeferredBlock<Block> OSTRYA_WOOD_WOOD;
	public static final DeferredBlock<Block> OSTRYA_WOOD_LOG;
	public static final DeferredBlock<Block> OSTRYA_WOOD_PLANKS;
	public static final DeferredBlock<Block> OSTRYA_WOOD_LEAVES;
	public static final DeferredBlock<Block> OSTRYA_WOOD_STAIRS;
	public static final DeferredBlock<Block> OSTRYA_WOOD_SLAB;
	public static final DeferredBlock<Block> OSTRYA_WOOD_FENCE;
	public static final DeferredBlock<Block> OSTRYA_WOOD_FENCE_GATE;
	public static final DeferredBlock<Block> JACARANDA_WOOD;
	public static final DeferredBlock<Block> JACARANDA_LOG;
	public static final DeferredBlock<Block> JACARANDA_PLANKS;
	public static final DeferredBlock<Block> JACARANDA_LEAVES;
	public static final DeferredBlock<Block> JACARANDA_STAIRS;
	public static final DeferredBlock<Block> JACARANDA_SLAB;
	public static final DeferredBlock<Block> JACARANDA_FENCE;
	public static final DeferredBlock<Block> JACARANDA_FENCE_GATE;
	public static final DeferredBlock<Block> NBT_BLOCK;
	public static final DeferredBlock<Block> JUDEECERCIS_WOOD;
	public static final DeferredBlock<Block> JUDEECERCIS_LOG;
	public static final DeferredBlock<Block> JUDEECERCIS_PLANKS;
	public static final DeferredBlock<Block> JUDEECERCIS_LEAVES;
	public static final DeferredBlock<Block> JUDEECERCIS_STAIRS;
	public static final DeferredBlock<Block> JUDEECERCIS_SLAB;
	public static final DeferredBlock<Block> JUDEECERCIS_FENCE;
	public static final DeferredBlock<Block> JUDEECERCIS_FENCE_GATE;
	public static final DeferredBlock<Block> ERABLE_WOOD;
	public static final DeferredBlock<Block> ERABLE_LOG;
	public static final DeferredBlock<Block> ERABLE_PLANKS;
	public static final DeferredBlock<Block> ERABLE_LEAVES;
	public static final DeferredBlock<Block> ERABLE_STAIRS;
	public static final DeferredBlock<Block> ERABLE_SLAB;
	public static final DeferredBlock<Block> ERABLE_FENCE;
	public static final DeferredBlock<Block> ERABLE_FENCE_GATE;
	public static final DeferredBlock<Block> ERABLE_SAPPLING;
	public static final DeferredBlock<Block> JUDEECERCIS_SAPPLING;
	public static final DeferredBlock<Block> OSTRYA_SAPPLING;
	public static final DeferredBlock<Block> JACARANDA_SAPPLING;
	public static final DeferredBlock<Block> FINDIUM_STAIRS;
	public static final DeferredBlock<Block> FINDIUM_SLAB;
	public static final DeferredBlock<Block> XP_BUSH;
	public static final DeferredBlock<Block> XP_BUSH_ON;
	public static final DeferredBlock<Block> SLIMEPAD;
	public static final DeferredBlock<Block> PALADIUM_GREEN_ORE;
	public static final DeferredBlock<Block> PALADIUM_GREEN_BLOCK;
	public static final DeferredBlock<Block> ALCHIMET_1;
	public static final DeferredBlock<Block> GRINDER_CASING;
	public static final DeferredBlock<Block> GRINDER_FRAME;
	public static final DeferredBlock<Block> GRINDER_BLOCK;
	public static final DeferredBlock<Block> PALADIUM_FURNACE;
	public static final DeferredBlock<Block> PALADIUM_FURNACE_ON;
	public static final DeferredBlock<Block> OBSIDIAN_TRAPDOOR;
	public static final DeferredBlock<Block> RENFORCED_OBSIDIAN;
	public static final DeferredBlock<Block> OBSIDIAN_DOOR;
	public static final DeferredBlock<Block> COMPACTED_OBSIDIAN;
	public static final DeferredBlock<Block> FAKE_WATER_OBSIDIAN;
	public static final DeferredBlock<Block> LAVA_OBSIDIAN;
	public static final DeferredBlock<Block> IRON_SPIKE;
	public static final DeferredBlock<Block> SPIKE_GOLD;
	public static final DeferredBlock<Block> DIAMOND_SPIKE;
	public static final DeferredBlock<Block> AMETHYST_SPIKE;
	public static final DeferredBlock<Block> TITANE_SPIKE;
	public static final DeferredBlock<Block> PALADIUM_SPIKE;
	public static final DeferredBlock<Block> PALADIUM_FORGE;
	public static final DeferredBlock<Block> TITANE_SLAB;
	public static final DeferredBlock<Block> TITANE_STAIRS;
	public static final DeferredBlock<Block> LOADBLOCK_1T;
	public static final DeferredBlock<Block> TCV_2;
	public static final DeferredBlock<Block> EGGPLANT_0;
	public static final DeferredBlock<Block> EGGPLANT_1;
	public static final DeferredBlock<Block> EGGPLANT_2;
	public static final DeferredBlock<Block> EGGPLANT_3;
	public static final DeferredBlock<Block> PALADIUM_MACHINE;
	public static final DeferredBlock<Block> LUCKY_BLOCK;
	public static final DeferredBlock<Block> CHERVIL_1;
	public static final DeferredBlock<Block> CHERVIL_0;
	public static final DeferredBlock<Block> CHERVIL_2;
	public static final DeferredBlock<Block> CHERVIL_3;
	public static final DeferredBlock<Block> KIWANO_4;
	public static final DeferredBlock<Block> KIWANO_3;
	public static final DeferredBlock<Block> KIWANO_2;
	public static final DeferredBlock<Block> KIWANO_1;
	public static final DeferredBlock<Block> KIWANO_0;
	public static final DeferredBlock<Block> TRESAURE_FALSE;
	public static final DeferredBlock<Block> TRESAURE_TRUE;
	public static final DeferredBlock<Block> ALARM;
	public static final DeferredBlock<Block> MEGA_SAFE_CHEST;
	public static final DeferredBlock<Block> COLORED_LAMP;
	public static final DeferredBlock<Block> COLOFUL_LAMP;
	public static final DeferredBlock<Block> FAKE_PALADIUM_ORE;
	public static final DeferredBlock<Block> ORANGEBLUE_1;
	public static final DeferredBlock<Block> ORANGEBLUE_0;
	public static final DeferredBlock<Block> ORANGEBLUE_2;
	public static final DeferredBlock<Block> ORANGEBLUE_3;
	public static final DeferredBlock<Block> ORANGEBLUE_4;
	public static final DeferredBlock<Block> TRIXIUM_NBT_BLOCK;
	public static final DeferredBlock<Block> PALADIUM_STAIRS;
	public static final DeferredBlock<Block> PALADIUM_SLAB;
	public static final DeferredBlock<Block> AMETHYST_STAIRS;
	public static final DeferredBlock<Block> AMETHYST_SLAB;
	public static final DeferredBlock<Block> ELEVATOR_WHITE;
	public static final DeferredBlock<Block> ELEVATOR_RED;
	public static final DeferredBlock<Block> ELEVATOR_BLUE;
	public static final DeferredBlock<Block> ELEVATOR_GREEN;
	public static final DeferredBlock<Block> ELEVATOR_PINK;
	public static final DeferredBlock<Block> ELEVATOR_LIGHT_BLUE;
	public static final DeferredBlock<Block> ELEVATOR_LIGHT_GREEN;
	public static final DeferredBlock<Block> ELEVATOR_BROWN;
	public static final DeferredBlock<Block> ELEVATOR_ORANGE;
	public static final DeferredBlock<Block> ELEVATOR_PURPLE;
	public static final DeferredBlock<Block> ELEVATOR_GRAY;
	public static final DeferredBlock<Block> ELEVATOR_LIGHT_GRAY;
	public static final DeferredBlock<Block> ELEVATOR_CYAN;
	public static final DeferredBlock<Block> GUARDIAN_BLOCK;
	public static final DeferredBlock<Block> STONY;
	public static final DeferredBlock<Block> CLOUD_BLOCK;
	public static final DeferredBlock<Block> CROWN;
	public static final DeferredBlock<Block> FACTION_BLOCK;
	public static final DeferredBlock<Block> BLACK_LUCKY_BLOCK;
	public static final DeferredBlock<Block> JUDEECERCIS_DOOR;
	public static final DeferredBlock<Block> ENDIUM_LUCKY_BLOCK;
	public static final DeferredBlock<Block> ENDIUM_NUGGET_ORE;
	public static final DeferredBlock<Block> ENDIUM_SLAB;
	public static final DeferredBlock<Block> ENDIUM_STAIRS;
	public static final DeferredBlock<Block> GREEN_PALADIUM_STAIRS;
	public static final DeferredBlock<Block> GREEN_PALADIUM_SLAB;
	public static final DeferredBlock<Block> UPLOADER;
	public static final DeferredBlock<Block> OSTRYA_DOOR;
	public static final DeferredBlock<Block> ERABLE_DOOR;
	public static final DeferredBlock<Block> JACARANDA_DOOR;
	public static final DeferredBlock<Block> HDV_BLOCK;
	public static final DeferredBlock<Block> ERABLE_TRAPDOOR;
	public static final DeferredBlock<Block> FLATTEN_TITANE_CHEST;
	public static final DeferredBlock<Block> FLATTEN_PALADIUM_CHEST;
	public static final DeferredBlock<Block> FLATTEN_AMETHYST_CHEST;
	public static final DeferredBlock<Block> FLATTEN_GREEN_PALADIUM_CHEST;
	public static final DeferredBlock<Block> FLATTEN_ENDIUM_CHEST;
	public static final DeferredBlock<Block> DOWNLOADER;
	public static final DeferredBlock<Block> ALARM_ON;
	public static final DeferredBlock<Block> DEEPSLATE_AMETHYST_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_TITANE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_PALADIUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_TRIXIUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_GREEN_PALADIUM_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_ENDIUM_NUGGET_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_FINDIUM_ORE;
	public static final DeferredBlock<Block> TRIXIUM_ORE;
	public static final DeferredBlock<Block> TRIXIUM_BLOCK;
	public static final DeferredBlock<Block> CAVE_BLOCK;
	public static final DeferredBlock<Block> PALADIUM_CHEST;
	public static final DeferredBlock<Block> GREEN_PALADIUM_CHEST;
	public static final DeferredBlock<Block> AMETHYST_CHEST;
	public static final DeferredBlock<Block> ENDIUM_CHEST;
	public static final DeferredBlock<Block> TITANE_CHEST;
	public static final DeferredBlock<Block> WOODEN_SPIKE;
	public static final DeferredBlock<Block> WOODEN_OBSIDIAN_SPIKE;
	public static final DeferredBlock<Block> IRON_OBSIDIAN_SPIKE;
	public static final DeferredBlock<Block> GOLDEN_OBSIDIAN_SPIKE;
	public static final DeferredBlock<Block> DIAMOND_OBSIDIAN_SPIKE;
	public static final DeferredBlock<Block> AMETHYST_OBSIDIAN_SPIKE;
	public static final DeferredBlock<Block> TITANE_OBSIDIAN_SPIKE;
	public static final DeferredBlock<Block> PALADIUM_OBSIDIAN_SPIKE;
	public static final DeferredBlock<Block> ONLINE_DETECTOR;
	public static final DeferredBlock<Block> ONLINE_DETECTOR_ON;
	public static final DeferredBlock<Block> COBBLEBREAKER;
	public static final DeferredBlock<Block> FERTILZED_DIRT;
	public static final DeferredBlock<Block> PRINTINGPRESS;
	public static final DeferredBlock<Block> TYPESETTINGTABLE;
	public static final DeferredBlock<Block> DRAWBRIDGE;
	public static final DeferredBlock<Block> UNKNOWNBLOCK;
	public static final DeferredBlock<Block> COMPRESSED_SPONGE;
	public static final DeferredBlock<Block> TNT_SPONGE;
	public static final DeferredBlock<Block> LAVA_SPONGE;
	public static final DeferredBlock<Block> WET_LAVA_SPONGE;
	public static final DeferredBlock<Block> TNT_WITHER;
	public static final DeferredBlock<Block> TNT_MAGIC;
	public static final DeferredBlock<Block> TNT_COMPACT;
	public static final DeferredBlock<Block> TNT_ENDIUM;
	public static final DeferredBlock<Block> RENFORCED_OBSIDIAN_STAIRS;
	public static final DeferredBlock<Block> OBSIDIAN_STAIRS;
	public static final DeferredBlock<Block> OBSIDIAN_SLAB;
	public static final DeferredBlock<Block> HARDENED_OBSIDIAN_SLAB;
	public static final DeferredBlock<Block> FAKE_WATER;
	public static final DeferredBlock<Block> ANGELIC_WATER;
	public static final DeferredBlock<Block> SLIME_OBSIDIAN;
	public static final DeferredBlock<Block> POISON_OBSIDIAN;
	public static final DeferredBlock<Block> EXTRACTOR;
	public static final DeferredBlock<Block> BOOM_OBSIDIAN;
	public static final DeferredBlock<Block> MEGA_BOOM_OBSIDIAN;
	public static final DeferredBlock<Block> HARPAGOPHYTUM;
	public static final DeferredBlock<Block> GLUEBALL_RED;
	public static final DeferredBlock<Block> GREEN_GLUEBALL;
	public static final DeferredBlock<Block> GLUEBALL_LIGHT_GREEN;
	public static final DeferredBlock<Block> GLUEBALL_DARK_GREEN;
	public static final DeferredBlock<Block> GLUEBALL_BLUE;
	public static final DeferredBlock<Block> GLUEBALL_PURPLE;
	public static final DeferredBlock<Block> GLUEBALL_YELLOW;
	public static final DeferredBlock<Block> GLUEBALL_CYAN;
	public static final DeferredBlock<Block> GLUEBALL_ORANGE;
	public static final DeferredBlock<Block> GLUEBALL_GRAY;
	public static final DeferredBlock<Block> SLIMEPAD_RED;
	public static final DeferredBlock<Block> SLIMEPAD_BLUE;
	public static final DeferredBlock<Block> SLIMEPAD_ORANGE;
	public static final DeferredBlock<Block> SLIMEPAD_PURPLE;
	public static final DeferredBlock<Block> TOTEM_FERTILITY;
	public static final DeferredBlock<Block> XP_BUSH_LOW;
	public static final DeferredBlock<Block> ROTATED_PALADIUM_HOPPER;
	public static final DeferredBlock<Block> PALADIUM_HOPPER;
	public static final DeferredBlock<Block> TRIXIUMSLAB;
	public static final DeferredBlock<Block> TRIXIUMSTAIRS;
	public static final DeferredBlock<Block> COBBLEBREAKER_SERVER;
	public static final DeferredBlock<Block> ROTATED_SLIMEPAD;
	public static final DeferredBlock<Block> ROTATED_RED_SLIMEPAD;
	public static final DeferredBlock<Block> ROTATED_PURPLE_SLIMEPAD;
	public static final DeferredBlock<Block> ROTATED_BLUE_SLIMEPAD;
	public static final DeferredBlock<Block> ROTATED_ORANGE_SLIMEPAD;
	public static final DeferredBlock<Block> WITHERED_OBSIDIAN_0;
	public static final DeferredBlock<Block> WITHERED_OBSIDIAN_1;
	public static final DeferredBlock<Block> WITHERED_OBSIDIAN_2;
	public static final DeferredBlock<Block> WITHERED_OBSIDIAN_3;
	public static final DeferredBlock<Block> WITHERED_OBSIDIAN_4;
	public static final DeferredBlock<Block> WITHERED_OBSIDIAN_5;
	public static final DeferredBlock<Block> WITHERED_OBSIDIAN_6;
	public static final DeferredBlock<Block> WITHERED_OBSIDIAN_7;
	public static final DeferredBlock<Block> WITHERED_OBSIDIAN_8;
	public static final DeferredBlock<Block> WITHERED_OBSIDIAN_9;
	public static final DeferredBlock<Block> WITHERED_OBSIDIAN_10;
	public static final DeferredBlock<Block> WITHERED_OBSIDIAN_11;
	public static final DeferredBlock<Block> WITHERED_OBSIDIAN_12;
	public static final DeferredBlock<Block> WITHERED_OBSIDIAN_13;
	public static final DeferredBlock<Block> MINERDIMENSION_PORTAL;
	public static final DeferredBlock<Block> SOFT_STONE;
	public static final DeferredBlock<Block> SOFTENED_AMETHYST_ORE;
	public static final DeferredBlock<Block> SOFTENED_TITANE_ORE;
	public static final DeferredBlock<Block> SOFTENED_PALADIUM_ORE;
	public static final DeferredBlock<Block> SOFTENED_TRIXIUM_ORE;
	public static final DeferredBlock<Block> SOFTENED_GREEN_PALADIUM_ORE;
	public static final DeferredBlock<Block> SOFTENED_FINDIUM_ORE;
	public static final DeferredBlock<Block> SOFTENED_ENDIUM_NUGGET_ORE;
	public static final DeferredBlock<Block> COBBLED_SOFT_STONE;
	public static final DeferredBlock<Block> SOFT_STONE_SLAB;
	public static final DeferredBlock<Block> SOFT_STONE_STAIRS;
	public static final DeferredBlock<Block> COBBLED_SOFT_STONE_SLAB;
	public static final DeferredBlock<Block> COBBLED_SOFT_STONE_STAIRS;
	public static final DeferredBlock<Block> SOFTENED_COAL_ORE;
	public static final DeferredBlock<Block> SOFTENED_IRON_ORE;
	public static final DeferredBlock<Block> SOFTENED_GOLD_ORE;
	public static final DeferredBlock<Block> SOFTENED_DIAMOND_ORE;
	public static final DeferredBlock<Block> SOFTENED_REDSTONE_ORE;
	public static final DeferredBlock<Block> SOFTENED_LAPIS_LAZULIS_ORE;
	public static final DeferredBlock<Block> FLOWER_TOTEM;
	public static final DeferredBlock<Block> MINERAL_FLOWER;
	public static final DeferredBlock<Block> ENDIUM_FLOWER;
	public static final DeferredBlock<Block> ENDIUM_FLOWER_ON;
	public static final DeferredBlock<Block> CLATHRUSARCHERI;
	public static final DeferredBlock<Block> PALADIUM_FLOWER;
	public static final DeferredBlock<Block> DANKABLOCK;
	public static final DeferredBlock<Block> BROKEN_SPAWNER;
	public static final DeferredBlock<Block> SPAWN_CONTROLLER;
	public static final DeferredBlock<Block> EMPTY_SPAWNER;
	public static final DeferredBlock<Block> DIAMOND_INFUSED_OBSIDIAN;
	public static final DeferredBlock<Block> AMETHYST_INFUSED_OBSIDIAN;
	public static final DeferredBlock<Block> TITANE_INFUSED_OBSIDIAN;
	public static final DeferredBlock<Block> PALADIUM_INFUSED_OBSIDIAN;
	public static final DeferredBlock<Block> DEAD_LOG;
	public static final DeferredBlock<Block> DEAD_WOOD;
	public static final DeferredBlock<Block> STRIPPED_DEAD_LOG;
	public static final DeferredBlock<Block> STRIPPED_DEAD_WOOD;
	public static final DeferredBlock<Block> DEAD_PLANKS;
	public static final DeferredBlock<Block> DEAD_STAIRS;
	public static final DeferredBlock<Block> DEAD_SLAB;
	public static final DeferredBlock<Block> DEAD_FENCE;
	public static final DeferredBlock<Block> DEAD_FENCE_GATE;
	public static final DeferredBlock<Block> DEAD_DOOR;
	public static final DeferredBlock<Block> DEAD_TRAPDOOR;
	public static final DeferredBlock<Block> DEAD_PRESSURE_PLATE;
	public static final DeferredBlock<Block> DEAD_BUTTON;
	public static final DeferredBlock<Block> FROZEN_OBSIDIAN;
	public static final DeferredBlock<Block> KNOCKBACK_OBSIDIAN;
	public static final DeferredBlock<Block> AMETHYST_ANVIL;
	public static final DeferredBlock<Block> TITANE_ANVIL;
	public static final DeferredBlock<Block> PALADIUM_ANVIL;
	public static final DeferredBlock<Block> MONEY_ANVIL;
	public static final DeferredBlock<Block> AMETHYSTTANK;
	static {
		PALADIUM_ORE = REGISTRY.register("paladium_ore", PaladiumOreBlock::new);
		PALADIUM_BLOCK = REGISTRY.register("paladium_block", PaladiumBlockBlock::new);
		TITANE_ORE = REGISTRY.register("titane_ore", TitaneOreBlock::new);
		TITANE_BLOCK = REGISTRY.register("titane_block", TitaneBlockBlock::new);
		AMETHYST_ORE = REGISTRY.register("amethyst_ore", AmethysteOreBlock::new);
		AMETHYST_BLOCK = REGISTRY.register("amethyst_block", AmethysteBlockBlock::new);
		PALADIUM_CRUSHER = REGISTRY.register("paladium_crusher", PaladiumcrusherBlock::new);
		ENDIUM_BLOCK = REGISTRY.register("endium_block", EndiumBlockBlock::new);
		FINDIUM_ORE = REGISTRY.register("findium_ore", FindiumOreBlock::new);
		FINDIUM_BLOCK = REGISTRY.register("findium_block", FindiumBlockBlock::new);
		OSTRYA_WOOD_WOOD = REGISTRY.register("ostrya_wood_wood", Ostrya_woodWoodBlock::new);
		OSTRYA_WOOD_LOG = REGISTRY.register("ostrya_wood_log", Ostrya_woodLogBlock::new);
		OSTRYA_WOOD_PLANKS = REGISTRY.register("ostrya_wood_planks", Ostrya_woodPlanksBlock::new);
		OSTRYA_WOOD_LEAVES = REGISTRY.register("ostrya_wood_leaves", Ostrya_woodLeavesBlock::new);
		OSTRYA_WOOD_STAIRS = REGISTRY.register("ostrya_wood_stairs", Ostrya_woodStairsBlock::new);
		OSTRYA_WOOD_SLAB = REGISTRY.register("ostrya_wood_slab", Ostrya_woodSlabBlock::new);
		OSTRYA_WOOD_FENCE = REGISTRY.register("ostrya_wood_fence", Ostrya_woodFenceBlock::new);
		OSTRYA_WOOD_FENCE_GATE = REGISTRY.register("ostrya_wood_fence_gate", Ostrya_woodFenceGateBlock::new);
		JACARANDA_WOOD = REGISTRY.register("jacaranda_wood", Jacaranda_WoodBlock::new);
		JACARANDA_LOG = REGISTRY.register("jacaranda_log", Jacaranda_LogBlock::new);
		JACARANDA_PLANKS = REGISTRY.register("jacaranda_planks", Jacaranda_PlanksBlock::new);
		JACARANDA_LEAVES = REGISTRY.register("jacaranda_leaves", Jacaranda_LeavesBlock::new);
		JACARANDA_STAIRS = REGISTRY.register("jacaranda_stairs", Jacaranda_StairsBlock::new);
		JACARANDA_SLAB = REGISTRY.register("jacaranda_slab", Jacaranda_SlabBlock::new);
		JACARANDA_FENCE = REGISTRY.register("jacaranda_fence", Jacaranda_FenceBlock::new);
		JACARANDA_FENCE_GATE = REGISTRY.register("jacaranda_fence_gate", Jacaranda_FenceGateBlock::new);
		NBT_BLOCK = REGISTRY.register("nbt_block", NbtblockBlock::new);
		JUDEECERCIS_WOOD = REGISTRY.register("judeecercis_wood", Judeecercis_WoodBlock::new);
		JUDEECERCIS_LOG = REGISTRY.register("judeecercis_log", Judeecercis_LogBlock::new);
		JUDEECERCIS_PLANKS = REGISTRY.register("judeecercis_planks", Judeecercis_PlanksBlock::new);
		JUDEECERCIS_LEAVES = REGISTRY.register("judeecercis_leaves", Judeecercis_LeavesBlock::new);
		JUDEECERCIS_STAIRS = REGISTRY.register("judeecercis_stairs", Judeecercis_StairsBlock::new);
		JUDEECERCIS_SLAB = REGISTRY.register("judeecercis_slab", Judeecercis_SlabBlock::new);
		JUDEECERCIS_FENCE = REGISTRY.register("judeecercis_fence", Judeecercis_FenceBlock::new);
		JUDEECERCIS_FENCE_GATE = REGISTRY.register("judeecercis_fence_gate", Judeecercis_FenceGateBlock::new);
		ERABLE_WOOD = REGISTRY.register("erable_wood", Erable_WoodBlock::new);
		ERABLE_LOG = REGISTRY.register("erable_log", Erable_LogBlock::new);
		ERABLE_PLANKS = REGISTRY.register("erable_planks", Erable_PlanksBlock::new);
		ERABLE_LEAVES = REGISTRY.register("erable_leaves", Erable_LeavesBlock::new);
		ERABLE_STAIRS = REGISTRY.register("erable_stairs", Erable_StairsBlock::new);
		ERABLE_SLAB = REGISTRY.register("erable_slab", Erable_SlabBlock::new);
		ERABLE_FENCE = REGISTRY.register("erable_fence", Erable_FenceBlock::new);
		ERABLE_FENCE_GATE = REGISTRY.register("erable_fence_gate", Erable_FenceGateBlock::new);
		ERABLE_SAPPLING = REGISTRY.register("erable_sappling", ErablesapplingBlock::new);
		JUDEECERCIS_SAPPLING = REGISTRY.register("judeecercis_sappling", JudeecercissapplingBlock::new);
		OSTRYA_SAPPLING = REGISTRY.register("ostrya_sappling", OstryasapplingBlock::new);
		JACARANDA_SAPPLING = REGISTRY.register("jacaranda_sappling", JacarandasapplingBlock::new);
		FINDIUM_STAIRS = REGISTRY.register("findium_stairs", FindiumstairsBlock::new);
		FINDIUM_SLAB = REGISTRY.register("findium_slab", FindiumslabBlock::new);
		XP_BUSH = REGISTRY.register("xp_bush", XpbushBlock::new);
		XP_BUSH_ON = REGISTRY.register("xp_bush_on", XpbushonBlock::new);
		SLIMEPAD = REGISTRY.register("slimepad", SlimepadBlock::new);
		PALADIUM_GREEN_ORE = REGISTRY.register("paladium_green_ore", PaladiumGreenoreBlock::new);
		PALADIUM_GREEN_BLOCK = REGISTRY.register("paladium_green_block", PaladiumGreenblockBlock::new);
		ALCHIMET_1 = REGISTRY.register("alchimet_1", Alchimet1Block::new);
		GRINDER_CASING = REGISTRY.register("grinder_casing", GrindercasingBlock::new);
		GRINDER_FRAME = REGISTRY.register("grinder_frame", GrinderframeBlock::new);
		GRINDER_BLOCK = REGISTRY.register("grinder_block", GrinderblockBlock::new);
		PALADIUM_FURNACE = REGISTRY.register("paladium_furnace", PaladiumfurnaceBlock::new);
		PALADIUM_FURNACE_ON = REGISTRY.register("paladium_furnace_on", PaladiumfurnaceonBlock::new);
		OBSIDIAN_TRAPDOOR = REGISTRY.register("obsidian_trapdoor", ObsidiantrapdoorBlock::new);
		RENFORCED_OBSIDIAN = REGISTRY.register("renforced_obsidian", RenforcedobsidianBlock::new);
		OBSIDIAN_DOOR = REGISTRY.register("obsidian_door", ObsidiandoorBlock::new);
		COMPACTED_OBSIDIAN = REGISTRY.register("compacted_obsidian", CompactedobsidianBlock::new);
		FAKE_WATER_OBSIDIAN = REGISTRY.register("fake_water_obsidian", FakewaterobsidianBlock::new);
		LAVA_OBSIDIAN = REGISTRY.register("lava_obsidian", LavaobsidianBlock::new);
		IRON_SPIKE = REGISTRY.register("iron_spike", IronspikeBlock::new);
		SPIKE_GOLD = REGISTRY.register("spike_gold", SpikegoldBlock::new);
		DIAMOND_SPIKE = REGISTRY.register("diamond_spike", DiamondspikeBlock::new);
		AMETHYST_SPIKE = REGISTRY.register("amethyst_spike", AmetystespikeBlock::new);
		TITANE_SPIKE = REGISTRY.register("titane_spike", TitanespikeBlock::new);
		PALADIUM_SPIKE = REGISTRY.register("paladium_spike", PaladiumspikeBlock::new);
		PALADIUM_FORGE = REGISTRY.register("paladium_forge", PaladiumforgeBlock::new);
		TITANE_SLAB = REGISTRY.register("titane_slab", TitaneslabBlock::new);
		TITANE_STAIRS = REGISTRY.register("titane_stairs", TitanestairsBlock::new);
		LOADBLOCK_1T = REGISTRY.register("loadblock_1t", Loadblock1tBlock::new);
		TCV_2 = REGISTRY.register("tcv_2", Tcv2Block::new);
		EGGPLANT_0 = REGISTRY.register("eggplant_0", Eggplant0Block::new);
		EGGPLANT_1 = REGISTRY.register("eggplant_1", Eggplant1Block::new);
		EGGPLANT_2 = REGISTRY.register("eggplant_2", Eggplant2Block::new);
		EGGPLANT_3 = REGISTRY.register("eggplant_3", Eggplant3Block::new);
		PALADIUM_MACHINE = REGISTRY.register("paladium_machine", PaladiummachineBlock::new);
		LUCKY_BLOCK = REGISTRY.register("lucky_block", LuckyblockBlock::new);
		CHERVIL_1 = REGISTRY.register("chervil_1", Chervil1Block::new);
		CHERVIL_0 = REGISTRY.register("chervil_0", Chervil0Block::new);
		CHERVIL_2 = REGISTRY.register("chervil_2", Chervil2Block::new);
		CHERVIL_3 = REGISTRY.register("chervil_3", Chervil3Block::new);
		KIWANO_4 = REGISTRY.register("kiwano_4", Kiwano4Block::new);
		KIWANO_3 = REGISTRY.register("kiwano_3", Kiwano3Block::new);
		KIWANO_2 = REGISTRY.register("kiwano_2", Kiwano2Block::new);
		KIWANO_1 = REGISTRY.register("kiwano_1", Kiwano1Block::new);
		KIWANO_0 = REGISTRY.register("kiwano_0", Kiwano0Block::new);
		TRESAURE_FALSE = REGISTRY.register("tresaure_false", FalsetresureBlock::new);
		TRESAURE_TRUE = REGISTRY.register("tresaure_true", TruetresureBlock::new);
		ALARM = REGISTRY.register("alarm", AlarmBlock::new);
		MEGA_SAFE_CHEST = REGISTRY.register("mega_safe_chest", MegasafechestBlock::new);
		COLORED_LAMP = REGISTRY.register("colored_lamp", ColoredlampBlock::new);
		COLOFUL_LAMP = REGISTRY.register("coloful_lamp", ColofullampBlock::new);
		FAKE_PALADIUM_ORE = REGISTRY.register("fake_paladium_ore", FakepaladiumoreBlock::new);
		ORANGEBLUE_1 = REGISTRY.register("orangeblue_1", Orangeblue1Block::new);
		ORANGEBLUE_0 = REGISTRY.register("orangeblue_0", Orangeblue0Block::new);
		ORANGEBLUE_2 = REGISTRY.register("orangeblue_2", Orangeblue2Block::new);
		ORANGEBLUE_3 = REGISTRY.register("orangeblue_3", Orangeblue3Block::new);
		ORANGEBLUE_4 = REGISTRY.register("orangeblue_4", Orangeblue4Block::new);
		TRIXIUM_NBT_BLOCK = REGISTRY.register("trixium_nbt_block", TrixiumnbtblockBlock::new);
		PALADIUM_STAIRS = REGISTRY.register("paladium_stairs", PaladiumstairsBlock::new);
		PALADIUM_SLAB = REGISTRY.register("paladium_slab", PaladiumslabBlock::new);
		AMETHYST_STAIRS = REGISTRY.register("amethyst_stairs", AmethyststairsBlock::new);
		AMETHYST_SLAB = REGISTRY.register("amethyst_slab", AmethystslabBlock::new);
		ELEVATOR_WHITE = REGISTRY.register("elevator_white", ElevatorwhiteBlock::new);
		ELEVATOR_RED = REGISTRY.register("elevator_red", ElevatorredBlock::new);
		ELEVATOR_BLUE = REGISTRY.register("elevator_blue", ElevatorblueBlock::new);
		ELEVATOR_GREEN = REGISTRY.register("elevator_green", ElevatorgreenBlock::new);
		ELEVATOR_PINK = REGISTRY.register("elevator_pink", ElevatorpinkBlock::new);
		ELEVATOR_LIGHT_BLUE = REGISTRY.register("elevator_light_blue", ElevatorlightblueBlock::new);
		ELEVATOR_LIGHT_GREEN = REGISTRY.register("elevator_light_green", ElevatorlightgreenBlock::new);
		ELEVATOR_BROWN = REGISTRY.register("elevator_brown", ElevatorbrownBlock::new);
		ELEVATOR_ORANGE = REGISTRY.register("elevator_orange", ElevatororangeBlock::new);
		ELEVATOR_PURPLE = REGISTRY.register("elevator_purple", ElevatorpurpleBlock::new);
		ELEVATOR_GRAY = REGISTRY.register("elevator_gray", ElevatorgrayBlock::new);
		ELEVATOR_LIGHT_GRAY = REGISTRY.register("elevator_light_gray", ElevatorlightgrayBlock::new);
		ELEVATOR_CYAN = REGISTRY.register("elevator_cyan", ElevatorcyanBlock::new);
		GUARDIAN_BLOCK = REGISTRY.register("guardian_block", GuardianblockBlock::new);
		STONY = REGISTRY.register("stony", StonyBlock::new);
		CLOUD_BLOCK = REGISTRY.register("cloud_block", CloudblockBlock::new);
		CROWN = REGISTRY.register("crown", CrownBlock::new);
		FACTION_BLOCK = REGISTRY.register("faction_block", FactionblckBlock::new);
		BLACK_LUCKY_BLOCK = REGISTRY.register("black_lucky_block", BlackluckyblockBlock::new);
		JUDEECERCIS_DOOR = REGISTRY.register("judeecercis_door", JudeecercisdoorBlock::new);
		ENDIUM_LUCKY_BLOCK = REGISTRY.register("endium_lucky_block", EndiumluckyblockBlock::new);
		ENDIUM_NUGGET_ORE = REGISTRY.register("endium_nugget_ore", EndiumnuggetoreBlock::new);
		ENDIUM_SLAB = REGISTRY.register("endium_slab", EndiumslabBlock::new);
		ENDIUM_STAIRS = REGISTRY.register("endium_stairs", EndiumstairsBlock::new);
		GREEN_PALADIUM_STAIRS = REGISTRY.register("green_paladium_stairs", GreenpaladiumstairsBlock::new);
		GREEN_PALADIUM_SLAB = REGISTRY.register("green_paladium_slab", GreenpaladiumslabBlock::new);
		UPLOADER = REGISTRY.register("uploader", UploaderBlock::new);
		OSTRYA_DOOR = REGISTRY.register("ostrya_door", OstryadoorBlock::new);
		ERABLE_DOOR = REGISTRY.register("erable_door", ErabledoorBlock::new);
		JACARANDA_DOOR = REGISTRY.register("jacaranda_door", JacarandadoorBlock::new);
		HDV_BLOCK = REGISTRY.register("hdv_block", HdvblockBlock::new);
		ERABLE_TRAPDOOR = REGISTRY.register("erable_trapdoor", ErabletrapdoorBlock::new);
		FLATTEN_TITANE_CHEST = REGISTRY.register("flatten_titane_chest", TitanechestBlock::new);
		FLATTEN_PALADIUM_CHEST = REGISTRY.register("flatten_paladium_chest", PaladiumchestBlock::new);
		FLATTEN_AMETHYST_CHEST = REGISTRY.register("flatten_amethyst_chest", AmethystchestBlock::new);
		FLATTEN_GREEN_PALADIUM_CHEST = REGISTRY.register("flatten_green_paladium_chest", GreenpaladiumchestBlock::new);
		FLATTEN_ENDIUM_CHEST = REGISTRY.register("flatten_endium_chest", EndiumchestBlock::new);
		DOWNLOADER = REGISTRY.register("downloader", DownloaderBlock::new);
		ALARM_ON = REGISTRY.register("alarm_on", AlarmonBlock::new);
		DEEPSLATE_AMETHYST_ORE = REGISTRY.register("deepslate_amethyst_ore", AmethystoredeepslateBlock::new);
		DEEPSLATE_TITANE_ORE = REGISTRY.register("deepslate_titane_ore", TitaneoredeepslateBlock::new);
		DEEPSLATE_PALADIUM_ORE = REGISTRY.register("deepslate_paladium_ore", PaladiumoredeepslateBlock::new);
		DEEPSLATE_TRIXIUM_ORE = REGISTRY.register("deepslate_trixium_ore", TrixiumoredeepslateBlock::new);
		DEEPSLATE_GREEN_PALADIUM_ORE = REGISTRY.register("deepslate_green_paladium_ore", PaladiumgreenoredeepslateBlock::new);
		DEEPSLATE_ENDIUM_NUGGET_ORE = REGISTRY.register("deepslate_endium_nugget_ore", EndiumnuggetoredeepslateBlock::new);
		DEEPSLATE_FINDIUM_ORE = REGISTRY.register("deepslate_findium_ore", FindiumoredeepslateBlock::new);
		TRIXIUM_ORE = REGISTRY.register("trixium_ore", TrixiumoreBlock::new);
		TRIXIUM_BLOCK = REGISTRY.register("trixium_block", TrixiumblockBlock::new);
		CAVE_BLOCK = REGISTRY.register("cave_block", CaveblockBlock::new);
		PALADIUM_CHEST = REGISTRY.register("paladium_chest", Paladiumchestv2Block::new);
		GREEN_PALADIUM_CHEST = REGISTRY.register("green_paladium_chest", Greenpaladiumchestv2Block::new);
		AMETHYST_CHEST = REGISTRY.register("amethyst_chest", Amethystchestv2Block::new);
		ENDIUM_CHEST = REGISTRY.register("endium_chest", Endiumchestv2Block::new);
		TITANE_CHEST = REGISTRY.register("titane_chest", Titanechestv2Block::new);
		WOODEN_SPIKE = REGISTRY.register("wooden_spike", WoddenspikeBlock::new);
		WOODEN_OBSIDIAN_SPIKE = REGISTRY.register("wooden_obsidian_spike", SpikeobsidianwoodBlock::new);
		IRON_OBSIDIAN_SPIKE = REGISTRY.register("iron_obsidian_spike", IronobsidianspikeBlock::new);
		GOLDEN_OBSIDIAN_SPIKE = REGISTRY.register("golden_obsidian_spike", GoldenobsidianspikeBlock::new);
		DIAMOND_OBSIDIAN_SPIKE = REGISTRY.register("diamond_obsidian_spike", DiamondobsidianspikeBlock::new);
		AMETHYST_OBSIDIAN_SPIKE = REGISTRY.register("amethyst_obsidian_spike", AmethystobsidianspikeBlock::new);
		TITANE_OBSIDIAN_SPIKE = REGISTRY.register("titane_obsidian_spike", TitaneobsidianspikeBlock::new);
		PALADIUM_OBSIDIAN_SPIKE = REGISTRY.register("paladium_obsidian_spike", PaladiumobsidianspikeBlock::new);
		ONLINE_DETECTOR = REGISTRY.register("online_detector", OnlinedetectorBlock::new);
		ONLINE_DETECTOR_ON = REGISTRY.register("online_detector_on", OnlinedetectoronBlock::new);
		COBBLEBREAKER = REGISTRY.register("cobblebreaker", CobblebreakerBlock::new);
		FERTILZED_DIRT = REGISTRY.register("fertilzed_dirt", FertilseddirtBlock::new);
		PRINTINGPRESS = REGISTRY.register("printingpress", PrintingpressBlock::new);
		TYPESETTINGTABLE = REGISTRY.register("typesettingtable", TypesettingtableBlock::new);
		DRAWBRIDGE = REGISTRY.register("drawbridge", DrawbridgeBlock::new);
		UNKNOWNBLOCK = REGISTRY.register("unknownblock", UnknownblockBlock::new);
		COMPRESSED_SPONGE = REGISTRY.register("compressed_sponge", CompressedspongeBlock::new);
		TNT_SPONGE = REGISTRY.register("tnt_sponge", SpongetntBlock::new);
		LAVA_SPONGE = REGISTRY.register("lava_sponge", LavaspongeBlock::new);
		WET_LAVA_SPONGE = REGISTRY.register("wet_lava_sponge", WetlavaspongeBlock::new);
		TNT_WITHER = REGISTRY.register("tnt_wither", WithertntBlock::new);
		TNT_MAGIC = REGISTRY.register("tnt_magic", MagictntBlock::new);
		TNT_COMPACT = REGISTRY.register("tnt_compact", CompacttntBlock::new);
		TNT_ENDIUM = REGISTRY.register("tnt_endium", EndiumtntBlock::new);
		RENFORCED_OBSIDIAN_STAIRS = REGISTRY.register("renforced_obsidian_stairs", RenforcedobsidianstairsBlock::new);
		OBSIDIAN_STAIRS = REGISTRY.register("obsidian_stairs", ObsidianstairsBlock::new);
		OBSIDIAN_SLAB = REGISTRY.register("obsidian_slab", ObsidianslabBlock::new);
		HARDENED_OBSIDIAN_SLAB = REGISTRY.register("hardened_obsidian_slab", HardenedobsidianslabBlock::new);
		FAKE_WATER = REGISTRY.register("fake_water", FakewterBlock::new);
		ANGELIC_WATER = REGISTRY.register("angelic_water", AngelicwterBlock::new);
		SLIME_OBSIDIAN = REGISTRY.register("slime_obsidian", SlimeobsidianBlock::new);
		POISON_OBSIDIAN = REGISTRY.register("poison_obsidian", PoisonobsidianBlock::new);
		EXTRACTOR = REGISTRY.register("extractor", ExctractorBlock::new);
		BOOM_OBSIDIAN = REGISTRY.register("boom_obsidian", BoomobsidianBlock::new);
		MEGA_BOOM_OBSIDIAN = REGISTRY.register("mega_boom_obsidian", MegaboomobsidianBlock::new);
		HARPAGOPHYTUM = REGISTRY.register("harpagophytum", HarpagophytumBlock::new);
		GLUEBALL_RED = REGISTRY.register("glueball_red", RedglueballBlock::new);
		GREEN_GLUEBALL = REGISTRY.register("green_glueball", GreenglueballBlock::new);
		GLUEBALL_LIGHT_GREEN = REGISTRY.register("glueball_light_green", LightgreenglueballBlock::new);
		GLUEBALL_DARK_GREEN = REGISTRY.register("glueball_dark_green", DarkgreenglueballBlock::new);
		GLUEBALL_BLUE = REGISTRY.register("glueball_blue", BlueglueballBlock::new);
		GLUEBALL_PURPLE = REGISTRY.register("glueball_purple", PurpleglueballBlock::new);
		GLUEBALL_YELLOW = REGISTRY.register("glueball_yellow", YellowglueballBlock::new);
		GLUEBALL_CYAN = REGISTRY.register("glueball_cyan", CyanglueballBlock::new);
		GLUEBALL_ORANGE = REGISTRY.register("glueball_orange", OrangeglueballBlock::new);
		GLUEBALL_GRAY = REGISTRY.register("glueball_gray", GrayglueballBlock::new);
		SLIMEPAD_RED = REGISTRY.register("slimepad_red", RedslimepadBlock::new);
		SLIMEPAD_BLUE = REGISTRY.register("slimepad_blue", BlueslimepadBlock::new);
		SLIMEPAD_ORANGE = REGISTRY.register("slimepad_orange", OrangeslimepadBlock::new);
		SLIMEPAD_PURPLE = REGISTRY.register("slimepad_purple", PurpleslimepadBlock::new);
		TOTEM_FERTILITY = REGISTRY.register("totem_fertility", TotemfertilityBlock::new);
		XP_BUSH_LOW = REGISTRY.register("xp_bush_low", XpbushlowBlock::new);
		ROTATED_PALADIUM_HOPPER = REGISTRY.register("rotated_paladium_hopper", PaladiumhopperBlock::new);
		PALADIUM_HOPPER = REGISTRY.register("paladium_hopper", PaladiumhoppersouthBlock::new);
		TRIXIUMSLAB = REGISTRY.register("trixiumslab", TrixiumslabBlock::new);
		TRIXIUMSTAIRS = REGISTRY.register("trixiumstairs", TrixiumstairsBlock::new);
		COBBLEBREAKER_SERVER = REGISTRY.register("cobblebreaker_server", CobblebreakerserverBlock::new);
		ROTATED_SLIMEPAD = REGISTRY.register("rotated_slimepad", RotatedslimepadBlock::new);
		ROTATED_RED_SLIMEPAD = REGISTRY.register("rotated_red_slimepad", RotatedredslimepadBlock::new);
		ROTATED_PURPLE_SLIMEPAD = REGISTRY.register("rotated_purple_slimepad", RotatedpurpleslimepadBlock::new);
		ROTATED_BLUE_SLIMEPAD = REGISTRY.register("rotated_blue_slimepad", RotatedblueslimepadBlock::new);
		ROTATED_ORANGE_SLIMEPAD = REGISTRY.register("rotated_orange_slimepad", RotatedorangeslimepadBlock::new);
		WITHERED_OBSIDIAN_0 = REGISTRY.register("withered_obsidian_0", Witheredobsidian0Block::new);
		WITHERED_OBSIDIAN_1 = REGISTRY.register("withered_obsidian_1", Witheredobsidian1Block::new);
		WITHERED_OBSIDIAN_2 = REGISTRY.register("withered_obsidian_2", Witheredobsidian2Block::new);
		WITHERED_OBSIDIAN_3 = REGISTRY.register("withered_obsidian_3", Witheredobsidian3Block::new);
		WITHERED_OBSIDIAN_4 = REGISTRY.register("withered_obsidian_4", Witheredobsidian4Block::new);
		WITHERED_OBSIDIAN_5 = REGISTRY.register("withered_obsidian_5", Witheredobsidian5Block::new);
		WITHERED_OBSIDIAN_6 = REGISTRY.register("withered_obsidian_6", Witheredobsidian6Block::new);
		WITHERED_OBSIDIAN_7 = REGISTRY.register("withered_obsidian_7", Witheredobsidian7Block::new);
		WITHERED_OBSIDIAN_8 = REGISTRY.register("withered_obsidian_8", Witheredobsidian8Block::new);
		WITHERED_OBSIDIAN_9 = REGISTRY.register("withered_obsidian_9", Witheredobsidian9Block::new);
		WITHERED_OBSIDIAN_10 = REGISTRY.register("withered_obsidian_10", Witheredobsidian10Block::new);
		WITHERED_OBSIDIAN_11 = REGISTRY.register("withered_obsidian_11", Witheredobsidian11Block::new);
		WITHERED_OBSIDIAN_12 = REGISTRY.register("withered_obsidian_12", Witheredobsidian12Block::new);
		WITHERED_OBSIDIAN_13 = REGISTRY.register("withered_obsidian_13", Witheredobsidian13Block::new);
		MINERDIMENSION_PORTAL = REGISTRY.register("minerdimension_portal", MinerdimensionPortalBlock::new);
		SOFT_STONE = REGISTRY.register("soft_stone", SoftstoneBlock::new);
		SOFTENED_AMETHYST_ORE = REGISTRY.register("softened_amethyst_ore", SoftenedamethystoreBlock::new);
		SOFTENED_TITANE_ORE = REGISTRY.register("softened_titane_ore", SoftenedtitaneoreBlock::new);
		SOFTENED_PALADIUM_ORE = REGISTRY.register("softened_paladium_ore", SoftenedpaladiumoreBlock::new);
		SOFTENED_TRIXIUM_ORE = REGISTRY.register("softened_trixium_ore", SoftenedtrixiumoreBlock::new);
		SOFTENED_GREEN_PALADIUM_ORE = REGISTRY.register("softened_green_paladium_ore", SoftenedgreenpaladiumoreBlock::new);
		SOFTENED_FINDIUM_ORE = REGISTRY.register("softened_findium_ore", SoftenedfindiumoreBlock::new);
		SOFTENED_ENDIUM_NUGGET_ORE = REGISTRY.register("softened_endium_nugget_ore", SoftenedendiumnuggetoreBlock::new);
		COBBLED_SOFT_STONE = REGISTRY.register("cobbled_soft_stone", CobbleledsoftstoneBlock::new);
		SOFT_STONE_SLAB = REGISTRY.register("soft_stone_slab", SoftstoneslabBlock::new);
		SOFT_STONE_STAIRS = REGISTRY.register("soft_stone_stairs", SoftstonestairsBlock::new);
		COBBLED_SOFT_STONE_SLAB = REGISTRY.register("cobbled_soft_stone_slab", CobbledsoftstoneslabBlock::new);
		COBBLED_SOFT_STONE_STAIRS = REGISTRY.register("cobbled_soft_stone_stairs", CobbledsoftstonestairsBlock::new);
		SOFTENED_COAL_ORE = REGISTRY.register("softened_coal_ore", SoftcoaloreBlock::new);
		SOFTENED_IRON_ORE = REGISTRY.register("softened_iron_ore", SoftenedironoreBlock::new);
		SOFTENED_GOLD_ORE = REGISTRY.register("softened_gold_ore", SoftenedgoldoreBlock::new);
		SOFTENED_DIAMOND_ORE = REGISTRY.register("softened_diamond_ore", SofteneddiamondoreBlock::new);
		SOFTENED_REDSTONE_ORE = REGISTRY.register("softened_redstone_ore", SoftenedredstoneoreBlock::new);
		SOFTENED_LAPIS_LAZULIS_ORE = REGISTRY.register("softened_lapis_lazulis_ore", SoftenedlapislazulisoreBlock::new);
		FLOWER_TOTEM = REGISTRY.register("flower_totem", FlowertotemBlock::new);
		MINERAL_FLOWER = REGISTRY.register("mineral_flower", MineralflowerBlock::new);
		ENDIUM_FLOWER = REGISTRY.register("endium_flower", EndiumflowerBlock::new);
		ENDIUM_FLOWER_ON = REGISTRY.register("endium_flower_on", EndiumfloweronBlock::new);
		CLATHRUSARCHERI = REGISTRY.register("clathrusarcheri", ClathrusarcheriBlock::new);
		PALADIUM_FLOWER = REGISTRY.register("paladium_flower", PaladiumflowerBlock::new);
		DANKABLOCK = REGISTRY.register("dankablock", DankablockBlock::new);
		BROKEN_SPAWNER = REGISTRY.register("broken_spawner", BrokenspawnerBlock::new);
		SPAWN_CONTROLLER = REGISTRY.register("spawn_controller", SpawncontrollerBlock::new);
		EMPTY_SPAWNER = REGISTRY.register("empty_spawner", EmptyspawnerBlock::new);
		DIAMOND_INFUSED_OBSIDIAN = REGISTRY.register("diamond_infused_obsidian", DiamondinfusedobsidianBlock::new);
		AMETHYST_INFUSED_OBSIDIAN = REGISTRY.register("amethyst_infused_obsidian", AmethystinfusedobsidianBlock::new);
		TITANE_INFUSED_OBSIDIAN = REGISTRY.register("titane_infused_obsidian", TitaneinfusedobsidianBlock::new);
		PALADIUM_INFUSED_OBSIDIAN = REGISTRY.register("paladium_infused_obsidian", PaladiuminfusedobsidianBlock::new);
		DEAD_LOG = REGISTRY.register("dead_log", DeadLogBlock::new);
		DEAD_WOOD = REGISTRY.register("dead_wood", DeadWoodBlock::new);
		STRIPPED_DEAD_LOG = REGISTRY.register("stripped_dead_log", StrippedDeadLogBlock::new);
		STRIPPED_DEAD_WOOD = REGISTRY.register("stripped_dead_wood", StrippedDeadWoodBlock::new);
		DEAD_PLANKS = REGISTRY.register("dead_planks", DeadPlanksBlock::new);
		DEAD_STAIRS = REGISTRY.register("dead_stairs", DeadStairsBlock::new);
		DEAD_SLAB = REGISTRY.register("dead_slab", DeadSlabBlock::new);
		DEAD_FENCE = REGISTRY.register("dead_fence", DeadFenceBlock::new);
		DEAD_FENCE_GATE = REGISTRY.register("dead_fence_gate", DeadFenceGateBlock::new);
		DEAD_DOOR = REGISTRY.register("dead_door", DeadDoorBlock::new);
		DEAD_TRAPDOOR = REGISTRY.register("dead_trapdoor", DeadTrapdoorBlock::new);
		DEAD_PRESSURE_PLATE = REGISTRY.register("dead_pressure_plate", DeadPressurePlateBlock::new);
		DEAD_BUTTON = REGISTRY.register("dead_button", DeadButtonBlock::new);
		FROZEN_OBSIDIAN = REGISTRY.register("frozen_obsidian", FrozenobsidianBlock::new);
		KNOCKBACK_OBSIDIAN = REGISTRY.register("knockback_obsidian", KnockbackobsidianBlock::new);
		AMETHYST_ANVIL = REGISTRY.register("amethyst_anvil", AmethystanvilBlock::new);
		TITANE_ANVIL = REGISTRY.register("titane_anvil", TitaneanvilBlock::new);
		PALADIUM_ANVIL = REGISTRY.register("paladium_anvil", PaladiumanvilBlock::new);
		MONEY_ANVIL = REGISTRY.register("money_anvil", MoneyanvilBlock::new);
		AMETHYSTTANK = REGISTRY.register("amethysttank", AmethysttankBlock::new);
	}
	// Start of user code block custom blocks
	// End of user code block custom blocks
}