
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package palamod.init;

import palamod.procedures.GetxpfrombottleProcedure;
import palamod.procedures.GetjobsfrombottleProcedure;

import palamod.item.XpbottleItem;
import palamod.item.XpberryItem;
import palamod.item.X10xppotionItem;
import palamod.item.WithershardItem;
import palamod.item.WitherimbuepotionItem;
import palamod.item.WingItem;
import palamod.item.WeightedItem;
import palamod.item.VoidstoneItem;
import palamod.item.TrixiumItem;
import palamod.item.TravelarmorItem;
import palamod.item.TitanestickItem;
import palamod.item.TitaneseedplanterItem;
import palamod.item.TitanepollenItem;
import palamod.item.TitaneparticleItem;
import palamod.item.TitanemixedcoalItem;
import palamod.item.TitanehoeItem;
import palamod.item.TitanehammerItem;
import palamod.item.TitanefastswordItem;
import palamod.item.TitaneexcavatorItem;
import palamod.item.TitanebroadswordItem;
import palamod.item.TitaneSwordItem;
import palamod.item.TitaneShovelItem;
import palamod.item.TitanePickaxeItem;
import palamod.item.TitaneIngotItem;
import palamod.item.TitaneAxeItem;
import palamod.item.TitaneArmorItem;
import palamod.item.SwordpaternItem;
import palamod.item.SwordheadItem;
import palamod.item.StrenghtstickItem;
import palamod.item.StrenghorbItem;
import palamod.item.StickofgodsItem;
import palamod.item.SpeedstickItem;
import palamod.item.SpeedorbItem;
import palamod.item.SpeedmodifierItem;
import palamod.item.SpacefoodItem;
import palamod.item.SocketpaternItem;
import palamod.item.SmeltmodifierItem;
import palamod.item.SmallringgreenpaladiumItem;
import palamod.item.SmallringItem;
import palamod.item.ShovelpaternItem;
import palamod.item.ShovelheadItem;
import palamod.item.SealedxpbottleItem;
import palamod.item.ScubaItem;
import palamod.item.RoulettepaladiennediscItem;
import palamod.item.RanbowarmorItem;
import palamod.item.PotatobackpackItem;
import palamod.item.PoisonimbuepotionItem;
import palamod.item.PlateItem;
import palamod.item.PickaxepaternItem;
import palamod.item.Pickaxeofthegodslv9Item;
import palamod.item.Pickaxeofthegodslv8Item;
import palamod.item.Pickaxeofthegodslv7Item;
import palamod.item.Pickaxeofthegodslv6Item;
import palamod.item.Pickaxeofthegodslv5Item;
import palamod.item.Pickaxeofthegodslv4Item;
import palamod.item.Pickaxeofthegodslv3Item;
import palamod.item.Pickaxeofthegodslv2Item;
import palamod.item.Pickaxeofthegodslv20Item;
import palamod.item.Pickaxeofthegodslv1Item;
import palamod.item.Pickaxeofthegodslv19Item;
import palamod.item.Pickaxeofthegodslv18Item;
import palamod.item.Pickaxeofthegodslv17Item;
import palamod.item.Pickaxeofthegodslv16Item;
import palamod.item.Pickaxeofthegodslv15Item;
import palamod.item.Pickaxeofthegodslv14Item;
import palamod.item.Pickaxeofthegodslv13Item;
import palamod.item.Pickaxeofthegodslv12Item;
import palamod.item.Pickaxeofthegodslv11Item;
import palamod.item.Pickaxeofthegodslv10Item;
import palamod.item.PickaxeheadItem;
import palamod.item.PesyblpotionItem;
import palamod.item.PalamixedcharoalItem;
import palamod.item.PaladiumstickItem;
import palamod.item.PaladiumseedplanterItem;
import palamod.item.PaladiumpollenItem;
import palamod.item.PaladiumphoneItem;
import palamod.item.PaladiumparticleItem;
import palamod.item.PaladiumhoeItem;
import palamod.item.PaladiumhammerItem;
import palamod.item.PaladiumgreenswordItem;
import palamod.item.PaladiumgreenshovelItem;
import palamod.item.PaladiumgreenpickaxeItem;
import palamod.item.PaladiumgreenaxeItem;
import palamod.item.PaladiumfastswordItem;
import palamod.item.PaladiumexcavatorItem;
import palamod.item.PaladiumcoreItem;
import palamod.item.PaladiumbroadswordItem;
import palamod.item.Paladiumarmorcustom9Item;
import palamod.item.Paladiumarmorcustom8Item;
import palamod.item.Paladiumarmorcustom7Item;
import palamod.item.Paladiumarmorcustom6Item;
import palamod.item.Paladiumarmorcustom5Item;
import palamod.item.Paladiumarmorcustom4Item;
import palamod.item.Paladiumarmorcustom3Item;
import palamod.item.Paladiumarmorcustom2Item;
import palamod.item.Paladiumarmorcustom1Item;
import palamod.item.Paladiumarmorcustom10Item;
import palamod.item.PaladiumappleItem;
import palamod.item.PaladiumSwordItem;
import palamod.item.PaladiumShovelItem;
import palamod.item.PaladiumPickaxeItem;
import palamod.item.PaladiumIngotItem;
import palamod.item.PaladiumGreeningotItem;
import palamod.item.PaladiumAxeItem;
import palamod.item.PaladiumArmorItem;
import palamod.item.OrangeblueseedItem;
import palamod.item.OrangeblueItem;
import palamod.item.OnemoremodifierItem;
import palamod.item.ObsidianpickaxeItem;
import palamod.item.MoulastoneItem;
import palamod.item.MoneyotherItem;
import palamod.item.MoneyitemItem;
import palamod.item.Moneye1k1Item;
import palamod.item.MixedendiumingotItem;
import palamod.item.MixedendiumarmorItem;
import palamod.item.MinagevoidstoneItem;
import palamod.item.MiichalengeItem;
import palamod.item.MediumringgreenpaladiumItem;
import palamod.item.MediumringItem;
import palamod.item.MagicaltoolItem;
import palamod.item.LuckybetaItem;
import palamod.item.LegendarystoneteleportationItem;
import palamod.item.LegendarystonerandomItem;
import palamod.item.LegendarystonepowerItem;
import palamod.item.LegendarystonejobsItem;
import palamod.item.LegendarystoneinvisibleItem;
import palamod.item.LegendarystonefortuneItem;
import palamod.item.KnockbackorbItem;
import palamod.item.KnockbackmodifierItem;
import palamod.item.KiwanoseedItem;
import palamod.item.KiwanoItem;
import palamod.item.JumpstickItem;
import palamod.item.JumporbItem;
import palamod.item.IronparticleItem;
import palamod.item.InvisiblearmorItem;
import palamod.item.InternetcardItem;
import palamod.item.IngotpaternItem;
import palamod.item.InfernalknockerItem;
import palamod.item.HyperjumpstickItem;
import palamod.item.HealstickItem;
import palamod.item.HealorbItem;
import palamod.item.HeadgreenswordItem;
import palamod.item.HeadgreenshovelItem;
import palamod.item.HeadgreenpickaxeItem;
import palamod.item.HeadgreenbroadswordItem;
import palamod.item.HeadgreenaxeItem;
import palamod.item.HeadendiumswordItem;
import palamod.item.HeadendiumpickaxeItem;
import palamod.item.HeadendiumaxeItem;
import palamod.item.HanggliderItem;
import palamod.item.HammerpaternItem;
import palamod.item.HammerheadItem;
import palamod.item.GuardianstoneItem;
import palamod.item.GreenpaladumexcatorItem;
import palamod.item.GreenpaladiumseedplanterItem;
import palamod.item.GreenpaladiumparticleItem;
import palamod.item.GreenpaladiumhoeItem;
import palamod.item.GreenpaladiumhammerheadItem;
import palamod.item.GreenpaladiumhammerItem;
import palamod.item.GreenpaladiumfastswordheadItem;
import palamod.item.GreenpaladiumfastswordItem;
import palamod.item.GreenpaladiumbroadswordItem;
import palamod.item.GreenpaladiumarmorItem;
import palamod.item.GoldparticleItem;
import palamod.item.GoldmixedcoalItem;
import palamod.item.FuzediscItem;
import palamod.item.FurnaceupgradeItem;
import palamod.item.ForturnemodifierItem;
import palamod.item.FlypotionItem;
import palamod.item.FlatchestupgradeItem;
import palamod.item.FlamemodifierItem;
import palamod.item.FireimbuepotionItem;
import palamod.item.FindiumItem;
import palamod.item.FastswordpaternItem;
import palamod.item.FastswordheadItem;
import palamod.item.FakewterItem;
import palamod.item.EnfyupotionItem;
import palamod.item.EndiumsmallringItem;
import palamod.item.EndiumshovelheadItem;
import palamod.item.EndiumshovelItem;
import palamod.item.EndiumseedplanterItem;
import palamod.item.EndiumpollenItem;
import palamod.item.EndiumnuggetItem;
import palamod.item.EndiummediumringItem;
import palamod.item.EndiumhoeItem;
import palamod.item.EndiumhammerheadItem;
import palamod.item.EndiumhammerItem;
import palamod.item.EndiumfragmentItem;
import palamod.item.EndiumfastswordheadItem;
import palamod.item.EndiumfastswordItem;
import palamod.item.EndiumdynaItem;
import palamod.item.EndiumbroadswordheadItem;
import palamod.item.EndiumbroadswordItem;
import palamod.item.EndiumbigringItem;
import palamod.item.EndiumSwordItem;
import palamod.item.EndiumPickaxeItem;
import palamod.item.EndiumIngotItem;
import palamod.item.EndiumAxeItem;
import palamod.item.EndiumArmorItem;
import palamod.item.EggplantseedItem;
import palamod.item.EggplantItem;
import palamod.item.DynamiteItem;
import palamod.item.DoubleexppotionItem;
import palamod.item.DiamondstringItem;
import palamod.item.DiamondparticleItem;
import palamod.item.DamagestickItem;
import palamod.item.CreativetrixiumswordItem;
import palamod.item.CreativepotgItem;
import palamod.item.CreativehammerItem;
import palamod.item.CompressedxpberryItem;
import palamod.item.CompressedtitaneItem;
import palamod.item.CompressedpaladiumItem;
import palamod.item.CompressedgreenpaladumItem;
import palamod.item.CompressedamethysteItem;
import palamod.item.CobblebreakertitaneupgradeItem;
import palamod.item.CobblebreakerpaladiumupgradeItem;
import palamod.item.CobblebreakeramethystupgradeItem;
import palamod.item.ClashkumizItem;
import palamod.item.ChunkanaslyserItem;
import palamod.item.ChervilseedItem;
import palamod.item.ChervilItem;
import palamod.item.BroadswordpaternItem;
import palamod.item.BroadswordheadItem;
import palamod.item.BlockpaternItem;
import palamod.item.BigringgreenpaladiumItem;
import palamod.item.BigringItem;
import palamod.item.BigholeupgradeItem;
import palamod.item.BigdynamiteItem;
import palamod.item.AxeparternItem;
import palamod.item.AxeheadItem;
import palamod.item.AutosmeltupgradepotgItem;
import palamod.item.AntifuzediscItem;
import palamod.item.AngelicwterItem;
import palamod.item.AmethytestickItem;
import palamod.item.AmethystseedplanterItem;
import palamod.item.AmethystpollenItem;
import palamod.item.AmethystparticleItem;
import palamod.item.AmethystmixedcoalItem;
import palamod.item.AmethystexacvatorItem;
import palamod.item.AmethystehammerItem;
import palamod.item.AmethystefastswordItem;
import palamod.item.AmethystebroadswordItem;
import palamod.item.AmethysteSwordItem;
import palamod.item.AmethysteShovelItem;
import palamod.item.AmethystePickaxeItem;
import palamod.item.AmethysteItem;
import palamod.item.AmethysteAxeItem;
import palamod.item.AmethysteArmorItem;
import palamod.item.AmethtysthoeItem;

import palamod.PalamodMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class PalamodModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, PalamodMod.MODID);
	public static final RegistryObject<Item> PALADIUM_INGOT = REGISTRY.register("paladium_ingot", () -> new PaladiumIngotItem());
	public static final RegistryObject<Item> PALADIUM_ORE = block(PalamodModBlocks.PALADIUM_ORE);
	public static final RegistryObject<Item> PALADIUM_BLOCK = block(PalamodModBlocks.PALADIUM_BLOCK);
	public static final RegistryObject<Item> PALADIUM_PICKAXE = REGISTRY.register("paladium_pickaxe", () -> new PaladiumPickaxeItem());
	public static final RegistryObject<Item> PALADIUM_AXE = REGISTRY.register("paladium_axe", () -> new PaladiumAxeItem());
	public static final RegistryObject<Item> PALADIUM_SWORD = REGISTRY.register("paladium_sword", () -> new PaladiumSwordItem());
	public static final RegistryObject<Item> PALADIUM_SHOVEL = REGISTRY.register("paladium_shovel", () -> new PaladiumShovelItem());
	public static final RegistryObject<Item> PALADIUM_ARMOR_HELMET = REGISTRY.register("paladium_armor_helmet", () -> new PaladiumArmorItem.Helmet());
	public static final RegistryObject<Item> PALADIUM_ARMOR_CHESTPLATE = REGISTRY.register("paladium_armor_chestplate", () -> new PaladiumArmorItem.Chestplate());
	public static final RegistryObject<Item> PALADIUM_ARMOR_LEGGINGS = REGISTRY.register("paladium_armor_leggings", () -> new PaladiumArmorItem.Leggings());
	public static final RegistryObject<Item> PALADIUM_ARMOR_BOOTS = REGISTRY.register("paladium_armor_boots", () -> new PaladiumArmorItem.Boots());
	public static final RegistryObject<Item> TITANE_INGOT = REGISTRY.register("titane_ingot", () -> new TitaneIngotItem());
	public static final RegistryObject<Item> TITANE_ORE = block(PalamodModBlocks.TITANE_ORE);
	public static final RegistryObject<Item> TITANE_BLOCK = block(PalamodModBlocks.TITANE_BLOCK);
	public static final RegistryObject<Item> TITANE_PICKAXE = REGISTRY.register("titane_pickaxe", () -> new TitanePickaxeItem());
	public static final RegistryObject<Item> TITANE_AXE = REGISTRY.register("titane_axe", () -> new TitaneAxeItem());
	public static final RegistryObject<Item> TITANE_SWORD = REGISTRY.register("titane_sword", () -> new TitaneSwordItem());
	public static final RegistryObject<Item> TITANE_SHOVEL = REGISTRY.register("titane_shovel", () -> new TitaneShovelItem());
	public static final RegistryObject<Item> TITANE_ARMOR_HELMET = REGISTRY.register("titane_armor_helmet", () -> new TitaneArmorItem.Helmet());
	public static final RegistryObject<Item> TITANE_ARMOR_CHESTPLATE = REGISTRY.register("titane_armor_chestplate", () -> new TitaneArmorItem.Chestplate());
	public static final RegistryObject<Item> TITANE_ARMOR_LEGGINGS = REGISTRY.register("titane_armor_leggings", () -> new TitaneArmorItem.Leggings());
	public static final RegistryObject<Item> TITANE_ARMOR_BOOTS = REGISTRY.register("titane_armor_boots", () -> new TitaneArmorItem.Boots());
	public static final RegistryObject<Item> AMETHYST = REGISTRY.register("amethyst", () -> new AmethysteItem());
	public static final RegistryObject<Item> AMETHYST_ORE = block(PalamodModBlocks.AMETHYST_ORE);
	public static final RegistryObject<Item> AMETHYST_BLOCK = block(PalamodModBlocks.AMETHYST_BLOCK);
	public static final RegistryObject<Item> AMETHYST_PICKAXE = REGISTRY.register("amethyst_pickaxe", () -> new AmethystePickaxeItem());
	public static final RegistryObject<Item> AMETHYST_AXE = REGISTRY.register("amethyst_axe", () -> new AmethysteAxeItem());
	public static final RegistryObject<Item> AMETHYST_SWORD = REGISTRY.register("amethyst_sword", () -> new AmethysteSwordItem());
	public static final RegistryObject<Item> AMETHYST_SHOVEL = REGISTRY.register("amethyst_shovel", () -> new AmethysteShovelItem());
	public static final RegistryObject<Item> AMETHYST_ARMOR_HELMET = REGISTRY.register("amethyst_armor_helmet", () -> new AmethysteArmorItem.Helmet());
	public static final RegistryObject<Item> AMETHYST_ARMOR_CHESTPLATE = REGISTRY.register("amethyst_armor_chestplate", () -> new AmethysteArmorItem.Chestplate());
	public static final RegistryObject<Item> AMETHYST_ARMOR_LEGGINGS = REGISTRY.register("amethyst_armor_leggings", () -> new AmethysteArmorItem.Leggings());
	public static final RegistryObject<Item> AMETHYST_ARMOR_BOOTS = REGISTRY.register("amethyst_armor_boots", () -> new AmethysteArmorItem.Boots());
	public static final RegistryObject<Item> PALADIUM_CRUSHER = block(PalamodModBlocks.PALADIUM_CRUSHER);
	public static final RegistryObject<Item> PALADIUM_MIXED_CHARCOAL = REGISTRY.register("paladium_mixed_charcoal", () -> new PalamixedcharoalItem());
	public static final RegistryObject<Item> EGGPLANT = REGISTRY.register("eggplant", () -> new EggplantItem());
	public static final RegistryObject<Item> ORANGEBLUE = REGISTRY.register("orangeblue", () -> new OrangeblueItem());
	public static final RegistryObject<Item> KIWANO = REGISTRY.register("kiwano", () -> new KiwanoItem());
	public static final RegistryObject<Item> CHERVIL = REGISTRY.register("chervil", () -> new ChervilItem());
	public static final RegistryObject<Item> ENDIUM_INGOT = REGISTRY.register("endium_ingot", () -> new EndiumIngotItem());
	public static final RegistryObject<Item> ENDIUM_BLOCK = block(PalamodModBlocks.ENDIUM_BLOCK);
	public static final RegistryObject<Item> ENDIUM_PICKAXE = REGISTRY.register("endium_pickaxe", () -> new EndiumPickaxeItem());
	public static final RegistryObject<Item> ENDIUM_AXE = REGISTRY.register("endium_axe", () -> new EndiumAxeItem());
	public static final RegistryObject<Item> ENDIUM_SWORD = REGISTRY.register("endium_sword", () -> new EndiumSwordItem());
	public static final RegistryObject<Item> ENDIUM_ARMOR_HELMET = REGISTRY.register("endium_armor_helmet", () -> new EndiumArmorItem.Helmet());
	public static final RegistryObject<Item> ENDIUM_ARMOR_CHESTPLATE = REGISTRY.register("endium_armor_chestplate", () -> new EndiumArmorItem.Chestplate());
	public static final RegistryObject<Item> ENDIUM_ARMOR_LEGGINGS = REGISTRY.register("endium_armor_leggings", () -> new EndiumArmorItem.Leggings());
	public static final RegistryObject<Item> ENDIUM_ARMOR_BOOTS = REGISTRY.register("endium_armor_boots", () -> new EndiumArmorItem.Boots());
	public static final RegistryObject<Item> ENDIUM_NUGGET = REGISTRY.register("endium_nugget", () -> new EndiumnuggetItem());
	public static final RegistryObject<Item> PALADIUM_STICK = REGISTRY.register("paladium_stick", () -> new PaladiumstickItem());
	public static final RegistryObject<Item> TITANE_STICK = REGISTRY.register("titane_stick", () -> new TitanestickItem());
	public static final RegistryObject<Item> AMETHYST_STICK = REGISTRY.register("amethyst_stick", () -> new AmethytestickItem());
	public static final RegistryObject<Item> COMPRESSED_AMETHYST = REGISTRY.register("compressed_amethyst", () -> new CompressedamethysteItem());
	public static final RegistryObject<Item> COMPRESSED_TITANE = REGISTRY.register("compressed_titane", () -> new CompressedtitaneItem());
	public static final RegistryObject<Item> COMPRESSED_PALADIUM = REGISTRY.register("compressed_paladium", () -> new CompressedpaladiumItem());
	public static final RegistryObject<Item> FINDIUM = REGISTRY.register("findium", () -> new FindiumItem());
	public static final RegistryObject<Item> FINDIUM_ORE = block(PalamodModBlocks.FINDIUM_ORE);
	public static final RegistryObject<Item> FINDIUM_BLOCK = block(PalamodModBlocks.FINDIUM_BLOCK);
	public static final RegistryObject<Item> OSTRYA_WOOD_WOOD = block(PalamodModBlocks.OSTRYA_WOOD_WOOD);
	public static final RegistryObject<Item> OSTRYA_WOOD_LOG = block(PalamodModBlocks.OSTRYA_WOOD_LOG);
	public static final RegistryObject<Item> OSTRYA_WOOD_PLANKS = block(PalamodModBlocks.OSTRYA_WOOD_PLANKS);
	public static final RegistryObject<Item> OSTRYA_WOOD_LEAVES = block(PalamodModBlocks.OSTRYA_WOOD_LEAVES);
	public static final RegistryObject<Item> OSTRYA_WOOD_STAIRS = block(PalamodModBlocks.OSTRYA_WOOD_STAIRS);
	public static final RegistryObject<Item> OSTRYA_WOOD_SLAB = block(PalamodModBlocks.OSTRYA_WOOD_SLAB);
	public static final RegistryObject<Item> OSTRYA_WOOD_FENCE = block(PalamodModBlocks.OSTRYA_WOOD_FENCE);
	public static final RegistryObject<Item> OSTRYA_WOOD_FENCE_GATE = block(PalamodModBlocks.OSTRYA_WOOD_FENCE_GATE);
	public static final RegistryObject<Item> JACARANDA_WOOD = block(PalamodModBlocks.JACARANDA_WOOD);
	public static final RegistryObject<Item> JACARANDA_LOG = block(PalamodModBlocks.JACARANDA_LOG);
	public static final RegistryObject<Item> JACARANDA_PLANKS = block(PalamodModBlocks.JACARANDA_PLANKS);
	public static final RegistryObject<Item> JACARANDA_LEAVES = block(PalamodModBlocks.JACARANDA_LEAVES);
	public static final RegistryObject<Item> JACARANDA_STAIRS = block(PalamodModBlocks.JACARANDA_STAIRS);
	public static final RegistryObject<Item> JACARANDA_SLAB = block(PalamodModBlocks.JACARANDA_SLAB);
	public static final RegistryObject<Item> JACARANDA_FENCE = block(PalamodModBlocks.JACARANDA_FENCE);
	public static final RegistryObject<Item> JACARANDA_FENCE_GATE = block(PalamodModBlocks.JACARANDA_FENCE_GATE);
	public static final RegistryObject<Item> NBT_BLOCK = block(PalamodModBlocks.NBT_BLOCK);
	public static final RegistryObject<Item> JUDEECERCIS_WOOD = block(PalamodModBlocks.JUDEECERCIS_WOOD);
	public static final RegistryObject<Item> JUDEECERCIS_LOG = block(PalamodModBlocks.JUDEECERCIS_LOG);
	public static final RegistryObject<Item> JUDEECERCIS_PLANKS = block(PalamodModBlocks.JUDEECERCIS_PLANKS);
	public static final RegistryObject<Item> JUDEECERCIS_LEAVES = block(PalamodModBlocks.JUDEECERCIS_LEAVES);
	public static final RegistryObject<Item> JUDEECERCIS_STAIRS = block(PalamodModBlocks.JUDEECERCIS_STAIRS);
	public static final RegistryObject<Item> JUDEECERCIS_SLAB = block(PalamodModBlocks.JUDEECERCIS_SLAB);
	public static final RegistryObject<Item> JUDEECERCIS_FENCE = block(PalamodModBlocks.JUDEECERCIS_FENCE);
	public static final RegistryObject<Item> JUDEECERCIS_FENCE_GATE = block(PalamodModBlocks.JUDEECERCIS_FENCE_GATE);
	public static final RegistryObject<Item> ERABLE_WOOD = block(PalamodModBlocks.ERABLE_WOOD);
	public static final RegistryObject<Item> ERABLE_LOG = block(PalamodModBlocks.ERABLE_LOG);
	public static final RegistryObject<Item> ERABLE_PLANKS = block(PalamodModBlocks.ERABLE_PLANKS);
	public static final RegistryObject<Item> ERABLE_LEAVES = block(PalamodModBlocks.ERABLE_LEAVES);
	public static final RegistryObject<Item> ERABLE_STAIRS = block(PalamodModBlocks.ERABLE_STAIRS);
	public static final RegistryObject<Item> ERABLE_SLAB = block(PalamodModBlocks.ERABLE_SLAB);
	public static final RegistryObject<Item> ERABLE_FENCE = block(PalamodModBlocks.ERABLE_FENCE);
	public static final RegistryObject<Item> ERABLE_FENCE_GATE = block(PalamodModBlocks.ERABLE_FENCE_GATE);
	public static final RegistryObject<Item> ERABLE_SAPPLING = block(PalamodModBlocks.ERABLE_SAPPLING);
	public static final RegistryObject<Item> JUDEECERCIS_SAPPLING = block(PalamodModBlocks.JUDEECERCIS_SAPPLING);
	public static final RegistryObject<Item> OSTRYA_SAPPLING = block(PalamodModBlocks.OSTRYA_SAPPLING);
	public static final RegistryObject<Item> JACARANDA_SAPPLING = block(PalamodModBlocks.JACARANDA_SAPPLING);
	public static final RegistryObject<Item> KIWANOSEED = REGISTRY.register("kiwanoseed", () -> new KiwanoseedItem());
	public static final RegistryObject<Item> ORANGEBLUESEED = REGISTRY.register("orangeblueseed", () -> new OrangeblueseedItem());
	public static final RegistryObject<Item> CHERVILSEED = REGISTRY.register("chervilseed", () -> new ChervilseedItem());
	public static final RegistryObject<Item> EGGPLANT_SEED = REGISTRY.register("eggplant_seed", () -> new EggplantseedItem());
	public static final RegistryObject<Item> FINDIUM_STAIRS = block(PalamodModBlocks.FINDIUM_STAIRS);
	public static final RegistryObject<Item> FINDIUM_SLAB = block(PalamodModBlocks.FINDIUM_SLAB);
	public static final RegistryObject<Item> XPBUSH = block(PalamodModBlocks.XPBUSH);
	public static final RegistryObject<Item> XPBUSHON = block(PalamodModBlocks.XPBUSHON);
	public static final RegistryObject<Item> XPBERRY = REGISTRY.register("xpberry", () -> new XpberryItem());
	public static final RegistryObject<Item> COMPRESSEDXPBERRY = REGISTRY.register("compressedxpberry", () -> new CompressedxpberryItem());
	public static final RegistryObject<Item> PALADIUM_CORE = REGISTRY.register("paladium_core", () -> new PaladiumcoreItem());
	public static final RegistryObject<Item> SLIMEPAD = block(PalamodModBlocks.SLIMEPAD);
	public static final RegistryObject<Item> HEAL_ORB = REGISTRY.register("heal_orb", () -> new HealorbItem());
	public static final RegistryObject<Item> SPEED_ORB = REGISTRY.register("speed_orb", () -> new SpeedorbItem());
	public static final RegistryObject<Item> STRENGH_ORB = REGISTRY.register("strengh_orb", () -> new StrenghorbItem());
	public static final RegistryObject<Item> JUMP_ORB = REGISTRY.register("jump_orb", () -> new JumporbItem());
	public static final RegistryObject<Item> KNOCKBACK_ORB = REGISTRY.register("knockback_orb", () -> new KnockbackorbItem());
	public static final RegistryObject<Item> SPEED_MODIFIER = REGISTRY.register("speed_modifier", () -> new SpeedmodifierItem());
	public static final RegistryObject<Item> KNOCKBACK_MODIFIER = REGISTRY.register("knockback_modifier", () -> new KnockbackmodifierItem());
	public static final RegistryObject<Item> FLAME_MODIFIER = REGISTRY.register("flame_modifier", () -> new FlamemodifierItem());
	public static final RegistryObject<Item> FORTUNE_MODIFIER = REGISTRY.register("fortune_modifier", () -> new ForturnemodifierItem());
	public static final RegistryObject<Item> SPEEDSTICK = REGISTRY.register("speedstick", () -> new SpeedstickItem());
	public static final RegistryObject<Item> JUMPSTICK = REGISTRY.register("jumpstick", () -> new JumpstickItem());
	public static final RegistryObject<Item> HYPERJUMPSTICK = REGISTRY.register("hyperjumpstick", () -> new HyperjumpstickItem());
	public static final RegistryObject<Item> HEALSTICK = REGISTRY.register("healstick", () -> new HealstickItem());
	public static final RegistryObject<Item> STRENGHTSTICK = REGISTRY.register("strenghtstick", () -> new StrenghtstickItem());
	public static final RegistryObject<Item> DAMAGESTICK = REGISTRY.register("damagestick", () -> new DamagestickItem());
	public static final RegistryObject<Item> STICKOFGODS = REGISTRY.register("stickofgods", () -> new StickofgodsItem());
	public static final RegistryObject<Item> PALADIUMGREENPICKAXE = REGISTRY.register("paladiumgreenpickaxe", () -> new PaladiumgreenpickaxeItem());
	public static final RegistryObject<Item> PALADIUMGREENAXE = REGISTRY.register("paladiumgreenaxe", () -> new PaladiumgreenaxeItem());
	public static final RegistryObject<Item> PALADIUMGREENSWORD = REGISTRY.register("paladiumgreensword", () -> new PaladiumgreenswordItem());
	public static final RegistryObject<Item> PALADIUMGREENSHOVEL = REGISTRY.register("paladiumgreenshovel", () -> new PaladiumgreenshovelItem());
	public static final RegistryObject<Item> GREEN_PALADIUM_INGOT = REGISTRY.register("green_paladium_ingot", () -> new PaladiumGreeningotItem());
	public static final RegistryObject<Item> PALADIUM_GREEN_ORE = block(PalamodModBlocks.PALADIUM_GREEN_ORE);
	public static final RegistryObject<Item> PALADIUM_GREEN_BLOCK = block(PalamodModBlocks.PALADIUM_GREEN_BLOCK);
	public static final RegistryObject<Item> ALCHIMET_1 = block(PalamodModBlocks.ALCHIMET_1);
	public static final RegistryObject<Item> GRINDER_CASING = block(PalamodModBlocks.GRINDER_CASING);
	public static final RegistryObject<Item> GRINDER_FRAME = block(PalamodModBlocks.GRINDER_FRAME);
	public static final RegistryObject<Item> GRINDER_BLOCK = block(PalamodModBlocks.GRINDER_BLOCK);
	public static final RegistryObject<Item> PALADIUM_FURNACE = block(PalamodModBlocks.PALADIUM_FURNACE);
	public static final RegistryObject<Item> PALADIUM_FURNACE_ON = block(PalamodModBlocks.PALADIUM_FURNACE_ON);
	public static final RegistryObject<Item> AXE_HEAD = REGISTRY.register("axe_head", () -> new AxeheadItem());
	public static final RegistryObject<Item> PICKAXE_HEAD = REGISTRY.register("pickaxe_head", () -> new PickaxeheadItem());
	public static final RegistryObject<Item> HAMMER_HEAD = REGISTRY.register("hammer_head", () -> new HammerheadItem());
	public static final RegistryObject<Item> FASTSWORD_HEAD = REGISTRY.register("fastsword_head", () -> new FastswordheadItem());
	public static final RegistryObject<Item> BROADSWORD_HEAD = REGISTRY.register("broadsword_head", () -> new BroadswordheadItem());
	public static final RegistryObject<Item> SHOVEL_HEAD = REGISTRY.register("shovel_head", () -> new ShovelheadItem());
	public static final RegistryObject<Item> SWORD_HEAD = REGISTRY.register("sword_head", () -> new SwordheadItem());
	public static final RegistryObject<Item> AXE_PARTERN = REGISTRY.register("axe_partern", () -> new AxeparternItem());
	public static final RegistryObject<Item> PICKAXE_PATERN = REGISTRY.register("pickaxe_patern", () -> new PickaxepaternItem());
	public static final RegistryObject<Item> BROADSWORD_PATERN = REGISTRY.register("broadsword_patern", () -> new BroadswordpaternItem());
	public static final RegistryObject<Item> BLOCK_PATERN = REGISTRY.register("block_patern", () -> new BlockpaternItem());
	public static final RegistryObject<Item> FASTSWORD_PATERN = REGISTRY.register("fastsword_patern", () -> new FastswordpaternItem());
	public static final RegistryObject<Item> INGOT_PATERN = REGISTRY.register("ingot_patern", () -> new IngotpaternItem());
	public static final RegistryObject<Item> HAMMER_PATERN = REGISTRY.register("hammer_patern", () -> new HammerpaternItem());
	public static final RegistryObject<Item> SWORD_PATERN = REGISTRY.register("sword_patern", () -> new SwordpaternItem());
	public static final RegistryObject<Item> SHOVEL_PATERN = REGISTRY.register("shovel_patern", () -> new ShovelpaternItem());
	public static final RegistryObject<Item> PALADIUMBROADSWORD = REGISTRY.register("paladiumbroadsword", () -> new PaladiumbroadswordItem());
	public static final RegistryObject<Item> TITANEBROADSWORD = REGISTRY.register("titanebroadsword", () -> new TitanebroadswordItem());
	public static final RegistryObject<Item> AMETHYST_BROADSWORD = REGISTRY.register("amethyst_broadsword", () -> new AmethystebroadswordItem());
	public static final RegistryObject<Item> AMETHYST_FASTSWORD = REGISTRY.register("amethyst_fastsword", () -> new AmethystefastswordItem());
	public static final RegistryObject<Item> AMETHYST_HAMMER = REGISTRY.register("amethyst_hammer", () -> new AmethystehammerItem());
	public static final RegistryObject<Item> TITANE_HAMMER = REGISTRY.register("titane_hammer", () -> new TitanehammerItem());
	public static final RegistryObject<Item> PALADIUM_HAMMER = REGISTRY.register("paladium_hammer", () -> new PaladiumhammerItem());
	public static final RegistryObject<Item> OBSIDIAN_TRAPDOOR = block(PalamodModBlocks.OBSIDIAN_TRAPDOOR);
	public static final RegistryObject<Item> RENFORCED_OBSIDIAN = block(PalamodModBlocks.RENFORCED_OBSIDIAN);
	public static final RegistryObject<Item> OBSIDIAN_DOOR = doubleBlock(PalamodModBlocks.OBSIDIAN_DOOR);
	public static final RegistryObject<Item> COMPACTED_OBSIDIAN = block(PalamodModBlocks.COMPACTED_OBSIDIAN);
	public static final RegistryObject<Item> FAKE_WATER_OBSIDIAN = block(PalamodModBlocks.FAKE_WATER_OBSIDIAN);
	public static final RegistryObject<Item> LAVA_OBSIDIAN = block(PalamodModBlocks.LAVA_OBSIDIAN);
	public static final RegistryObject<Item> IRON_SPIKE = block(PalamodModBlocks.IRON_SPIKE);
	public static final RegistryObject<Item> SPIKE_GOLD = block(PalamodModBlocks.SPIKE_GOLD);
	public static final RegistryObject<Item> DIAMOND_SPIKE = block(PalamodModBlocks.DIAMOND_SPIKE);
	public static final RegistryObject<Item> AMETHYST_SPIKE = block(PalamodModBlocks.AMETHYST_SPIKE);
	public static final RegistryObject<Item> TITANE_SPIKE = block(PalamodModBlocks.TITANE_SPIKE);
	public static final RegistryObject<Item> PALADIUM_SPIKE = block(PalamodModBlocks.PALADIUM_SPIKE);
	public static final RegistryObject<Item> GOLD_MIXEDCOAL = REGISTRY.register("gold_mixedcoal", () -> new GoldmixedcoalItem());
	public static final RegistryObject<Item> AMETHYST_MIXEDCOAL = REGISTRY.register("amethyst_mixedcoal", () -> new AmethystmixedcoalItem());
	public static final RegistryObject<Item> TITANE_MIXED_COAL = REGISTRY.register("titane_mixed_coal", () -> new TitanemixedcoalItem());
	public static final RegistryObject<Item> PALADIUM_FORGE = block(PalamodModBlocks.PALADIUM_FORGE);
	public static final RegistryObject<Item> TITANEFASTSWORD = REGISTRY.register("titanefastsword", () -> new TitanefastswordItem());
	public static final RegistryObject<Item> TITANE_SLAB = block(PalamodModBlocks.TITANE_SLAB);
	public static final RegistryObject<Item> TITANE_STAIRS = block(PalamodModBlocks.TITANE_STAIRS);
	public static final RegistryObject<Item> LOADBLOCK_1T = block(PalamodModBlocks.LOADBLOCK_1T);
	public static final RegistryObject<Item> SOCKET_PATERN = REGISTRY.register("socket_patern", () -> new SocketpaternItem());
	public static final RegistryObject<Item> PALADIUMFASTSWORD = REGISTRY.register("paladiumfastsword", () -> new PaladiumfastswordItem());
	public static final RegistryObject<Item> SMELT_MODIFIER = REGISTRY.register("smelt_modifier", () -> new SmeltmodifierItem());
	public static final RegistryObject<Item> ENDIUM_HAMMER = REGISTRY.register("endium_hammer", () -> new EndiumhammerItem());
	public static final RegistryObject<Item> TCV_2 = block(PalamodModBlocks.TCV_2);
	public static final RegistryObject<Item> LEGENDARY_STONE_FORTUNE = REGISTRY.register("legendary_stone_fortune", () -> new LegendarystonefortuneItem());
	public static final RegistryObject<Item> LEGENDARY_STONE_INVISIBLE = REGISTRY.register("legendary_stone_invisible", () -> new LegendarystoneinvisibleItem());
	public static final RegistryObject<Item> ASEMBLING_TABLE = block(PalamodModBlocks.ASEMBLING_TABLE);
	public static final RegistryObject<Item> LEGENDARY_STONE_POWER = REGISTRY.register("legendary_stone_power", () -> new LegendarystonepowerItem());
	public static final RegistryObject<Item> LEGENDARY_STONE_JOBS = REGISTRY.register("legendary_stone_jobs", () -> new LegendarystonejobsItem());
	public static final RegistryObject<Item> LEGENDARY_STONE_TELEPORTATION = REGISTRY.register("legendary_stone_teleportation", () -> new LegendarystoneteleportationItem());
	public static final RegistryObject<Item> LEGENDARY_STONE_RANDOM = REGISTRY.register("legendary_stone_random", () -> new LegendarystonerandomItem());
	public static final RegistryObject<Item> EGGPLANT_0 = block(PalamodModBlocks.EGGPLANT_0);
	public static final RegistryObject<Item> EGGPLANT_1 = block(PalamodModBlocks.EGGPLANT_1);
	public static final RegistryObject<Item> EGGPLANT_2 = block(PalamodModBlocks.EGGPLANT_2);
	public static final RegistryObject<Item> EGGPLANT_3 = block(PalamodModBlocks.EGGPLANT_3);
	public static final RegistryObject<Item> PALADIUM_MACHINE = block(PalamodModBlocks.PALADIUM_MACHINE);
	public static final RegistryObject<Item> LUCKY_BLOCK = block(PalamodModBlocks.LUCKY_BLOCK);
	public static final RegistryObject<Item> CHERVIL_1 = block(PalamodModBlocks.CHERVIL_1);
	public static final RegistryObject<Item> CHERVIL_0 = block(PalamodModBlocks.CHERVIL_0);
	public static final RegistryObject<Item> CHERVIL_2 = block(PalamodModBlocks.CHERVIL_2);
	public static final RegistryObject<Item> CHERVIL_3 = block(PalamodModBlocks.CHERVIL_3);
	public static final RegistryObject<Item> KIWANO_4 = block(PalamodModBlocks.KIWANO_4);
	public static final RegistryObject<Item> KIWANO_3 = block(PalamodModBlocks.KIWANO_3);
	public static final RegistryObject<Item> KIWANO_2 = block(PalamodModBlocks.KIWANO_2);
	public static final RegistryObject<Item> KIWANO_1 = block(PalamodModBlocks.KIWANO_1);
	public static final RegistryObject<Item> KIWANO_0 = block(PalamodModBlocks.KIWANO_0);
	public static final RegistryObject<Item> WITHER_SHARD = REGISTRY.register("wither_shard", () -> new WithershardItem());
	public static final RegistryObject<Item> GREENPALADIUMARMOR_HELMET = REGISTRY.register("greenpaladiumarmor_helmet", () -> new GreenpaladiumarmorItem.Helmet());
	public static final RegistryObject<Item> GREENPALADIUMARMOR_CHESTPLATE = REGISTRY.register("greenpaladiumarmor_chestplate", () -> new GreenpaladiumarmorItem.Chestplate());
	public static final RegistryObject<Item> GREENPALADIUMARMOR_LEGGINGS = REGISTRY.register("greenpaladiumarmor_leggings", () -> new GreenpaladiumarmorItem.Leggings());
	public static final RegistryObject<Item> GREENPALADIUMARMOR_BOOTS = REGISTRY.register("greenpaladiumarmor_boots", () -> new GreenpaladiumarmorItem.Boots());
	public static final RegistryObject<Item> LUCKY_BETA = REGISTRY.register("lucky_beta", () -> new LuckybetaItem());
	public static final RegistryObject<Item> WEIGHTED_BOOTS = REGISTRY.register("weighted_boots", () -> new WeightedItem.Boots());
	public static final RegistryObject<Item> TRESAURE_FALSE = block(PalamodModBlocks.TRESAURE_FALSE);
	public static final RegistryObject<Item> TRESAURE_TRUE = block(PalamodModBlocks.TRESAURE_TRUE);
	public static final RegistryObject<Item> ALARM = block(PalamodModBlocks.ALARM);
	public static final RegistryObject<Item> MEGA_SAFE_CHEST = block(PalamodModBlocks.MEGA_SAFE_CHEST);
	public static final RegistryObject<Item> COLORED_LAMP = block(PalamodModBlocks.COLORED_LAMP);
	public static final RegistryObject<Item> COLOFUL_LAMP = block(PalamodModBlocks.COLOFUL_LAMP);
	public static final RegistryObject<Item> DYNAMITE = REGISTRY.register("dynamite", () -> new DynamiteItem());
	public static final RegistryObject<Item> ENDIUM_DYNAMITE = REGISTRY.register("endium_dynamite", () -> new EndiumdynaItem());
	public static final RegistryObject<Item> BIG_DYNAMITE = REGISTRY.register("big_dynamite", () -> new BigdynamiteItem());
	public static final RegistryObject<Item> DIAMOND_STRING = REGISTRY.register("diamond_string", () -> new DiamondstringItem());
	public static final RegistryObject<Item> PALADIUM_PHONE = REGISTRY.register("paladium_phone", () -> new PaladiumphoneItem());
	public static final RegistryObject<Item> FAKE_PALADIUM_ORE = block(PalamodModBlocks.FAKE_PALADIUM_ORE);
	public static final RegistryObject<Item> MONEY_OTHER = REGISTRY.register("money_other", () -> new MoneyotherItem());
	public static final RegistryObject<Item> ORANGEBLUE_1 = block(PalamodModBlocks.ORANGEBLUE_1);
	public static final RegistryObject<Item> ORANGEBLUE_0 = block(PalamodModBlocks.ORANGEBLUE_0);
	public static final RegistryObject<Item> ORANGEBLUE_2 = block(PalamodModBlocks.ORANGEBLUE_2);
	public static final RegistryObject<Item> ORANGEBLUE_3 = block(PalamodModBlocks.ORANGEBLUE_3);
	public static final RegistryObject<Item> ORANGEBLUE_4 = block(PalamodModBlocks.ORANGEBLUE_4);
	public static final RegistryObject<Item> TRIXIUM_NBT_BLOCK = block(PalamodModBlocks.TRIXIUM_NBT_BLOCK);
	public static final RegistryObject<Item> TRIXIUM = REGISTRY.register("trixium", () -> new TrixiumItem());
	public static final RegistryObject<Item> PALADIUM_STAIRS = block(PalamodModBlocks.PALADIUM_STAIRS);
	public static final RegistryObject<Item> PALADIUM_SLAB = block(PalamodModBlocks.PALADIUM_SLAB);
	public static final RegistryObject<Item> AMETHYST_STAIRS = block(PalamodModBlocks.AMETHYST_STAIRS);
	public static final RegistryObject<Item> AMETHYST_SLAB = block(PalamodModBlocks.AMETHYST_SLAB);
	public static final RegistryObject<Item> FURNACE_UPGRADE = REGISTRY.register("furnace_upgrade", () -> new FurnaceupgradeItem());
	public static final RegistryObject<Item> WITHER_IMBUE_POTION = REGISTRY.register("wither_imbue_potion", () -> new WitherimbuepotionItem());
	public static final RegistryObject<Item> FIRE_IMBUE_POTION = REGISTRY.register("fire_imbue_potion", () -> new FireimbuepotionItem());
	public static final RegistryObject<Item> POISON_IMBUE_POTION = REGISTRY.register("poison_imbue_potion", () -> new PoisonimbuepotionItem());
	public static final RegistryObject<Item> PALADIUM_APPLE = REGISTRY.register("paladium_apple", () -> new PaladiumappleItem());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_1 = REGISTRY.register("pickaxeofthegodslv_1", () -> new Pickaxeofthegodslv1Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_2 = REGISTRY.register("pickaxeofthegodslv_2", () -> new Pickaxeofthegodslv2Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_3 = REGISTRY.register("pickaxeofthegodslv_3", () -> new Pickaxeofthegodslv3Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_4 = REGISTRY.register("pickaxeofthegodslv_4", () -> new Pickaxeofthegodslv4Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_5 = REGISTRY.register("pickaxeofthegodslv_5", () -> new Pickaxeofthegodslv5Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_6 = REGISTRY.register("pickaxeofthegodslv_6", () -> new Pickaxeofthegodslv6Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_7 = REGISTRY.register("pickaxeofthegodslv_7", () -> new Pickaxeofthegodslv7Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_8 = REGISTRY.register("pickaxeofthegodslv_8", () -> new Pickaxeofthegodslv8Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_9 = REGISTRY.register("pickaxeofthegodslv_9", () -> new Pickaxeofthegodslv9Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_10 = REGISTRY.register("pickaxeofthegodslv_10", () -> new Pickaxeofthegodslv10Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_11 = REGISTRY.register("pickaxeofthegodslv_11", () -> new Pickaxeofthegodslv11Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_12 = REGISTRY.register("pickaxeofthegodslv_12", () -> new Pickaxeofthegodslv12Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_14 = REGISTRY.register("pickaxeofthegodslv_14", () -> new Pickaxeofthegodslv14Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_15 = REGISTRY.register("pickaxeofthegodslv_15", () -> new Pickaxeofthegodslv15Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_16 = REGISTRY.register("pickaxeofthegodslv_16", () -> new Pickaxeofthegodslv16Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_17 = REGISTRY.register("pickaxeofthegodslv_17", () -> new Pickaxeofthegodslv17Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_18 = REGISTRY.register("pickaxeofthegodslv_18", () -> new Pickaxeofthegodslv18Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_19 = REGISTRY.register("pickaxeofthegodslv_19", () -> new Pickaxeofthegodslv19Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_20 = REGISTRY.register("pickaxeofthegodslv_20", () -> new Pickaxeofthegodslv20Item());
	public static final RegistryObject<Item> PICKAXEOFTHEGODSLV_13 = REGISTRY.register("pickaxeofthegodslv_13", () -> new Pickaxeofthegodslv13Item());
	public static final RegistryObject<Item> AMETHYST_EXCACVATOR = REGISTRY.register("amethyst_excacvator", () -> new AmethystexacvatorItem());
	public static final RegistryObject<Item> TITANEEXCAVATOR = REGISTRY.register("titaneexcavator", () -> new TitaneexcavatorItem());
	public static final RegistryObject<Item> PALADIUMEXCAVATOR = REGISTRY.register("paladiumexcavator", () -> new PaladiumexcavatorItem());
	public static final RegistryObject<Item> BIG_HOLE_UPGRADE = REGISTRY.register("big_hole_upgrade", () -> new BigholeupgradeItem());
	public static final RegistryObject<Item> VOIDSTONE = REGISTRY.register("voidstone", () -> new VoidstoneItem());
	public static final RegistryObject<Item> AUTO_SMELT_UPGRADE_POTG = REGISTRY.register("auto_smelt_upgrade_potg", () -> new AutosmeltupgradepotgItem());
	public static final RegistryObject<Item> INFERNALKNOCKER = REGISTRY.register("infernalknocker", () -> new InfernalknockerItem());
	public static final RegistryObject<Item> TRAVELARMOR_HELMET = REGISTRY.register("travelarmor_helmet", () -> new TravelarmorItem.Helmet());
	public static final RegistryObject<Item> TRAVELARMOR_CHESTPLATE = REGISTRY.register("travelarmor_chestplate", () -> new TravelarmorItem.Chestplate());
	public static final RegistryObject<Item> TRAVELARMOR_LEGGINGS = REGISTRY.register("travelarmor_leggings", () -> new TravelarmorItem.Leggings());
	public static final RegistryObject<Item> TRAVELARMOR_BOOTS = REGISTRY.register("travelarmor_boots", () -> new TravelarmorItem.Boots());
	public static final RegistryObject<Item> SCUBA_HELMET = REGISTRY.register("scuba_helmet", () -> new ScubaItem.Helmet());
	public static final RegistryObject<Item> WING = REGISTRY.register("wing", () -> new WingItem());
	public static final RegistryObject<Item> ELEVATOR_WHITE = block(PalamodModBlocks.ELEVATOR_WHITE);
	public static final RegistryObject<Item> ELEVATO_RRED = block(PalamodModBlocks.ELEVATO_RRED);
	public static final RegistryObject<Item> ELEVATOR_BLUE = block(PalamodModBlocks.ELEVATOR_BLUE);
	public static final RegistryObject<Item> ELEVATOR_GREEN = block(PalamodModBlocks.ELEVATOR_GREEN);
	public static final RegistryObject<Item> ELEVATOR_PINK = block(PalamodModBlocks.ELEVATOR_PINK);
	public static final RegistryObject<Item> ELEVATORL_IGHT_BLUE = block(PalamodModBlocks.ELEVATORL_IGHT_BLUE);
	public static final RegistryObject<Item> ELEVATOR_LIGHT_GREEN = block(PalamodModBlocks.ELEVATOR_LIGHT_GREEN);
	public static final RegistryObject<Item> ELEVATOR_BROWN = block(PalamodModBlocks.ELEVATOR_BROWN);
	public static final RegistryObject<Item> ELEVATOR_ORANGE = block(PalamodModBlocks.ELEVATOR_ORANGE);
	public static final RegistryObject<Item> MINAGE_VOIDSTONE = REGISTRY.register("minage_voidstone", () -> new MinagevoidstoneItem());
	public static final RegistryObject<Item> CREATIVEPOTG = REGISTRY.register("creativepotg", () -> new CreativepotgItem());
	public static final RegistryObject<Item> ELEVATOR_PURPLE = block(PalamodModBlocks.ELEVATOR_PURPLE);
	public static final RegistryObject<Item> ELEVATOR_GRAY = block(PalamodModBlocks.ELEVATOR_GRAY);
	public static final RegistryObject<Item> ELEVATOR_LIGHT_GRAY = block(PalamodModBlocks.ELEVATOR_LIGHT_GRAY);
	public static final RegistryObject<Item> ELEVATOR_CYAN = block(PalamodModBlocks.ELEVATOR_CYAN);
	public static final RegistryObject<Item> PALADIUMGOLEM_SPAWN_EGG = REGISTRY.register("paladiumgolem_spawn_egg", () -> new ForgeSpawnEggItem(PalamodModEntities.PALADIUMGOLEM, -13369600, -52480, new Item.Properties()));
	public static final RegistryObject<Item> GUARDIAN_STONE = REGISTRY.register("guardian_stone", () -> new GuardianstoneItem());
	public static final RegistryObject<Item> GUARDIAN_BLOCK = block(PalamodModBlocks.GUARDIAN_BLOCK);
	public static final RegistryObject<Item> GREEN_PALADIUM_BROADSWORD_HEAD = REGISTRY.register("green_paladium_broadsword_head", () -> new HeadgreenbroadswordItem());
	public static final RegistryObject<Item> GREEN_PALADIUM_SWORD_HEAD = REGISTRY.register("green_paladium_sword_head", () -> new HeadgreenswordItem());
	public static final RegistryObject<Item> GREEN_PALADIUM_PICKAXE_HEAD = REGISTRY.register("green_paladium_pickaxe_head", () -> new HeadgreenpickaxeItem());
	public static final RegistryObject<Item> GREEN_PALADIUM_AXE_HEAD = REGISTRY.register("green_paladium_axe_head", () -> new HeadgreenaxeItem());
	public static final RegistryObject<Item> GREEN_PALADIUM_SHOVEL_HEAD = REGISTRY.register("green_paladium_shovel_head", () -> new HeadgreenshovelItem());
	public static final RegistryObject<Item> HEADENDIUMSWORD = REGISTRY.register("headendiumsword", () -> new HeadendiumswordItem());
	public static final RegistryObject<Item> HEAD_ENDIUM_PICKAXE = REGISTRY.register("head_endium_pickaxe", () -> new HeadendiumpickaxeItem());
	public static final RegistryObject<Item> HEAD_ENDIUM_AXE = REGISTRY.register("head_endium_axe", () -> new HeadendiumaxeItem());
	public static final RegistryObject<Item> GREENPALADIUMBROADSWORD = REGISTRY.register("greenpaladiumbroadsword", () -> new GreenpaladiumbroadswordItem());
	public static final RegistryObject<Item> ONE_MORE_MODIFIER = REGISTRY.register("one_more_modifier", () -> new OnemoremodifierItem());
	public static final RegistryObject<Item> ENDIUM_BROADSWORD_HEAD = REGISTRY.register("endium_broadsword_head", () -> new EndiumbroadswordheadItem());
	public static final RegistryObject<Item> ENDIUMBROADSWORD = REGISTRY.register("endiumbroadsword", () -> new EndiumbroadswordItem());
	public static final RegistryObject<Item> GREEN_PALADIUM_HAMMER = REGISTRY.register("green_paladium_hammer", () -> new GreenpaladiumhammerItem());
	public static final RegistryObject<Item> GREEN_PALADIUM_HAMMER_HEAD = REGISTRY.register("green_paladium_hammer_head", () -> new GreenpaladiumhammerheadItem());
	public static final RegistryObject<Item> ENDIUM_HAMMER_HEAD = REGISTRY.register("endium_hammer_head", () -> new EndiumhammerheadItem());
	public static final RegistryObject<Item> MAGICAL_TOOL = REGISTRY.register("magical_tool", () -> new MagicaltoolItem());
	public static final RegistryObject<Item> STONY = block(PalamodModBlocks.STONY);
	public static final RegistryObject<Item> CLOUD_BLOCK = block(PalamodModBlocks.CLOUD_BLOCK);
	public static final RegistryObject<Item> CROWN = block(PalamodModBlocks.CROWN);
	public static final RegistryObject<Item> FACTION_BLOCK = block(PalamodModBlocks.FACTION_BLOCK);
	public static final RegistryObject<Item> BLACK_LUCKY_BLOCK = block(PalamodModBlocks.BLACK_LUCKY_BLOCK);
	public static final RegistryObject<Item> ENFYUPOTION = REGISTRY.register("enfyupotion", () -> new EnfyupotionItem());
	public static final RegistryObject<Item> INVISIBLEARMOR_HELMET = REGISTRY.register("invisiblearmor_helmet", () -> new InvisiblearmorItem.Helmet());
	public static final RegistryObject<Item> INVISIBLEARMOR_CHESTPLATE = REGISTRY.register("invisiblearmor_chestplate", () -> new InvisiblearmorItem.Chestplate());
	public static final RegistryObject<Item> INVISIBLEARMOR_LEGGINGS = REGISTRY.register("invisiblearmor_leggings", () -> new InvisiblearmorItem.Leggings());
	public static final RegistryObject<Item> INVISIBLEARMOR_BOOTS = REGISTRY.register("invisiblearmor_boots", () -> new InvisiblearmorItem.Boots());
	public static final RegistryObject<Item> RAINBOWARMOR_HELMET = REGISTRY.register("rainbowarmor_helmet", () -> new RanbowarmorItem.Helmet());
	public static final RegistryObject<Item> RAINBOWARMOR_CHESTPLATE = REGISTRY.register("rainbowarmor_chestplate", () -> new RanbowarmorItem.Chestplate());
	public static final RegistryObject<Item> RAINBOWARMOR_LEGGINGS = REGISTRY.register("rainbowarmor_leggings", () -> new RanbowarmorItem.Leggings());
	public static final RegistryObject<Item> RAINBOWARMOR_BOOTS = REGISTRY.register("rainbowarmor_boots", () -> new RanbowarmorItem.Boots());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_1_HELMET = REGISTRY.register("paladiumarmorcustom_1_helmet", () -> new Paladiumarmorcustom1Item.Helmet());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_1_CHESTPLATE = REGISTRY.register("paladiumarmorcustom_1_chestplate", () -> new Paladiumarmorcustom1Item.Chestplate());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_1_LEGGINGS = REGISTRY.register("paladiumarmorcustom_1_leggings", () -> new Paladiumarmorcustom1Item.Leggings());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_1_BOOTS = REGISTRY.register("paladiumarmorcustom_1_boots", () -> new Paladiumarmorcustom1Item.Boots());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_2_HELMET = REGISTRY.register("paladiumarmorcustom_2_helmet", () -> new Paladiumarmorcustom2Item.Helmet());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_2_CHESTPLATE = REGISTRY.register("paladiumarmorcustom_2_chestplate", () -> new Paladiumarmorcustom2Item.Chestplate());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_2_LEGGINGS = REGISTRY.register("paladiumarmorcustom_2_leggings", () -> new Paladiumarmorcustom2Item.Leggings());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_2_BOOTS = REGISTRY.register("paladiumarmorcustom_2_boots", () -> new Paladiumarmorcustom2Item.Boots());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_3_HELMET = REGISTRY.register("paladiumarmorcustom_3_helmet", () -> new Paladiumarmorcustom3Item.Helmet());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_3_CHESTPLATE = REGISTRY.register("paladiumarmorcustom_3_chestplate", () -> new Paladiumarmorcustom3Item.Chestplate());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_3_LEGGINGS = REGISTRY.register("paladiumarmorcustom_3_leggings", () -> new Paladiumarmorcustom3Item.Leggings());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_3_BOOTS = REGISTRY.register("paladiumarmorcustom_3_boots", () -> new Paladiumarmorcustom3Item.Boots());
	public static final RegistryObject<Item> FLYPOTION = REGISTRY.register("flypotion", () -> new FlypotionItem());
	public static final RegistryObject<Item> SPACE_FOOD = REGISTRY.register("space_food", () -> new SpacefoodItem());
	public static final RegistryObject<Item> JUDEECERCIS_DOOR = doubleBlock(PalamodModBlocks.JUDEECERCIS_DOOR);
	public static final RegistryObject<Item> CHUNKANASLYSER = REGISTRY.register("chunkanaslyser", () -> new ChunkanaslyserItem());
	public static final RegistryObject<Item> ENDIUM_LUCKY_BLOCK = block(PalamodModBlocks.ENDIUM_LUCKY_BLOCK);
	public static final RegistryObject<Item> ENDIUM_NUGGET_ORE = block(PalamodModBlocks.ENDIUM_NUGGET_ORE);
	public static final RegistryObject<Item> ENDIUM_SLAB = block(PalamodModBlocks.ENDIUM_SLAB);
	public static final RegistryObject<Item> ENDIUM_STAIRS = block(PalamodModBlocks.ENDIUM_STAIRS);
	public static final RegistryObject<Item> GREEN_PALADIUM_STAIRS = block(PalamodModBlocks.GREEN_PALADIUM_STAIRS);
	public static final RegistryObject<Item> GREEN_PALADIUM_SLAB = block(PalamodModBlocks.GREEN_PALADIUM_SLAB);
	public static final RegistryObject<Item> UPLOADER = block(PalamodModBlocks.UPLOADER);
	public static final RegistryObject<Item> INTERNET_CARD = REGISTRY.register("internet_card", () -> new InternetcardItem());
	public static final RegistryObject<Item> SMALL_RING = REGISTRY.register("small_ring", () -> new SmallringItem());
	public static final RegistryObject<Item> MEDIUM_RING = REGISTRY.register("medium_ring", () -> new MediumringItem());
	public static final RegistryObject<Item> BIG_RING = REGISTRY.register("big_ring", () -> new BigringItem());
	public static final RegistryObject<Item> ENDIUM_SMALL_RING = REGISTRY.register("endium_small_ring", () -> new EndiumsmallringItem());
	public static final RegistryObject<Item> ENDIUM_MEDIUM_RING = REGISTRY.register("endium_medium_ring", () -> new EndiummediumringItem());
	public static final RegistryObject<Item> ENDIUM_BIG_RING = REGISTRY.register("endium_big_ring", () -> new EndiumbigringItem());
	public static final RegistryObject<Item> OSTRYA_DOOR = doubleBlock(PalamodModBlocks.OSTRYA_DOOR);
	public static final RegistryObject<Item> ERABLE_DOOR = doubleBlock(PalamodModBlocks.ERABLE_DOOR);
	public static final RegistryObject<Item> JACARANDA_DOOR = doubleBlock(PalamodModBlocks.JACARANDA_DOOR);
	public static final RegistryObject<Item> HDV_BLOCK = block(PalamodModBlocks.HDV_BLOCK);
	public static final RegistryObject<Item> ERABLETRAPDOOR = block(PalamodModBlocks.ERABLETRAPDOOR);
	public static final RegistryObject<Item> MONEY_ITEM = REGISTRY.register("money_item", () -> new MoneyitemItem());
	public static final RegistryObject<Item> PALADIUM_PARTICLE = REGISTRY.register("paladium_particle", () -> new PaladiumparticleItem());
	public static final RegistryObject<Item> FLATTEN_TITANE_CHEST = block(PalamodModBlocks.FLATTEN_TITANE_CHEST);
	public static final RegistryObject<Item> GREEN_PALADIUM_SMALL_RING = REGISTRY.register("green_paladium_small_ring", () -> new SmallringgreenpaladiumItem());
	public static final RegistryObject<Item> GREEN_PALADIUM_MEDIUM_RING = REGISTRY.register("green_paladium_medium_ring", () -> new MediumringgreenpaladiumItem());
	public static final RegistryObject<Item> GREEN_PALADIUM_BIG_RING = REGISTRY.register("green_paladium_big_ring", () -> new BigringgreenpaladiumItem());
	public static final RegistryObject<Item> HANG_GLIDER = REGISTRY.register("hang_glider", () -> new HanggliderItem());
	public static final RegistryObject<Item> FLATTEN_PALADIUM_CHEST = block(PalamodModBlocks.FLATTEN_PALADIUM_CHEST);
	public static final RegistryObject<Item> FLATTEN_AMETHYST_CHEST = block(PalamodModBlocks.FLATTEN_AMETHYST_CHEST);
	public static final RegistryObject<Item> PESYBLPOTION = REGISTRY.register("pesyblpotion", () -> new PesyblpotionItem());
	public static final RegistryObject<Item> GREEN_PALADIUM_PARTICLE = REGISTRY.register("green_paladium_particle", () -> new GreenpaladiumparticleItem());
	public static final RegistryObject<Item> COMPRESSED_GREEN_PALADUM = REGISTRY.register("compressed_green_paladum", () -> new CompressedgreenpaladumItem());
	public static final RegistryObject<Item> GREENPALADUMEXCATOR = REGISTRY.register("greenpaladumexcator", () -> new GreenpaladumexcatorItem());
	public static final RegistryObject<Item> CREATIVE_HAMMER = REGISTRY.register("creative_hammer", () -> new CreativehammerItem());
	public static final RegistryObject<Item> FLATTEN_GREEN_PALADIUM_CHEST = block(PalamodModBlocks.FLATTEN_GREEN_PALADIUM_CHEST);
	public static final RegistryObject<Item> FLATTEN_ENDIUM_CHEST = block(PalamodModBlocks.FLATTEN_ENDIUM_CHEST);
	public static final RegistryObject<Item> MONEY_1K = REGISTRY.register("money_1k", () -> new Moneye1k1Item());
	public static final RegistryObject<Item> DOWNLOADER = block(PalamodModBlocks.DOWNLOADER);
	public static final RegistryObject<Item> ALARM_ON = block(PalamodModBlocks.ALARM_ON);
	public static final RegistryObject<Item> CREATIVE_TRIXIUM_SWORD = REGISTRY.register("creative_trixium_sword", () -> new CreativetrixiumswordItem());
	public static final RegistryObject<Item> DEEPSLATE_AMETHYST_ORE = block(PalamodModBlocks.DEEPSLATE_AMETHYST_ORE);
	public static final RegistryObject<Item> DEEPSLATE_TITANE_ORE = block(PalamodModBlocks.DEEPSLATE_TITANE_ORE);
	public static final RegistryObject<Item> DEEPSLATE_PALADIUM_ORE = block(PalamodModBlocks.DEEPSLATE_PALADIUM_ORE);
	public static final RegistryObject<Item> DEEPSLATE_TRIXIUM_ORE = block(PalamodModBlocks.DEEPSLATE_TRIXIUM_ORE);
	public static final RegistryObject<Item> DEEPSLATE_GREEN_PALADIUM_ORE = block(PalamodModBlocks.DEEPSLATE_GREEN_PALADIUM_ORE);
	public static final RegistryObject<Item> DEEPSLATE_ENDIUM_NUGGET_ORE = block(PalamodModBlocks.DEEPSLATE_ENDIUM_NUGGET_ORE);
	public static final RegistryObject<Item> DEEPSLATE_FINDIUM_ORE = block(PalamodModBlocks.DEEPSLATE_FINDIUM_ORE);
	public static final RegistryObject<Item> TRIXIUM_ORE = block(PalamodModBlocks.TRIXIUM_ORE);
	public static final RegistryObject<Item> TRIXIUM_BLOCK = block(PalamodModBlocks.TRIXIUM_BLOCK);
	public static final RegistryObject<Item> ENDIUM_POLLEN = REGISTRY.register("endium_pollen", () -> new EndiumpollenItem());
	public static final RegistryObject<Item> POTATO_BACKPACK = REGISTRY.register("potato_backpack", () -> new PotatobackpackItem());
	public static final RegistryObject<Item> PALADIUM_POLLEN = REGISTRY.register("paladium_pollen", () -> new PaladiumpollenItem());
	public static final RegistryObject<Item> TITANE_POLLEN = REGISTRY.register("titane_pollen", () -> new TitanepollenItem());
	public static final RegistryObject<Item> AMETHYST_POLLEN = REGISTRY.register("amethyst_pollen", () -> new AmethystpollenItem());
	public static final RegistryObject<Item> AMETHYST_PARTICLE = REGISTRY.register("amethyst_particle", () -> new AmethystparticleItem());
	public static final RegistryObject<Item> TITANE_PARTICLE = REGISTRY.register("titane_particle", () -> new TitaneparticleItem());
	public static final RegistryObject<Item> DIAMOND_PARTICLE = REGISTRY.register("diamond_particle", () -> new DiamondparticleItem());
	public static final RegistryObject<Item> GOLD_PARTICLE = REGISTRY.register("gold_particle", () -> new GoldparticleItem());
	public static final RegistryObject<Item> IRON_PARTICLE = REGISTRY.register("iron_particle", () -> new IronparticleItem());
	public static final RegistryObject<Item> GREENPALADIUMFASTSWORD = REGISTRY.register("greenpaladiumfastsword", () -> new GreenpaladiumfastswordItem());
	public static final RegistryObject<Item> GREEN_PALADIUM_FASTSWORD_HEAD = REGISTRY.register("green_paladium_fastsword_head", () -> new GreenpaladiumfastswordheadItem());
	public static final RegistryObject<Item> ENDIUMFASTSWORD = REGISTRY.register("endiumfastsword", () -> new EndiumfastswordItem());
	public static final RegistryObject<Item> ENDIUM_FASTSWORD_HEAD = REGISTRY.register("endium_fastsword_head", () -> new EndiumfastswordheadItem());
	public static final RegistryObject<Item> ENDIUM_SHOVEL_HEAD = REGISTRY.register("endium_shovel_head", () -> new EndiumshovelheadItem());
	public static final RegistryObject<Item> ENDIUMSHOVEL = REGISTRY.register("endiumshovel", () -> new EndiumshovelItem());
	public static final RegistryObject<Item> CAVE_BLOCK = block(PalamodModBlocks.CAVE_BLOCK);
	public static final RegistryObject<Item> MIICHALENGE = REGISTRY.register("miichalenge", () -> new MiichalengeItem());
	public static final RegistryObject<Item> FUZEDISC = REGISTRY.register("fuzedisc", () -> new FuzediscItem());
	public static final RegistryObject<Item> ENDIUM_FRAGMENT = REGISTRY.register("endium_fragment", () -> new EndiumfragmentItem());
	public static final RegistryObject<Item> FLAT_CHEST_UPGRADE = REGISTRY.register("flat_chest_upgrade", () -> new FlatchestupgradeItem());
	public static final RegistryObject<Item> PALADIUM_CHEST = block(PalamodModBlocks.PALADIUM_CHEST);
	public static final RegistryObject<Item> GREEN_PALADIUM_CHEST = block(PalamodModBlocks.GREEN_PALADIUM_CHEST);
	public static final RegistryObject<Item> AMETHYST_CHEST = block(PalamodModBlocks.AMETHYST_CHEST);
	public static final RegistryObject<Item> ENDIUM_CHEST = block(PalamodModBlocks.ENDIUM_CHEST);
	public static final RegistryObject<Item> TITANE_CHEST = block(PalamodModBlocks.TITANE_CHEST);
	public static final RegistryObject<Item> WOODEN_SPIKE = block(PalamodModBlocks.WOODEN_SPIKE);
	public static final RegistryObject<Item> WOODEN_OBSIDIAN_SPIKE = block(PalamodModBlocks.WOODEN_OBSIDIAN_SPIKE);
	public static final RegistryObject<Item> IRON_OBSIDIAN_SPIKE = block(PalamodModBlocks.IRON_OBSIDIAN_SPIKE);
	public static final RegistryObject<Item> GOLDEN_OBSIDIAN_SPIKE = block(PalamodModBlocks.GOLDEN_OBSIDIAN_SPIKE);
	public static final RegistryObject<Item> DIAMOND_OBSIDIAN_SPIKE = block(PalamodModBlocks.DIAMOND_OBSIDIAN_SPIKE);
	public static final RegistryObject<Item> AMETHYS_TOBSIDIAN_SPIKE = block(PalamodModBlocks.AMETHYS_TOBSIDIAN_SPIKE);
	public static final RegistryObject<Item> TITANE_OBSIDIAN_SPIKE = block(PalamodModBlocks.TITANE_OBSIDIAN_SPIKE);
	public static final RegistryObject<Item> PALADIUM_OBSIDIAN_SPIKE = block(PalamodModBlocks.PALADIUM_OBSIDIAN_SPIKE);
	public static final RegistryObject<Item> ONLINE_DETECTOR = block(PalamodModBlocks.ONLINE_DETECTOR);
	public static final RegistryObject<Item> ONLINE_DETECTOR_ON = block(PalamodModBlocks.ONLINE_DETECTOR_ON);
	public static final RegistryObject<Item> COBBLEBREAKER = block(PalamodModBlocks.COBBLEBREAKER);
	public static final RegistryObject<Item> OBSIDIANPICKAXE = REGISTRY.register("obsidianpickaxe", () -> new ObsidianpickaxeItem());
	public static final RegistryObject<Item> DOLLARS_STONE = REGISTRY.register("dollars_stone", () -> new MoulastoneItem());
	public static final RegistryObject<Item> COBBLEBREAKER_AMETHYST_UPGRADE = REGISTRY.register("cobblebreaker_amethyst_upgrade", () -> new CobblebreakeramethystupgradeItem());
	public static final RegistryObject<Item> COBBLEBREAKER_TITANE_UPGRADE = REGISTRY.register("cobblebreaker_titane_upgrade", () -> new CobblebreakertitaneupgradeItem());
	public static final RegistryObject<Item> COBBLEBREAKER_PALADIUM_UPGRADE = REGISTRY.register("cobblebreaker_paladium_upgrade", () -> new CobblebreakerpaladiumupgradeItem());
	public static final RegistryObject<Item> FERTILZED_DIRT = block(PalamodModBlocks.FERTILZED_DIRT);
	public static final RegistryObject<Item> AMETHYST_HOE = REGISTRY.register("amethyst_hoe", () -> new AmethtysthoeItem());
	public static final RegistryObject<Item> TITANEHOE = REGISTRY.register("titanehoe", () -> new TitanehoeItem());
	public static final RegistryObject<Item> PALADIUM_HOE = REGISTRY.register("paladium_hoe", () -> new PaladiumhoeItem());
	public static final RegistryObject<Item> GREEN_PALADIUM_HOE = REGISTRY.register("green_paladium_hoe", () -> new GreenpaladiumhoeItem());
	public static final RegistryObject<Item> ENDIUM_HOE = REGISTRY.register("endium_hoe", () -> new EndiumhoeItem());
	public static final RegistryObject<Item> AMETHYST_SEEDPLANTER = REGISTRY.register("amethyst_seedplanter", () -> new AmethystseedplanterItem());
	public static final RegistryObject<Item> TITANE_SEEDPLANTER = REGISTRY.register("titane_seedplanter", () -> new TitaneseedplanterItem());
	public static final RegistryObject<Item> PALADIUM_SEEDPLANTER = REGISTRY.register("paladium_seedplanter", () -> new PaladiumseedplanterItem());
	public static final RegistryObject<Item> GREEN_PALADIUM_SEEDPLANTER = REGISTRY.register("green_paladium_seedplanter", () -> new GreenpaladiumseedplanterItem());
	public static final RegistryObject<Item> ENDIUM_SEEDPLANTER = REGISTRY.register("endium_seedplanter", () -> new EndiumseedplanterItem());
	public static final RegistryObject<Item> PRINTINGPRESS = block(PalamodModBlocks.PRINTINGPRESS);
	public static final RegistryObject<Item> PLATE = REGISTRY.register("plate", () -> new PlateItem());
	public static final RegistryObject<Item> TYPESETTINGTABLE = block(PalamodModBlocks.TYPESETTINGTABLE);
	public static final RegistryObject<Item> TYPESETTINGBOOK = block(PalamodModBlocks.TYPESETTINGBOOK);
	public static final RegistryObject<Item> TYPESETTINGPLATE = block(PalamodModBlocks.TYPESETTINGPLATE);
	public static final RegistryObject<Item> TYPESETTINGMAX = block(PalamodModBlocks.TYPESETTINGMAX);
	public static final RegistryObject<Item> ANTIFUZEDISC = REGISTRY.register("antifuzedisc", () -> new AntifuzediscItem());
	public static final RegistryObject<Item> ROULETTEPALADIENNEDISC = REGISTRY.register("roulettepaladiennedisc", () -> new RoulettepaladiennediscItem());
	public static final RegistryObject<Item> CLASHKUMIZ = REGISTRY.register("clashkumiz", () -> new ClashkumizItem());
	public static final RegistryObject<Item> DRAWBRIDGE = block(PalamodModBlocks.DRAWBRIDGE);
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_4_HELMET = REGISTRY.register("paladiumarmorcustom_4_helmet", () -> new Paladiumarmorcustom4Item.Helmet());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_4_CHESTPLATE = REGISTRY.register("paladiumarmorcustom_4_chestplate", () -> new Paladiumarmorcustom4Item.Chestplate());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_4_LEGGINGS = REGISTRY.register("paladiumarmorcustom_4_leggings", () -> new Paladiumarmorcustom4Item.Leggings());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_4_BOOTS = REGISTRY.register("paladiumarmorcustom_4_boots", () -> new Paladiumarmorcustom4Item.Boots());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_5_HELMET = REGISTRY.register("paladiumarmorcustom_5_helmet", () -> new Paladiumarmorcustom5Item.Helmet());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_5_CHESTPLATE = REGISTRY.register("paladiumarmorcustom_5_chestplate", () -> new Paladiumarmorcustom5Item.Chestplate());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_5_LEGGINGS = REGISTRY.register("paladiumarmorcustom_5_leggings", () -> new Paladiumarmorcustom5Item.Leggings());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_5_BOOTS = REGISTRY.register("paladiumarmorcustom_5_boots", () -> new Paladiumarmorcustom5Item.Boots());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_6_HELMET = REGISTRY.register("paladiumarmorcustom_6_helmet", () -> new Paladiumarmorcustom6Item.Helmet());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_6_CHESTPLATE = REGISTRY.register("paladiumarmorcustom_6_chestplate", () -> new Paladiumarmorcustom6Item.Chestplate());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_6_LEGGINGS = REGISTRY.register("paladiumarmorcustom_6_leggings", () -> new Paladiumarmorcustom6Item.Leggings());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_6_BOOTS = REGISTRY.register("paladiumarmorcustom_6_boots", () -> new Paladiumarmorcustom6Item.Boots());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_7_HELMET = REGISTRY.register("paladiumarmorcustom_7_helmet", () -> new Paladiumarmorcustom7Item.Helmet());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_7_CHESTPLATE = REGISTRY.register("paladiumarmorcustom_7_chestplate", () -> new Paladiumarmorcustom7Item.Chestplate());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_7_LEGGINGS = REGISTRY.register("paladiumarmorcustom_7_leggings", () -> new Paladiumarmorcustom7Item.Leggings());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_7_BOOTS = REGISTRY.register("paladiumarmorcustom_7_boots", () -> new Paladiumarmorcustom7Item.Boots());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_8_HELMET = REGISTRY.register("paladiumarmorcustom_8_helmet", () -> new Paladiumarmorcustom8Item.Helmet());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_8_CHESTPLATE = REGISTRY.register("paladiumarmorcustom_8_chestplate", () -> new Paladiumarmorcustom8Item.Chestplate());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_8_LEGGINGS = REGISTRY.register("paladiumarmorcustom_8_leggings", () -> new Paladiumarmorcustom8Item.Leggings());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_8_BOOTS = REGISTRY.register("paladiumarmorcustom_8_boots", () -> new Paladiumarmorcustom8Item.Boots());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_9_HELMET = REGISTRY.register("paladiumarmorcustom_9_helmet", () -> new Paladiumarmorcustom9Item.Helmet());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_9_CHESTPLATE = REGISTRY.register("paladiumarmorcustom_9_chestplate", () -> new Paladiumarmorcustom9Item.Chestplate());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_9_LEGGINGS = REGISTRY.register("paladiumarmorcustom_9_leggings", () -> new Paladiumarmorcustom9Item.Leggings());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_9_BOOTS = REGISTRY.register("paladiumarmorcustom_9_boots", () -> new Paladiumarmorcustom9Item.Boots());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_10_HELMET = REGISTRY.register("paladiumarmorcustom_10_helmet", () -> new Paladiumarmorcustom10Item.Helmet());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_10_CHESTPLATE = REGISTRY.register("paladiumarmorcustom_10_chestplate", () -> new Paladiumarmorcustom10Item.Chestplate());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_10_LEGGINGS = REGISTRY.register("paladiumarmorcustom_10_leggings", () -> new Paladiumarmorcustom10Item.Leggings());
	public static final RegistryObject<Item> PALADIUMARMORCUSTOM_10_BOOTS = REGISTRY.register("paladiumarmorcustom_10_boots", () -> new Paladiumarmorcustom10Item.Boots());
	public static final RegistryObject<Item> UNKNOWNBLOCK = block(PalamodModBlocks.UNKNOWNBLOCK);
	public static final RegistryObject<Item> COMPRESSEDSPONGE = block(PalamodModBlocks.COMPRESSEDSPONGE);
	public static final RegistryObject<Item> SPONGETNT = block(PalamodModBlocks.SPONGETNT);
	public static final RegistryObject<Item> LAVASPONGE = block(PalamodModBlocks.LAVASPONGE);
	public static final RegistryObject<Item> WETLAVASPONGE = block(PalamodModBlocks.WETLAVASPONGE);
	public static final RegistryObject<Item> WITHERTNT = block(PalamodModBlocks.WITHERTNT);
	public static final RegistryObject<Item> MAGIC_TNT = block(PalamodModBlocks.MAGIC_TNT);
	public static final RegistryObject<Item> COMPACTTNT = block(PalamodModBlocks.COMPACTTNT);
	public static final RegistryObject<Item> ENDIUMTNT = block(PalamodModBlocks.ENDIUMTNT);
	public static final RegistryObject<Item> RENFORCEDOBSIDIANSTAIRS = block(PalamodModBlocks.RENFORCEDOBSIDIANSTAIRS);
	public static final RegistryObject<Item> OBSIDIANSTAIRS = block(PalamodModBlocks.OBSIDIANSTAIRS);
	public static final RegistryObject<Item> OBSIDIANSLAB = block(PalamodModBlocks.OBSIDIANSLAB);
	public static final RegistryObject<Item> HARDENEDOBSIDIANSLAB = block(PalamodModBlocks.HARDENEDOBSIDIANSLAB);
	public static final RegistryObject<Item> FAKEWTER_BUCKET = REGISTRY.register("fakewter_bucket", () -> new FakewterItem());
	public static final RegistryObject<Item> ANGELICWTER_BUCKET = REGISTRY.register("angelicwter_bucket", () -> new AngelicwterItem());
	public static final RegistryObject<Item> SLIMEOBSIDIAN = block(PalamodModBlocks.SLIMEOBSIDIAN);
	public static final RegistryObject<Item> POISONOBSIDIAN = block(PalamodModBlocks.POISONOBSIDIAN);
	public static final RegistryObject<Item> SEALEDXPBOTTLE = REGISTRY.register("sealedxpbottle", () -> new SealedxpbottleItem());
	public static final RegistryObject<Item> MIXEDENDIUMINGOT = REGISTRY.register("mixedendiumingot", () -> new MixedendiumingotItem());
	public static final RegistryObject<Item> MIXEDENDIUMARMOR_HELMET = REGISTRY.register("mixedendiumarmor_helmet", () -> new MixedendiumarmorItem.Helmet());
	public static final RegistryObject<Item> MIXEDENDIUMARMOR_CHESTPLATE = REGISTRY.register("mixedendiumarmor_chestplate", () -> new MixedendiumarmorItem.Chestplate());
	public static final RegistryObject<Item> MIXEDENDIUMARMOR_LEGGINGS = REGISTRY.register("mixedendiumarmor_leggings", () -> new MixedendiumarmorItem.Leggings());
	public static final RegistryObject<Item> MIXEDENDIUMARMOR_BOOTS = REGISTRY.register("mixedendiumarmor_boots", () -> new MixedendiumarmorItem.Boots());
	public static final RegistryObject<Item> DOUBLEEXPPOTION = REGISTRY.register("doubleexppotion", () -> new DoubleexppotionItem());
	public static final RegistryObject<Item> X_10XPPOTION = REGISTRY.register("x_10xppotion", () -> new X10xppotionItem());
	public static final RegistryObject<Item> XPBOTTLE = REGISTRY.register("xpbottle", () -> new XpbottleItem());
	public static final RegistryObject<Item> EXCTRACTOR = block(PalamodModBlocks.EXCTRACTOR);
	public static final RegistryObject<Item> BOOMOBSIDIAN = block(PalamodModBlocks.BOOMOBSIDIAN);
	public static final RegistryObject<Item> MEGABOOMOBSIDIAN = block(PalamodModBlocks.MEGABOOMOBSIDIAN);

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}

	@SubscribeEvent
	public static void clientLoad(FMLClientSetupEvent event) {
		event.enqueueWork(() -> {
			ItemProperties.register(XPBOTTLE.get(), new ResourceLocation("palamod:xpbottle_xp"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetxpfrombottleProcedure.execute(itemStackToRender));
			ItemProperties.register(XPBOTTLE.get(), new ResourceLocation("palamod:xpbottle_jobs_type"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetjobsfrombottleProcedure.execute(itemStackToRender));
		});
	}
}
